# pandas
* https://pandas.pydata.org/
* spark 자료형
* pip install pandas
* conda install pandas

* numpy를 내부적으로 활용함
* 데이터분석에 특화된 데이터 구조 제공 (테이블, dataframe)
* 다양한 데이터분석 함수 제공
* 데이터베이스에 쉽게 연결 가능
* json 데이터 html의 table 요소를 dataframe으로 손쉽게 변형 가능

# Pandas에서 다루는 데이터 타입 2가지
## 1) DataFrame: 2차원 표형식 데이터
* python의 dict와 비슷하나 key에 list 형태의 value가 매칭된 형태
* {key:[value1, value2, value3], key2: [value1, value2, value3]}
## 2) Series: 1차원 벡터 형식 데이터
* python의 list, tuple, ndarray의 1차원 상태와 비슷
* 열벡터에 이름이 붙어있는 상태

In [1]:
import pandas as pd

# 데이터프레임 만들기
* pd.DataFrame({key1:[value1, value2], key2: [value1, value2]})

In [2]:
df = pd.DataFrame(
    {'이름' : ['홍길동','둘리','또치','도우너'],
    '주소': ['서울','의정부','고양','성남'],
    '취미' : ['음악감상','놀기','달리기','바이올린']}
)

In [6]:
print(type(df['이름'][:2]))
# series = list와 똑같은

<class 'pandas.core.series.Series'>

In [7]:
df.shape

(4, 3)

In [8]:
df.ndim

2

In [9]:
df['이름'].dtype

dtype('O')

# Series 만들기
* pd.Series([리스트 자료/튜플], name = "컬럼명")
* 이름을 가지고 있는 list /벡터
* dataframe에서 컬럼 1개를 잘라온 형태

In [11]:
ages = pd.Series([22,53,35], name="나이")
print(ages)
print(ages.dtype)

0    22
1    53
2    35
Name: 나이, dtype: int64
int64

In [12]:
ages[0] # 내부적으로 numpy로 바뀜

np.int64(22)

In [13]:
ages[::-1]

2    35
1    53
0    22
Name: 나이, dtype: int64

In [14]:
ages.max()

np.int64(53)

In [15]:
ages.sum()

np.int64(110)

In [16]:
ages.cumsum() #누적합

0     22
1     75
2    110
Name: 나이, dtype: int64

In [17]:
ages.mean()

np.float64(36.666666666666664)

In [18]:
ages.median()

np.float64(35.0)

# 판다스에서 자료 불러오기, 저장하기
* csv, tsv, excel, json, html, sql (+spark 타입)
* pd.read_확장자명(파일경로, 옵션)

### excel 파일 불러오기

In [19]:
df_excel=pd.read_excel("./data/Online Retail.xlsx")
df_excel

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [29]:
#df_excel2=pd.read_excel("./data/아파트(매매)_실거래가_20240806113828.xlsx")
# 데이터 이전에 정보들이 있는 경우
# 시트 이름(번호) or header 지정해서 원하는 위치의 데이터 불러오기 가능
df_excel2=pd.read_excel("./data/아파트(매매)_실거래가_20240806113828.xlsx",header=12, index_col=None)
df_excel2

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 영등포구 당산동5가,42,42,0,당산삼성래미안4차,115.7800,202407,31,"139,000",...,4,개인,개인,2003,당산로 214,-,직거래,-,-,아파트
1,2,강원특별자치도 원주시 지정면 가곡리,1512,1512,0,원주롯데캐슬골드파크1차(5단지),84.9644,202407,31,"38,900",...,10,개인,개인,2019,신지정로 250,20240802,중개거래,강원 원주시,-,아파트
2,3,대구광역시 달성군 화원읍 구라리,1650,1650,0,대곡역래미안,84.5958,202407,31,"29,500",...,11,개인,개인,2007,비슬로539길 35,-,중개거래,대구 달성군,-,아파트
3,4,광주광역시 남구 진월동,312-7,312,7,광명,70.6250,202407,31,"16,900",...,1,개인,개인,1998,광복마을길 63,-,중개거래,광주 남구,-,아파트
4,5,광주광역시 남구 진월동,331-93,331,93,중흥,84.8400,202407,31,"17,500",...,13,개인,개인,1992,서문대로749번마길 30,-,직거래,-,24.07.31,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,37576,서울특별시 송파구 장지동,849,849,0,송파파인타운3단지,84.9800,202407,1,"117,500",...,14,개인,개인,2008,충민로 152,-,중개거래,서울 송파구,-,아파트
37576,37577,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,000",...,8,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.10,아파트
37577,37578,광주광역시 광산구 비아동,152-5,152,5,호반,59.8800,202407,1,"15,400",...,5,개인,개인,1998,비아로 185,-,중개거래,광주 광산구,24.07.26,아파트
37578,37579,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,500",...,10,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.19,아파트
37579,37580,대구광역시 북구 읍내동,1366-2,1366,2,칠곡보성,84.9800,202407,1,"21,000",...,9,개인,개인,1992,구암로21길 26,-,중개거래,대구 북구,-,아파트

In [30]:
df_csv=pd.read_csv("./data/아파트(매매)_실거래가_20240806113828.csv", header=12)
df_csv

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 영등포구 당산동5가,42,42,0,당산삼성래미안4차,115.7800,202407,31,"139,000",...,4,개인,개인,2003,당산로 214,-,직거래,-,-,아파트
1,2,강원특별자치도 원주시 지정면 가곡리,1512,1512,0,원주롯데캐슬골드파크1차(5단지),84.9644,202407,31,"38,900",...,10,개인,개인,2019,신지정로 250,20240802,중개거래,강원 원주시,-,아파트
2,3,대구광역시 달성군 화원읍 구라리,1650,1650,0,대곡역래미안,84.5958,202407,31,"29,500",...,11,개인,개인,2007,비슬로539길 35,-,중개거래,대구 달성군,-,아파트
3,4,광주광역시 남구 진월동,312-7,312,7,광명,70.6250,202407,31,"16,900",...,1,개인,개인,1998,광복마을길 63,-,중개거래,광주 남구,-,아파트
4,5,광주광역시 남구 진월동,331-93,331,93,중흥,84.8400,202407,31,"17,500",...,13,개인,개인,1992,서문대로749번마길 30,-,직거래,-,24.07.31,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,37576,서울특별시 송파구 장지동,849,849,0,송파파인타운3단지,84.9800,202407,1,"117,500",...,14,개인,개인,2008,충민로 152,-,중개거래,서울 송파구,-,아파트
37576,37577,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,000",...,8,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.10,아파트
37577,37578,광주광역시 광산구 비아동,152-5,152,5,호반,59.8800,202407,1,"15,400",...,5,개인,개인,1998,비아로 185,-,중개거래,광주 광산구,24.07.26,아파트
37578,37579,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,500",...,10,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.19,아파트
37579,37580,대구광역시 북구 읍내동,1366-2,1366,2,칠곡보성,84.9800,202407,1,"21,000",...,9,개인,개인,1992,구암로21길 26,-,중개거래,대구 북구,-,아파트

In [32]:
df_json=pd.read_json("./data/서울특별시_관광지입장정보_2011_2016.json")
df_json

    ForNum  NatNum  addrCd gungu      resNm  rnum   sido  yyyymm
0    44722   75991    1111   종로구        창덕궁     1  서울특별시  201112
1        0   11017    1111   종로구        운현궁     2  서울특별시  201112
2   132399  237330    1111   종로구        경복궁     3  서울특별시  201112
3     3133   21267    1111   종로구        창경궁     4  서울특별시  201112
4    18226   24223    1111   종로구         종묘     5  서울특별시  201112
..     ...     ...     ...   ...        ...   ...    ...     ...
62    5588   44232    1141  서대문구  서대문형무소역사관     8  서울특별시  201512
63       0   22587    1141  서대문구  서대문자연사박물관     9  서울특별시  201512
64   29520    8822    1144   마포구    트릭아이미술관    10  서울특별시  201512
65       3    1647    1165   서초구      헌릉ㆍ인릉    11  서울특별시  201512
66     492   14454    1168   강남구      선릉·정릉    12  서울특별시  201512

[67 rows x 8 columns]

In [35]:
df_html = pd.read_html("./data/corpList.htm")
df_html[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,한국제15호스팩,금융 지원 서비스업,기업인수합병,2024-06-26,12월,유한,NaN,서울특별시
1,에스오에스랩,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",산업용 및 차량용 라이다(LiDAR),2024-06-25,12월,정지성,홈페이지 보기,광주광역시
2,미래에셋비전스팩6호,금융 지원 서비스업,기업인수합병,2024-06-24,12월,정명훈,NaN,서울특별시
3,에이치엠씨제7호스팩,금융 지원 서비스업,기타금융,2024-06-24,12월,강신명,NaN,서울특별시
4,파라다이스,유원지 및 기타 오락관련 서비스업,"카지노, 호텔, 복합리조트",2024-06-24,12월,최종환..,홈페이지 보기,서울특별시
5,한중엔시에스,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업","수냉식 냉각시스템 ESS Parts, 공랭식 ESS Module Parts, EV ...",2024-06-24,12월,김환식,홈페이지 보기,경상북도
6,KB제29호스팩,금융 지원 서비스업,기업인수합병,2024-06-21,12월,서영화,NaN,서울특별시
7,미래에셋비전스팩5호,금융 지원 서비스업,기업인수합병,2024-06-19,12월,김대호,NaN,서울특별시
8,씨어스테크놀로지,의료용 기기 제조업,심전도검사솔루션 입원환자모니터링솔루션,2024-06-19,12월,이영신,홈페이지 보기,경기도
9,한국제14호스팩,금융 지원 서비스업,기업인수합병,2024-06-19,12월,변성환,NaN,서울특별시
10,디비금융스팩12호,기타 금융업,기업인수 및 합병,2024-06-18,12월,김창희,NaN,서울특별시
11,라메디텍,의료용 기기 제조업,초소형 레이저 의료기기 및 미용기기,2024-06-17,12월,최종석,NaN,서울특별시
12,그리드위즈,"그외 기타 전문, 과학 및 기술 서비스업","수요관리 서비스, 전기차 충전기 모뎀 등",2024-06-14,12월,김구환,홈페이지 보기,경기도
13,다원넥스뷰,사진장비 및 광학기기 제조업,LSMB(Laser Micro Bonding System),2024-06-11,12월,남기중,홈페이지 보기,경기도
14,미래에셋비전스팩4호,금융 지원 서비스업,기업인수목적회사(기타금융서비스),2024-05-29,12월,김정수,NaN,서울특별시

## DB에서 자료 읽어오기

In [2]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [3]:
# 외부 db 접속 > kict04
engine=create_engine("mysql+pymysql://root:1234@localhost:3306/exchange_rate")
conn=engine.connect()
data=pd.read_sql('exchange_rate',con=conn)
conn.close()
data

,date,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때_보낼_때,송금_받을_때_받을_때,외화_수표_파실때,매매_기준율,환가_료율,미화_환산율
0,1995-01-03,미국 USD,800.53,1.5,776.87,1.5,791.80,785.60,0.00,788.70,0.00,1.0000
1,1995-01-03,일본 JPY (100),798.89,1.5,775.29,1.5,791.81,782.37,0.00,787.09,0.00,0.9980
2,1995-01-03,유로 EUR,0.00,0.0,0.00,0.0,975.40,959.92,957.94,967.66,7.37,1.2269
3,1995-01-03,중국 CNY,0.00,0.0,0.00,0.0,94.12,0.00,0.00,93.38,1.00,0.1184
4,1995-01-03,홍콩 HKD,103.45,3.0,100.41,3.0,102.74,101.12,0.00,101.93,0.00,0.1292
...,...,...,...,...,...,...,...,...,...,...,...,...
311134,2025-04-15,리비아 LYD,0.00,0.0,0.00,0.0,260.03,254.89,0.00,257.46,0.00,0.1799
311135,2025-04-15,루마니아 RON,0.00,0.0,0.00,0.0,329.91,322.75,0.00,326.33,7.74,0.2280
311136,2025-04-15,미얀마 MMK,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.68,0.00,0.0005
311137,2025-04-15,에티오피아 ETB,0.00,0.0,0.00,0.0,0.00,0.00,0.00,10.81,0.00,0.0076
311138,2025-04-15,우즈베키스탄 UZS,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.11,0.00,0.0001

# 타이타닉 데이터셋으로 pandas 기능 익히기

In [4]:
df = pd.read_csv("./data/Taitanic_train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

* 데이터의 일부만 보기
    * 앞쪽만 head(조회할 행의 갯수), 뒷쪽 tail()
    * 기본 값 = 5

In [40]:
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [41]:
# 데이터 프레임 각 컬럼의 데이터타입
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# .info
* 컬럼명, null이 아닌 데이터 개수, 데이터타입 동시에 출력

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# .describe()
* 데이터 프레임의 숫자 데이터 기초통계를 보여주는 함수
* count, mean, std, min, 25%, 50%, 75%, max

In [44]:
df.describe(include="all") # include=all을 하면 문자 값, 빈도수까지 모두 보여줌.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [ ]:
# 이상치 계측 시 4분위 수 계산 -> 정상 범위 안에 있는지 계산

### 판다스 데이터 프레임에서 일부 자료만 추출하기

In [45]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [46]:
df['Name'] # series로 잘라오기

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [47]:
print(type(df['Name']))

<class 'pandas.core.series.Series'>

* 2개 이상 컬럼 가져오기

In [48]:
df[['Name','Age']] # 컬럼 순서, 갯수 조정 가능

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

* 데이터 프레임의 컬럼 순서 바꾸기

In [49]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [53]:
df2=df[['Survived', 'Pclass', 'Name', 'Sex', 'Age',  'Embarked', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin','PassengerId']]
df2

,Survived,Pclass,Name,Sex,Age,Embarked,SibSp,Parch,Ticket,Fare,Cabin,PassengerId
0,0,3,"Braund, Mr. Owen Harris",male,22.0,S,1,0,A/5 21171,7.2500,NaN,1
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,C,1,0,PC 17599,71.2833,C85,2
2,1,3,"Heikkinen, Miss. Laina",female,26.0,S,0,0,STON/O2. 3101282,7.9250,NaN,3
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,S,1,0,113803,53.1000,C123,4
4,0,3,"Allen, Mr. William Henry",male,35.0,S,0,0,373450,8.0500,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,S,0,0,211536,13.0000,NaN,887
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,S,0,0,112053,30.0000,B42,888
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,S,1,2,W./C. 6607,23.4500,NaN,889
889,1,1,"Behr, Mr. Karl Howell",male,26.0,C,0,0,111369,30.0000,C148,890
890,0,3,"Dooley, Mr. Patrick",male,32.0,Q,0,0,370376,7.7500,NaN,891

# 데이터프레임에서 일부 컬럼만 가져오기2
* loc: 인덱스 이름과 컬럼명으로 데이터 일부를 추출해 가져옴
    * df.loc[시작 row 인덱스: 끝 row 인덱스, ['컬럼명1','컬럼명2']]
* iloc: 인덱스를 이용해 슬라이싱으로 데이터 일부 추출
    * df.iloc[시작row인덱스 : 끝row인덱스, 시작_column_index:끝_column_index]

### loc[시작 row 인덱스: 끝 row 인덱스, ['컬럼명1','컬럼명2']]

In [54]:
df.loc[100:130,['Name','Age']]

                                  Name   Age
100            Petranec, Miss. Matilda  28.0
101   Petroff, Mr. Pastcho ("Pentcho")   NaN
102          White, Mr. Richard Frasar  21.0
103         Johansson, Mr. Gustaf Joel  33.0
104     Gustafsson, Mr. Anders Vilhelm  37.0
105              Mionoff, Mr. Stoytcho  28.0
106   Salkjelsvik, Miss. Anna Kristine  21.0
107             Moss, Mr. Albert Johan   NaN
108                    Rekic, Mr. Tido  38.0
109                Moran, Miss. Bertha   NaN
110     Porter, Mr. Walter Chamberlain  47.0
111               Zabour, Miss. Hileni  14.5
112             Barton, Mr. David John  22.0
113            Jussila, Miss. Katriina  20.0
114              Attalah, Miss. Malake  17.0
115              Pekoniemi, Mr. Edvard  21.0
116               Connors, Mr. Patrick  70.5
117    Turpin, Mr. William John Robert  29.0
118           Baxter, Mr. Quigg Edmond  24.0
119  Andersson, Miss. Ellis Anna Maria   2.0
120        Hickman, Mr. Stanley George  21.0
121         Moore, Mr. Leonard Charles   NaN
122               Nasser, Mr. Nicholas  32.5
123                Webber, Miss. Susan  32.5
124        White, Mr. Percival Wayland  54.0
125       Nicola-Yarred, Master. Elias  12.0
126                McMahon, Mr. Martin   NaN
127          Madsen, Mr. Fridtjof Arne  24.0
128                  Peter, Miss. Anna   NaN
129                 Ekstrom, Mr. Johan  45.0
130               Drazenoic, Mr. Jozef  33.0

In [56]:
df.loc[101,['Age']] #1차원 데이터라 series로 조회됨 => 하나씩 조회해서 값 변경 가능

Age    NaN
Name: 101, dtype: object

In [57]:
df.loc[101,['Age']]=29
df.loc[101,['Age']]

Age    29.0
Name: 101, dtype: object

### df.iloc[시작row인덱스 : 끝row인덱스, 시작_column_index:끝_column_index]

In [63]:
df.iloc[:10,-5:]

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C

In [65]:
df.iloc[4,4]='female'

In [68]:
df.iloc[:5,:5]

,PassengerId,Survived,Pclass,Name,Sex
0,1,0,3,"Braund, Mr. Owen Harris",male
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female
2,3,1,3,"Heikkinen, Miss. Laina",female
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female
4,5,0,3,"Allen, Mr. William Henry",female

In [69]:
df.iloc[:10:2,::2]

   PassengerId  Pclass     Sex  SibSp            Ticket Cabin
0            1       3    male      1         A/5 21171   NaN
2            3       3  female      0  STON/O2. 3101282   NaN
4            5       3  female      0            373450   NaN
6            7       1    male      0             17463   E46
8            9       3  female      0            347742   NaN

* 특정 컬럼에서 유일값(중복되지 않은 고유한 값) 출력하기
* .unique()

In [71]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

* .nunique()
* 유일값의 개수를 출력
* nan값 무시

In [73]:
df['Embarked'].nunique()

3

* 카테고리 컬럼에서 유일값 별 개수를 세는 함수
* value_counts()

In [72]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [76]:
df['Pclass'].value_counts(ascending=True)
# 정렬하기 옵션 가능.

Pclass
2    184
1    216
3    491
Name: count, dtype: int64

In [78]:
df['Pclass'].value_counts(sort=True)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

* 데이터를 정렬하는 함수
* sort_values(by="컬럼명")
* sql - order by와 같은 기능

In [79]:
# 기준 컬럼 2개로 정렬
df.sort_values(by=['Age','Pclass'], ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C
793,794,0,1,"Hoyt, Mr. William Fisher",male,NaN,0,0,PC 17600,30.6958,NaN,C
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C

In [98]:
df = df.set_index("PassengerId")
# 재할당 안하면 원본 바뀌지 않음
# inplace 옵션을 사용해 원본 변경 가능.

* 인덱스를 숫자로 초기화
* reset_index(drop=True)

In [99]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [109]:
df.reset_index(drop=True)
df=df.reset_index()
df

,PassengerId,Surv,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

* 컬럼 이름 출력하기, 바꾸기
* df.colums

In [87]:
df.columns

Index(['index', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

* 컬럼 이름 변경하기
* rename(columns={'원래 이름':'새이름','원래 이름2':'새이름2'}):

In [110]:
df.rename(columns={'PassengerId':'Pid','Survived':'Surv'}, inplace=True)
df

,Pid,Surv,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

* df.columns 로 출력되는 리스트길이와 같은 새로운 이름의 리스트로 덮어쓰기

In [107]:
df. columns

Index(['Surv', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
newName=['승객번호', '생존여부', '선실등급', '이름', '성별', '나이', '형제자매수',
       '부모자식수', '티켓번호', '티켓가격', '선실번호', '목적지']

In [6]:
df.columns=newName
df

,승객번호,생존여부,선실등급,이름,성별,나이,형제자매수,부모자식수,티켓번호,티켓가격,선실번호,목적지
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

* 컬럼 추가하기/삭제하기
* 변수명['컬럼명']=value

In [7]:
df['가족수']=""
#df
# 행렬계산 가능 => 컬럼 값 연산을 통해서 새로운 컬럼 값 생성 가능
df['가족수']=df['형제자매수']+df['부모자식수']
df

,승객번호,생존여부,선실등급,이름,성별,나이,형제자매수,부모자식수,티켓번호,티켓가격,선실번호,목적지,가족수
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

* 컬럼 삭제하기
* del df['컬럼명']
* df.drop('컬럼명',axis=1, inplace=True) 
    * #drop은 행 삭제가 기본이기 때문에 axis 변경 필요

In [9]:
del df['형제자매수']
df

,승객번호,생존여부,선실등급,이름,성별,나이,부모자식수,티켓번호,티켓가격,선실번호,목적지,가족수
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,2,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,370376,7.7500,NaN,Q,0

In [10]:
df.drop('부모자식수',axis=1,inplace=True)

In [11]:
df

,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q,0

In [119]:
df.drop(['이름','승객번호'],axis=1)

     생존여부  선실등급      성별    나이              티켓번호     티켓가격  선실번호 목적지  가족수
0       0     3    male  22.0         A/5 21171   7.2500   NaN   S    1
1       1     1  female  38.0          PC 17599  71.2833   C85   C    1
2       1     3  female  26.0  STON/O2. 3101282   7.9250   NaN   S    0
3       1     1  female  35.0            113803  53.1000  C123   S    1
4       0     3    male  35.0            373450   8.0500   NaN   S    0
..    ...   ...     ...   ...               ...      ...   ...  ..  ...
886     0     2    male  27.0            211536  13.0000   NaN   S    0
887     1     1  female  19.0            112053  30.0000   B42   S    0
888     0     3  female   NaN        W./C. 6607  23.4500   NaN   S    3
889     1     1    male  26.0            111369  30.0000  C148   C    0
890     0     3    male  32.0            370376   7.7500   NaN   Q    0

[891 rows x 9 columns]

# 데이터 타입 바꾸기
* astype(자료형)
* apply(형변환함수)

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    891 non-null    int64
 1   생존여부    891 non-null    int64
 2   선실등급    891 non-null    int64
 3   이름      891 non-null    object
 4   성별      891 non-null    object
 5   나이      714 non-null    float64
 6   티켓번호    891 non-null    object
 7   티켓가격    891 non-null    float64
 8   선실번호    204 non-null    object
 9   목적지     889 non-null    object
 10  가족수     891 non-null    int64
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB

In [13]:
df['승객번호']=df['승객번호'].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    891 non-null    int64
 1   생존여부    891 non-null    int64
 2   선실등급    891 non-null    int64
 3   이름      891 non-null    object
 4   성별      891 non-null    object
 5   나이      714 non-null    float64
 6   티켓번호    891 non-null    object
 7   티켓가격    891 non-null    float64
 8   선실번호    204 non-null    object
 9   목적지     889 non-null    object
 10  가족수     891 non-null    int64
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB

In [128]:
df['승객번호']=df['승객번호'].apply(str)
#apply(lambda x: )사용하여 index 0번부터 함수 돌릴 수 있음
df['승객번호'].apply(lambda x:'짝수' if int(x)%2==0 else '홀수')

0      홀수
1      짝수
2      홀수
3      짝수
4      홀수
       ..
886    홀수
887    짝수
888    홀수
889    짝수
890    홀수
Name: 승객번호, Length: 891, dtype: object

# 판다스 데이터프레임에서 조건에 맞는 행만 가져오기 (데이터 필터링)
* df[df['컬럼명'] 조건식]
* 조건식 연산자 <.<=,>,>=,==,!=,&,|

In [132]:
df[df['승객번호']%2==0]

,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,1
5,6,0,3,"Moran, Mr. James",male,NaN,330877,8.4583,NaN,Q,0
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,349909,21.0750,NaN,S,4
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,237736,30.0708,NaN,C,1
...,...,...,...,...,...,...,...,...,...,...,...
881,882,0,3,"Markun, Mr. Johann",male,33.0,349257,7.8958,NaN,S,0
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,C.A./SOTON 34068,10.5000,NaN,S,0
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,382652,29.1250,NaN,Q,5
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,0

In [133]:
df[df['나이']>35]

,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,17463,51.8625,E46,S,0
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,113783,26.5500,C103,S,0
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,347082,31.2750,NaN,S,6
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,248706,16.0000,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,236852,13.0000,NaN,S,0
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,11751,52.5542,D35,S,2
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,345765,9.0000,NaN,S,0
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,11767,83.1583,C50,C,1
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,382652,29.1250,NaN,Q,5

In [136]:
# 조건 2개 => 각각의 조건을 () 묶어줘야 함.
# 여성이면서 나이가 35세 초과
len(df[(df['성별']=='female')&(df['나이']>35)])

73

* 선실 등급별 승차권 금액의 최소, 최대, 평균 등 4분위 수를 보고싶음

In [16]:
# 선실등급이 1등급인 사람들의 승차권 금액 통계량
df[df['선실등급']==1]['티켓가격'].describe()

count    216.000000
mean      84.154687
std       78.380373
min        0.000000
25%       30.923950
50%       60.287500
75%       93.500000
max      512.329200
Name: 티켓가격, dtype: float64

In [140]:
df['티켓가격'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: 티켓가격, dtype: float64

In [142]:
df[df['티켓가격']>512]

,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
258,259,1,1,"Ward, Miss. Anna",female,35.0,PC 17755,512.3292,NaN,C,0
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,PC 17755,512.3292,B51 B53 B55,C,1
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,PC 17755,512.3292,B101,C,0

In [143]:
df[df['티켓가격']==0]

,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,LINE,0.0,NaN,S,0
263,264,0,1,"Harrison, Mr. William",male,40.0,112059,0.0,B94,S,0
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,LINE,0.0,NaN,S,0
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,239853,0.0,NaN,S,0
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,LINE,0.0,NaN,S,0
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,239853,0.0,NaN,S,0
466,467,0,2,"Campbell, Mr. William",male,NaN,239853,0.0,NaN,S,0
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,239854,0.0,NaN,S,0
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,LINE,0.0,NaN,S,0
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,112052,0.0,NaN,S,0
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,239856,0.0,NaN,S,0
732,733,0,2,"Knight, Mr. Robert J",male,NaN,239855,0.0,NaN,S,0
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,112050,0.0,A36,S,0
815,816,0,1,"Fry, Mr. Richard",male,NaN,112058,0.0,B102,S,0
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,19972,0.0,NaN,S,0

### 조건에 맞는 행을 찾은 후 특정 컬럼만 조회하기

* 선실등급이 1 or 2 이면서 생존한 여성 중 이름 컬럼만 조회하기

In [149]:
df.loc[((df['선실등급']==1) | (df['선실등급']==2))& (df['성별']=='female') & (df['생존여부']==1), '이름']

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
9                    Nasser, Mrs. Nicholas (Adele Achem)
11                              Bonnell, Miss. Elizabeth
15                      Hewlett, Mrs. (Mary D Kingcome)
                             ...
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
874                Abelson, Mrs. Samuel (Hannah Wizosky)
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
880         Shelley, Mrs. William (Imanita Parrish Hall)
887                         Graham, Miss. Margaret Edith
Name: 이름, Length: 161, dtype: object

In [15]:
df[(df.나이<25)&(df.생존여부==1)][['이름','나이']]

                                           이름    나이
9         Nasser, Mrs. Nicholas (Adele Achem)  14.0
10            Sandstrom, Miss. Marguerite Rut   4.0
22                McGowan, Miss. Anna "Annie"  15.0
39                Nicola-Yarred, Miss. Jamila  14.0
43   Laroche, Miss. Simonne Marie Anne Andree   3.0
..                                        ...   ...
855                Aks, Mrs. Sam (Leah Rosen)  18.0
858     Baclini, Mrs. Solomon (Latifa Qurban)  24.0
869           Johnson, Master. Harold Theodor   4.0
875          Najib, Miss. Adele Kiamie "Jane"  15.0
887              Graham, Miss. Margaret Edith  19.0

[118 rows x 2 columns]

In [21]:
df[df['선실등급'].isin([1,2])]

,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,17463,51.8625,E46,S,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,237736,30.0708,NaN,C,1
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,113783,26.5500,C103,S,0
...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,230433,26.0000,NaN,S,1
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,C.A./SOTON 34068,10.5000,NaN,S,0
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,0

# 특정 단어 포함한 행 찾기
* 이름에 Joseph가 들어간 사람 찾기
* like %단어% - SQL
* .str.contains('찾을 단어')

In [152]:
df[df['이름'].str.contains("Joseph")]

,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,239865,26.0000,NaN,S,0
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,PC 17604,82.1708,NaN,C,1
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,374910,8.0500,NaN,S,0
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,2678,15.2458,NaN,C,2
145,146,0,2,"Nicholls, Mr. Joseph Charles",male,19.0,C.A. 33112,36.7500,NaN,S,2
194,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,PC 17610,27.7208,B4,C,0
375,376,1,1,"Meyer, Mrs. Edgar Joseph (Leila Saks)",female,NaN,PC 17604,82.1708,NaN,C,1
454,455,0,3,"Peduzzi, Mr. Joseph",male,NaN,A/5 2817,8.0500,NaN,S,0
532,533,0,3,"Elias, Mr. Joseph Jr",male,17.0,2690,7.2292,NaN,C,2
559,560,1,3,"de Messemaeker, Mrs. Guillaume Joseph (Emma)",female,36.0,345572,17.4000,NaN,S,1
578,579,0,3,"Caram, Mrs. Joseph (Maria Elias)",female,NaN,2689,14.4583,NaN,C,1
589,590,0,3,"Murdlin, Mr. Joseph",male,NaN,A./5. 3235,8.0500,NaN,S,0
608,609,1,2,"Laroche, Mrs. Joseph (Juliette Marie Louise La...",female,22.0,SC/Paris 2123,41.5792,NaN,C,3
685,686,0,2,"Laroche, Mr. Joseph Philippe Lemercier",male,25.0,SC/Paris 2123,41.5792,NaN,C,3
752,753,0,3,"Vande Velde, Mr. Johannes Joseph",male,33.0,345780,9.5000,NaN,S,0
828,829,1,3,"McCormack, Mr. Thomas Joseph",male,NaN,367228,7.7500,NaN,Q,0

In [153]:
df[df['티켓번호'].str.contains("PC")]

,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,PC 17601,27.7208,NaN,C,0
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,PC 17569,146.5208,B78,C,1
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,PC 17604,82.1708,NaN,C,1
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,PC 17572,76.7292,D33,C,1
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,PC 17605,27.7208,NaN,C,0
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,PC 17754,34.6542,A5,C,0
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,PC 17759,63.3583,D10 D12,C,1
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,PC 17558,247.5208,B58 B60,C,1
139,140,0,1,"Giglio, Mr. Victor",male,24.0,PC 17593,79.2000,B86,C,0
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,PC 17597,61.3792,NaN,C,1
168,169,0,1,"Baumann, Mr. John D",male,NaN,PC 17318,25.9250,NaN,S,0
177,178,0,1,"Isham, Miss. Ann Elizabeth",female,50.0,PC 17595,28.7125,C49,C,0
194,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,PC 17610,27.7208,B4,C,0
195,196,1,1,"Lurette, Miss. Elise",female,58.0,PC 17569,146.5208,B80,C,0
256,257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,NaN,PC 17585,79.2000,NaN,C,0
258,259,1,1,"Ward, Miss. Anna",female,35.0,PC 17755,512.3292,NaN,C,0
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,PC 17582,153.4625,C125,S,1
269,270,1,1,"Bissette, Miss. Amelia",female,35.0,PC 17760,135.6333,C99,S,0
273,274,0,1,"Natsch, Mr. Charles H",male,37.0,PC 17596,29.7000,C118,C,1
295,296,0,1,"Lewy, Mr. Ervin G",male,NaN,PC 17612,27.7208,NaN,C,0
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,PC 17558,247.5208,B58 B60,C,1
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.0,PC 17758,108.9000,C65,C,1
309,310,1,1,"Francatelli, Miss. Laura Mabel",female,30.0,PC 17485,56.9292,E36,C,0
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,PC 17608,262.3750,B57 B59 B63 B66,C,4
325,326,1,1,"Young, Miss. Marie Grice",female,36.0,PC 17760,135.6333,C32,C,0
332,333,0,1,"Graham, Mr. George Edward",male,38.0,PC 17582,153.4625,C91,S,1
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,PC 17611,133.6500,NaN,S,1
369,370,1,1,"Aubart, Mme. Leontine Pauline",female,24.0,PC 17477,69.3000,B35,C,0
373,374,0,1,"Ringhini, Mr. Sante",male,22.0,PC 17760,135.6333,NaN,C,0
375,376,1,1,"Meyer, Mrs. Edgar Joseph (Leila Saks)",female,NaN,PC 17604,82.1708,NaN,C,1
380,381,1,1,"Bidois, Miss. Rosalie",female,42.0,PC 17757,227.5250,NaN,C,0
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,PC 17609,49.5042,NaN,C,0
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.0,PC 17758,108.9000,C65,C,1
512,513,1,1,"McGough, Mr. James Robert",male,36.0,PC 17473,26.2875,E25,S,0
513,514,1,1,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",female,54.0,PC 17603,59.4000,NaN,C,1
527,528,0,1,"Farthing, Mr. John",male,NaN,PC 17483,221.7792,C95,S,0
537,538,1,1,"LeRoy, Miss. Bertha",female,30.0,PC 17761,106.4250,NaN,C,0
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.0,PC 17761,106.4250,C86,C,1
557,558,0,1,"Robbins, Mr. Victor",male,NaN,PC 17757,227.5250,NaN,C,0
572,573,1,1,"Flynn, Mr. John Irwin (""Irving"")",male,36.0,PC 17474,26.3875,E25,S,0
599,600,1,1,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",male,49.0,PC 17485,56.9292,A20,C,1
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.0,PC 17582,153.4625,C125,S,0
641,642,1,1,"Sagesser, Mlle. Emma",female,24.0,PC 17477,69.3000,B35,C,0
645,646,1,1,"Harper, Mr. Henry Sleeper",male,48.0,PC 17572,76.7292,D33,C,1
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.0,PC 17611,133.6500,NaN,S,2
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,PC 17755,512.3292,B51 B53 B55,C,1
681,682,1,1,"Hassab, Mr. Hammad",male,27.0,PC 17572,76.7292,D49,C,0
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,PC 17757,227.5250,C62 C64,C,1
701,702,1,1,"Silverthorne, Mr. Spencer Victor",male,35.0,PC 17475,26.2875,E24,S,0
707,708,1,1,"Calderhead, Mr. Edward Pennington",male,42.0,PC 17476,26.2875,E24,S,0
710,711,1,1,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",female,24.0,PC 17482,49.5042,C90,C,0
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.0,PC 17757,227.5250,C45,C,0
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,PC 17755,512.3292,B101,C,0
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,PC 17608,262.3750,B57 B59 B63 B66,C,4
789,790,0,1,"Guggenheim, Mr. Benjamin",male,46.0,PC 17593,79.2000,B82 B84,C,0
793,794,0,1,"Hoyt, Mr. William Fisher",male,NaN,PC 17600,30.6958,NaN,C,0
835,836,1,1,"Compton, Miss. Sara Rebecca",female,39.0,PC 17756,83.1583,E49,C,2
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,PC 17592,39.4000,D28,S,1
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,PC 17590,50.4958,A24,S,0

* 승객 이름에 ()를 없애는 경우

In [22]:
result=[]
for name in df['이름']:
    result.append(name.replace("(","").replace(")",""))
result
df['이름']=result

In [23]:
df

,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley Florence Briggs Thayer",female,38.0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath Lily May Peel",female,35.0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q,0

In [24]:
df = pd.read_csv("./data/Taitanic_train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [25]:
# apply와 lambda 함수 이용해 작업하기
df['Name'].apply(lambda name:name.replace("(","").replace(")",""))

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley Florence Briggs Thayer
2                                 Heikkinen, Miss. Laina
3             Futrelle, Mrs. Jacques Heath Lily May Peel
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [29]:
df['Name']=df['Name'].apply(lambda x:x.split(','))
df['first_name']=df['Name'].apply(lambda x:x[0])
df['second_name']=df['Name'].apply(lambda x:x[1])

In [30]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name,second_name
0,1,0,3,"[Braund, Mr. Owen Harris]",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris
1,2,1,1,"[Cumings, Mrs. John Bradley (Florence Briggs ...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
2,3,1,3,"[Heikkinen, Miss. Laina]",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina
3,4,1,1,"[Futrelle, Mrs. Jacques Heath (Lily May Peel)]",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel)
4,5,0,3,"[Allen, Mr. William Henry]",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"[Montvila, Rev. Juozas]",male,27.0,0,0,211536,13.0000,NaN,S,Montvila,Rev. Juozas
887,888,1,1,"[Graham, Miss. Margaret Edith]",female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss. Margaret Edith
888,889,0,3,"[Johnston, Miss. Catherine Helen ""Carrie""]",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Johnston,"Miss. Catherine Helen ""Carrie"""
889,890,1,1,"[Behr, Mr. Karl Howell]",male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr. Karl Howell
890,891,0,3,"[Dooley, Mr. Patrick]",male,32.0,0,0,370376,7.7500,NaN,Q,Dooley,Mr. Patrick

# groupby
* 특정 기준 컬럼 지정해서 다른 컬럼 통계량(평균, 최소, 최대)
* df[['보고싶은 컬럼1','보고싶은 컬럼2']].groupby('기준컬럼').집합함수(mean,max,min,median,count)

* 성별별 생존자 수

In [32]:
survbysex=df[['Sex','Survived']].groupby('Sex').value_counts(sort=False)
survbysex

Sex     Survived
female  0            81
        1           233
male    0           468
        1           109
Name: count, dtype: int64

In [33]:
print(type(survbysex))

<class 'pandas.core.series.Series'>

In [34]:
survbysex.index

MultiIndex([('female', 0),
            ('female', 1),
            (  'male', 0),
            (  'male', 1)],
           names=['Sex', 'Survived'])

In [35]:
df3 = pd.DataFrame(survbysex)
df3

                 count
Sex    Survived
female 0            81
       1           233
male   0           468
       1           109

In [37]:
#여성 생존자 생존율
233/(81+233) * 100

74.20382165605095

* 선실 등급별 생존자 수

In [39]:
df[['Pclass','Survived']].groupby('Pclass').value_counts(sort=False)

Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

* 성별별, 선실등급별 생존자 수

In [41]:
df[['Sex','Pclass','Survived']].groupby(['Pclass','Sex']).value_counts(sort=False)

Pclass  Sex     Survived
1       female  0             3
                1            91
        male    0            77
                1            45
2       female  0             6
                1            70
        male    0            91
                1            17
3       female  0            72
                1            72
        male    0           300
                1            47
Name: count, dtype: int64

은행 고객 등급
- 급여 통장 입금여부, 액수
- 적금, 예금

* 성별에 따른 나이의 평균, 최소, 최대값

In [42]:
df[['Sex','Age']].groupby('Sex').mean()

              Age
Sex
female  27.915709
male    30.726645

In [43]:
df[['Sex','Age']].groupby('Sex').describe()

          Age
        count       mean        std   min   25%   50%   75%   max
Sex
female  261.0  27.915709  14.110146  0.75  18.0  27.0  37.0  63.0
male    453.0  30.726645  14.678201  0.42  21.0  29.0  39.0  80.0

In [46]:
df[['Sex','Age']].groupby('Sex').agg(['min','max','mean'])

         Age
         min   max       mean
Sex
female  0.75  63.0  27.915709
male    0.42  80.0  30.726645

### 피벗테이블 pivot

In [48]:
df.pivot_table(values="Survived",index='Sex',columns='Pclass')

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [51]:
#결측값 퍼센티지 구하기
# 결측치가 40% 이상이면 측정 제외하는 것이 좋음
df.isna().sum()/len(df)*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
first_name      0.000000
second_name     0.000000
dtype: float64

* dropna() 결측값이 있는 행 삭제

In [52]:
df.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name,second_name
1,2,1,1,"[Cumings, Mrs. John Bradley (Florence Briggs ...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
3,4,1,1,"[Futrelle, Mrs. Jacques Heath (Lily May Peel)]",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel)
6,7,0,1,"[McCarthy, Mr. Timothy J]",male,54.0,0,0,17463,51.8625,E46,S,McCarthy,Mr. Timothy J
10,11,1,3,"[Sandstrom, Miss. Marguerite Rut]",female,4.0,1,1,PP 9549,16.7000,G6,S,Sandstrom,Miss. Marguerite Rut
11,12,1,1,"[Bonnell, Miss. Elizabeth]",female,58.0,0,0,113783,26.5500,C103,S,Bonnell,Miss. Elizabeth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"[Beckwith, Mrs. Richard Leonard (Sallie Monyp...",female,47.0,1,1,11751,52.5542,D35,S,Beckwith,Mrs. Richard Leonard (Sallie Monypeny)
872,873,0,1,"[Carlsson, Mr. Frans Olof]",male,33.0,0,0,695,5.0000,B51 B53 B55,S,Carlsson,Mr. Frans Olof
879,880,1,1,"[Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)]",female,56.0,0,1,11767,83.1583,C50,C,Potter,Mrs. Thomas Jr (Lily Alexenia Wilson)
887,888,1,1,"[Graham, Miss. Margaret Edith]",female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss. Margaret Edith
889,890,1,1,"[Behr, Mr. Karl Howell]",male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr. Karl Howell

* fillna() 결측 값을 다른 값으로 채워주는 함수

In [54]:
df['Age']=df['Age'].fillna(round(df['Age'].mean()))

In [55]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
first_name       0
second_name      0
dtype: int64

# 여러 개의 데이터프레임 합치기
* concat
* merge : sql join과 같은 역할. 공통된 기준 컬럼 매칭해서 합침
* join : sql join과 같은 역할 index가 같은 것 끼리 합침

In [56]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [58]:
engine = create_engine("mysql+pymysql://kict04:kict04@221.155.18.165:3306/titanic")
conn=engine.connect()

In [59]:
passenger = pd.read_sql("p_info", con=conn)
ticket = pd.read_sql("t_info", con=conn)
survived = pd.read_sql("survived", con=conn)
conn.close()

In [66]:
survived.head(1)

   PassengerId  Survived
0            1         0

# concat axis=0 행추가, axis =1 열 추가

In [68]:
df1 = pd.concat([passenger, ticket, survived],axis=1)
df1

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,1,A/5 21171,3,7.2500,None,S,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,2,PC 17599,1,71.2833,C85,C,2,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,3,STON/O2. 3101282,3,7.9250,None,S,3,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,4,113803,1,53.1000,C123,S,4,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,5,373450,3,8.0500,None,S,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,887,211536,2,13.0000,None,S,887,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,888,112053,1,30.0000,B42,S,888,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,889,W./C. 6607,3,23.4500,None,S,889,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,890,111369,1,30.0000,C148,C,890,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,891,370376,3,7.7500,None,Q,891,0

In [69]:
print('passenger',passenger.shape)
print('ticket',ticket.shape)
print('survived',survived.shape)

passenger (891, 6)
ticket (891, 6)
survived (891, 2)

In [70]:
passenger.head(1)

   PassengerId                     Name   Sex   Age  SibSp  Parch
0            1  Braund, Mr. Owen Harris  male  22.0      1      0

In [74]:
# select * from passenger left join ticket on passenger.PassengerId = ticket.PassengerId
joined_df=pd.merge(passenger,ticket, how="inner", on="PassengerId")
joined_df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q

In [75]:
joined_df=pd.merge(joined_df, survived, how='inner', on="PassengerId")

In [76]:
joined_df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0

# join : sql의 join과 동일. 기준 컬럼명 기준으로 합침

In [80]:
passenger=passenger.set_index("PassengerId")

KeyError: "None of ['PassengerId'] are in the columns"

In [81]:
ticket=ticket.set_index("PassengerId")

In [83]:
joined_df2=passenger.join(ticket)
joined_df2

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S
...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S
888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S
890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C
891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q

In [86]:
survived = survived.set_index("PassengerId")

In [87]:
joined_df2.join(survived)

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0
888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0
890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1
891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0

In [88]:
joined_df2=joined_df2.reset_index()
joined_df2

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q

# 중복여부 확인 및 제거하기

In [103]:
toss=pd.read_csv("./data/viva_republica_toss.csv", index_col=0)
toss.head(1)

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,2,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."

In [90]:
toss.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52565 entries, 0 to 52564
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용자     52531 non-null  object
 1   별점      52565 non-null  int64
 2   리뷰      52565 non-null  object
 3   날짜      52565 non-null  object
 4   개발자 응답  49611 non-null  object
dtypes: int64(1), object(4)
memory usage: 2.4+ MB

In [104]:
toss.duplicated().sum()

np.int64(52052)

* 중복 컬럼 삭제하기 drop_duplicates()

In [105]:
toss= toss.drop_duplicates()

In [106]:
toss = toss.reset_index(drop=True)
toss

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,2,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
1,최유연,1,"증권부분이 너무 빈약해요. 이평선, 분봉, 틱봉 자유롭게 수치를 설정할 수 있었음 ...",2025년 1월 18일,"안녕하세요. 최유연 님, 토스팀입니다. 토스증권 사용하시면서 주신 소중한 의견 너무..."
2,EXPRESS,1,주식 UI에서 홈과 관심 종목을 나눈 것도 불편한데 이번 자주 사용하는 계좌 업데이...,2025년 2월 25일,"안녕하세요. EXPRESS 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄..."
3,JS P,1,언제 한 번 대대적으로 앱 퍼포먼스 최적화를 했으면 좋겠습니다. 예전엔 이러지 않았...,2025년 2월 28일,"안녕하세요. JS P 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였..."
4,AndPeter,1,앱 최적화 좀 해주세요! 무슨 메모리를 1GB나 잡아먹고 패킷전송이 하루에 80만건...,2025년 3월 1일,"안녕하세요. AndPeter 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
...,...,...,...,...,...
508,나명자,5,사용은 편해요. 계좌개설 확인증이나 송금확인증 의 글씨가 좀 더 컸으면 좋겠습니다....,2024년 10월 31일,"안녕하세요. 나명자 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주..."
509,김주영,4,소비 관리하는 데 아주 유용하게 쓰고 있습니다. ktx 예매 때문에 코레일을 이용했...,2024년 11월 30일,"안녕하세요. 김주영님, 토스팀입니다. 우선, 토스 이용에 불편을 드려 죄송합니다. ..."
510,bk im,1,편리함은 사라지고 불편함만 가중되고있음. 1. 동영상 광고 도입으로 토스 켤 때 마...,2023년 7월 25일,"안녕하세요. bk im님, 토스 고객센터입니다. 우선 많이 불편하셨음에도 시간내어 ..."
511,임혜란,2,토스 편해서 사용했는데..최근에 토스에서 하는 꽃돼지이벤트 하다가 짜증났어요. 완전...,2025년 2월 27일,"안녕하세요. 임혜란님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나..."
512,60 2,3,왜 알람이 안 울릴까요? 입출금 알람 설정해뒀는데 어느 순간부터 안 울리네요 그렇다...,2024년 11월 27일,"안녕하세요. 고객 님, 토스팀입니다. 이용에 불편을 드린 것 같아 마음이 무겁습니다..."