공공데이터 포털
https://www.data.go.kr/data/15012005/openapi.do
* 데이터 포맷 확인
* 신청가능 트래픽
* 상세기능 - API 목록 - OpenAPI 실행준비 - 인증키, 필요한 코드 삽입
* 활용정보가이드에서 필요한 코드 등 확인 가능

In [4]:
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=11&indsSclsCd=I21006&numOfRows=1000&pageNo=1&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj/eEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai+Nt11O7Bupwnz7usNQ==

SyntaxError: invalid syntax (2847937349.py, line 1)

In [2]:
import requests
import json
import pandas as pd

In [3]:
serviceKey='bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj/eEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai+Nt11O7Bupwnz7usNQ=='

In [50]:
for key in [11,26,27,28,29,30,31,36,41,42,43,44,45,46,47,48,50]:
    print(key)

11
26
27
28
29
30
31
36
41
42
43
44
45
46
47
48
50

In [52]:
store_data={}
for k in [11,26,27,28,29,30,31,36,41,42,43,44,45,46,47,48,50]:
    n=1
    while True:
        url="http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?"
        payload=dict(divId="ctprvnCd",key=k,indsSclsCd='I21006',pageNo=n,numOfRows=1000,type='json',serviceKey=serviceKey)
        r=requests.get(url,params=payload)
        print(r.url)
        print(r.status_code)
        r=r.json()
        #print(n,':',len(r['body']['items']))
        items=r['body']['items']
        for item in items:
            for key, value in item.items():
                store_data.setdefault(key,[]).append(value)
        if len(r['body']['items'])>0:
            n+=1
        else:
            break
        
s_df=pd.DataFrame(store_data)
s_df

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=11&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=11&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=11&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=11&indsSclsCd=I21006&pageNo=4&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=11&indsSclsCd=I21006&pageNo=5&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=11&indsSclsCd=I21006&pageNo=6&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=11&indsSclsCd=I21006&pageNo=7&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=26&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=26&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=26&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=26&indsSclsCd=I21006&pageNo=4&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=27&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=27&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=27&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=27&indsSclsCd=I21006&pageNo=4&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=28&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=28&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=28&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=28&indsSclsCd=I21006&pageNo=4&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=29&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=29&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=29&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=30&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=30&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=30&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=31&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=31&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=31&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=36&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=36&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=4&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=5&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=6&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=7&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=8&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=9&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=10&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=41&indsSclsCd=I21006&pageNo=11&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=42&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=43&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=43&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=43&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=44&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=44&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=44&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=44&indsSclsCd=I21006&pageNo=4&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=45&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=46&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=46&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=46&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=47&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=47&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=47&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=47&indsSclsCd=I21006&pageNo=4&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=48&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=48&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=48&indsSclsCd=I21006&pageNo=3&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=48&indsSclsCd=I21006&pageNo=4&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=48&indsSclsCd=I21006&pageNo=5&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=50&indsSclsCd=I21006&pageNo=1&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200
http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInDong?divId=ctprvnCd&key=50&indsSclsCd=I21006&pageNo=2&numOfRows=1000&type=json&serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D
200

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,MA010120220800445252,가마로닭강정,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1159010500102240001017670,제,서울특별시 동작구 서달로 151,156861,06973,,1,,126.961535,37.506975
1,MA010120220800445378,수원왕갈비통닭,보라매점,I2,음식,I210,기타 간이,I21006,치킨,I56213,...,1159010800104150005004103,,서울특별시 동작구 여의대방로24가길 12,156811,07055,,1,,126.921008,37.498774
2,MA010120220800430361,페리카나,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1159010700102130007006364,,서울특별시 동작구 사당로 168,156879,07030,,,,126.967572,37.486813
3,MA010120220800445715,치킨89,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1159010900103460008001825,노블레스빌,서울특별시 동작구 보라매로 98-5,156847,07053,,,,126.928484,37.497932
4,MA010120220800439275,또바기치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1156013200103470294013808,,서울특별시 영등포구 가마산로 439,150848,07382,,,,126.905292,37.505322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38668,MA0106202410A2287965,네네치킨도남점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,5011010400110670000042703,,제주특별자치도 제주시 오복4길 6,690825,63223,,,,126.536263,33.495549
38669,MA0106202411A2022213,고고치킨앤피자,,I2,음식,I210,기타 간이,I21006,치킨,I56123,...,5011011300116580005000004,,제주특별자치도 제주시 선사로6길 10,690071,63318,,1,,126.587208,33.524453
38670,MA0106202409A2090862,굽네치킨용담점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,5011010800103120003018322,,제주특별자치도 제주시 용담로 107,690819,63153,,1,,126.513815,33.511168
38671,MA0106202405A0669657,강성통닭제주,본점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,5011010400104420001044835,,제주특별자치도 제주시 연신로 28,690824,63226,,1,,126.545137,33.498394
38672,MA0106202405A0698845,오태식해바라기치킨,영어교육도시점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,5013025029124760013000001,,제주특별자치도 서귀포시 대정읍 글로벌에듀로 382,699931,63644,,,,126.276988,33.280359

In [48]:
r

{'header': {'resultCode': '10',
  'resultMsg': 'INVALID_REQUEST_PARAMETER_ERROR'},
 'body': {}}

In [45]:
sample={}
for item in r['body']['items']:
    for key, value in item.items():
        sample.setdefault(key,[]).append(value)
s_df=pd.DataFrame(sample)
s_df

KeyError: 'items'

In [53]:
#전체 컬럼명 변경
for i in range(len(r['header']['columns'])):
    new_df=s_df.rename(columns={s_df.columns[i]:r['header']['columns'][i]},inplace=True)
s_df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220800445252,가마로닭강정,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1159010500102240001017670,제,서울특별시 동작구 서달로 151,156861,06973,,1,,126.961535,37.506975
1,MA010120220800445378,수원왕갈비통닭,보라매점,I2,음식,I210,기타 간이,I21006,치킨,I56213,...,1159010800104150005004103,,서울특별시 동작구 여의대방로24가길 12,156811,07055,,1,,126.921008,37.498774
2,MA010120220800430361,페리카나,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1159010700102130007006364,,서울특별시 동작구 사당로 168,156879,07030,,,,126.967572,37.486813
3,MA010120220800445715,치킨89,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1159010900103460008001825,노블레스빌,서울특별시 동작구 보라매로 98-5,156847,07053,,,,126.928484,37.497932
4,MA010120220800439275,또바기치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1156013200103470294013808,,서울특별시 영등포구 가마산로 439,150848,07382,,,,126.905292,37.505322
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38668,MA0106202410A2287965,네네치킨도남점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,5011010400110670000042703,,제주특별자치도 제주시 오복4길 6,690825,63223,,,,126.536263,33.495549
38669,MA0106202411A2022213,고고치킨앤피자,,I2,음식,I210,기타 간이,I21006,치킨,I56123,...,5011011300116580005000004,,제주특별자치도 제주시 선사로6길 10,690071,63318,,1,,126.587208,33.524453
38670,MA0106202409A2090862,굽네치킨용담점,,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,5011010800103120003018322,,제주특별자치도 제주시 용담로 107,690819,63153,,1,,126.513815,33.511168
38671,MA0106202405A0669657,강성통닭제주,본점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,5011010400104420001044835,,제주특별자치도 제주시 연신로 28,690824,63226,,1,,126.545137,33.498394
38672,MA0106202405A0698845,오태식해바라기치킨,영어교육도시점,I2,음식,I210,기타 간이,I21006,치킨,I56111,...,5013025029124760013000001,,제주특별자치도 서귀포시 대정읍 글로벌에듀로 382,699931,63644,,,,126.276988,33.280359

## sample

In [4]:
def unpack_data(response):
    result={}
    for item in response['body']['items']:
        for key, value in zip(response['header']['columns'],item.values()):
            result.setdefault(key,[]).append(value)
    df2=pd.DataFrame(result)
    return df2

In [5]:
#페이지 수 계산
response['body']['totalCount'] // 1000 +1

NameError: name 'response' is not defined

In [6]:
page=1 
result_dfs=[]
while True:
    url="http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
    payload=dict(divId="indsSclsCd",key='I21006',pageNo=page,numOfRows=1000,type='json',serviceKey=serviceKey)
    r=requests.get(url,params=payload)
    #print(r.url)
    #print(r.status_code)
    response=r.json()
    total_page=response['body']['totalCount'] // 1000 +1
    print(f'{page}/{total_page} 탐색 중입니다. 코드:{r.status_code}',end = "\r")
    result_dfs.append(unpack_data(response))
    if page < total_page:
        page+=1
    else: break
    #print(total_page)
result=pd.concat(result_dfs)
result

KeyboardInterrupt:

In [81]:
result=result.reset_index(drop=True)
result.to_csv('공공데이터_상권정보_202504.csv',encoding="utf-8",index=False)

### pandas로 데이터 불러오기

In [82]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [7]:
ori_data=pd.read_excel("./data/소상공인시장진흥공단_상가(상권)정보_업종분류(2302)_및_연계표_v1.0.xlsx", engine='openpyxl',header=[1])
ori_data

    대분류코드          대분류명 중분류코드              중분류명   소분류코드            소분류명
0      G2           소매업  G202  자동차 부품 및 내장품 소매업  G20201         타이어 소매업
1      G2           소매업  G202  자동차 부품 및 내장품 소매업  G20202      자동차 부품 소매업
2      G2           소매업  G203    모터사이클 및 부품 소매업  G20301  모터사이클 및 부품 소매업
3      G2           소매업  G204            종합 소매업  G20404            슈퍼마켓
4      G2           소매업  G204            종합 소매업  G20405             편의점
..    ...           ...   ...               ...     ...             ...
242    S2  수리 및 개인 서비스업  S209               세탁업  S20902          셀프 빨래방
243    S2  수리 및 개인 서비스업  S210    장례식장 및 관련 서비스업  S21001            장례식장
244    S2  수리 및 개인 서비스업  S210    장례식장 및 관련 서비스업  S21002      화장터/묘지/납골당
245    S2  수리 및 개인 서비스업  S211          기타 개인서비스  S21101            예식장업
246    S2  수리 및 개인 서비스업  S211          기타 개인서비스  S21105      결혼 상담 서비스업

[247 rows x 6 columns]

In [87]:
ori_data['소분류코드']

0      G20201
1      G20202
2      G20301
3      G20404
4      G20405
        ...
242    S20902
243    S21001
244    S21002
245    S21101
246    S21105
Name: 소분류코드, Length: 247, dtype: object

In [8]:
import os

In [9]:
errors=[]
for code, name in zip(ori_data['소분류코드'],ori_data['소분류명']):
    name=name.replace("/","_").replace(".","_")
    page=1 
    result_dfs=[]
    while True:
        url="http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
        payload=dict(divId="indsSclsCd",key=code,pageNo=page,numOfRows=1000,type='json',serviceKey=serviceKey)
        r=requests.get(url,params=payload)
        #print(r.url)
        #print(r.status_code)
        response=r.json()
        try:
            total_page=response['body']['totalCount'] // 1000 +1
        except Exception as e:
            print('데이터 없음', end="\r")
            errors.append(f"{idx},{code},{name} 데이터 없음")
            break
        print(f'{page}/{total_page} 탐색 중입니다. 코드:{r.status_code}',end = "\r")
        result_dfs.append(unpack_data(response))
        if page < total_page:
            page+=1
        else: break
        #print(total_page)
    result=pd.concat(result_dfs)
    result=result.reset_index(drop=True)
    
    if not os.path.exists("./scraping_results"):
        os.mkdir("./scraping_results")
    #else:
        #print('scraping_results가 이미 있습니다.')
    
    result.to_csv(f'./scraping_results//공공데이터_상권정보_{name}_202504.csv',encoding="utf-8",index=False)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)