# XML : html처럼 태그 기반으로 자료를 저장한 포맷
* xml parser를 통해 str을 xml로 변환화는 작업 필요
* xml로 변환이 되면 태그 기반으로 자료를 찾아 정리
* 태그에서 자료를 추출할 때는 beautifulsoup이라는 라이브러리를 이용

In [1]:
import json
import pandas as pd
import os
import requests

In [2]:
serviceKey='bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj/eEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai+Nt11O7Bupwnz7usNQ=='

In [3]:
data={}
url = 'http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list'
params ={'serviceKey' : serviceKey, 'pageNo' : 1, 'numOfRows' : 100, 'dataType' : 'json','bssYmdStart':'20190101'}
response = requests.get(url, params=params)
print(response.url)
print(response.status_code)
r=response.json()
for i in r['body']['items']:
    for key, value in i.items():
        data.setdefault(key,[]).append(value)
df=pd.DataFrame(data)
df

http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&pageNo=1&numOfRows=100&dataType=json&bssYmdStart=20190101
200

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
10,20250310,3.74,0,0,0,0,0,0,0,20250316,토스뱅크,1661-7654
11,20250310,3.7,0,0,0,0,0,0,0,20250316,케이뱅크,1522-1000
12,20250310,3.89,0,0,0,0,0,0,0,20250316,국민은행,1644-9999
13,20250310,3.84,0,0,0,0,0,0,0,20250316,부산은행,1588-6200
14,20250310,4.05,0,0,0,0,0,0,0,20250316,농협은행,1588-2100
15,20250310,4.0,0,0,0,0,0,0,0,20250316,기업은행,1566-2566
16,20250310,4.11,0,0,0,0,0,0,0,20250316,광주은행,1600-4000
17,20250310,4.07,0,0,0,0,0,0,0,20250316,신한은행,1599-8000

# xml로 가져오기
* xml로 데이터를 받으면 처음에는 단순 문자열로 받게 된다.
* 문자열을 xml로 바꿔줘야 함
* beautifulsoup을 이용해 변환
* beautifulsoup의 메서드인 select, select_one을 이용해 css 셀렉터 기반으로 데이터가 위치한 태그를 찾아서 내용 추출

In [75]:
url = 'http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list'
params ={'serviceKey' : serviceKey, 'pageNo' : 1, 'numOfRows' : 100, 'dataType' : 'xml','bssYmdStart':'20190101'}
response = requests.get(url, params=params)
print(response.url)
print(response.status_code)
r=response.text
r

http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&pageNo=1&numOfRows=100&dataType=xml&bssYmdStart=20190101
200

'<response><header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header><body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>100</numOfRows><items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.74</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.7</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>케이뱅크</organId><callCenter>1522-1000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>국민은행</organId><callCenter>1644-9999</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.84</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>부산은행</organId><callCenter>1588-6200</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.05</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>농협은행</organId><callCenter>1588-2100</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>기업은행</organId><callCenter>1566-2566</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.11</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.07</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>신한은행</organId><callCenter>1599-8000</callCenter></item></items></body></response>'

# BeautifulSoup
* https://www.crummy.com/software/BeautifulSoup/bs4/doc/ 참고
* pip install beautifulsoup4
* from bs4 import BeautifulSoup as bs
* find, find_all 함수: xml, html에서 태그 기반으로 내용 찾음
* select, select_one 함수 : xml이나 html에서 css selector 기반으로 내용 찾음
* find_all, select는 해당 태그나 css select를 가진 부분을 모두 찾아서 list로 반환
* find_all, select는 여러 태그나 css select 중에서 가장 먼저 나오는 태그/selector를 한개만 찾아줌
* 찾아온 태그.name : 태그 이름 반환
* 찾아온 태그.text, .string: 태그 안쪽 텍스트 반환

In [49]:
from bs4 import BeautifulSoup as bs

In [76]:
soup = bs(r, 'xml')
soup

<?xml version="1.0" encoding="utf-8"?>
<response><header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header><body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>100</numOfRows><items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.74</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.7</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>케이뱅크</organId><callCenter>1522-1000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>국민은행</organId><callCenter>1644-9999</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.84</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>부산은행</organId><callCenter>1588-6200</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.05</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>농협은행</organId><callCenter>1588-2100</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>기업은행</organId><callCenter>1566-2566</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.11</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.07</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>신한은행</organId><callCenter>1599-8000</callCenter></item></items></body></response>

In [52]:
soup.select_one("resultCode")

In [53]:
items=soup.select_one('items')
item = items.select('item')

In [54]:
for item_value in item:
    print(item_value)
    for tag in item_value:
        print(tag.text)
        print()

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item>
20250310

0

0

0

0

0

0

0

0

20250316

산업은행

1588-1500

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item>
20250310

0

0

0

0

0

0

0

0

20250316

제주은행

1588-0079

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item>
20250310

0

0

0

0

0

0

0

0

20250316

SC은행

1588-1599

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item>
20250310

4.89

0

0

0

0

0

0

0

20250316

전북은행

1588-4477

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item>
20250310

0

0

0

0

0

0

0

0

20250316

수협은행

1588-1515

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item>
20250310

4.26

0

0

0

0

0

0

0

20250316

우리은행

1599-5000

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item>
20250310

4.64

0

0

0

0

0

0

0

20250316

경남은행

1588-8585

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item>
20250310

3.5

0

0

0

0

0

0

0

20250316

카카오뱅크

1599-3333

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item>
20250310

3.38

0

0

0

0

0

0

0

20250316

아이엠뱅크

1588-5050

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item>
20250310

4.18

0

0

0

0

0

0

0

20250316

하나은행

1599-1111

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.74</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item>
20250310

3.74

0

0

0

0

0

0

0

20250316

토스뱅크

1661-7654

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.7</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>케이뱅크</organId><callCenter>1522-1000</callCenter></item>
20250310

3.7

0

0

0

0

0

0

0

20250316

케이뱅크

1522-1000

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>국민은행</organId><callCenter>1644-9999</callCenter></item>
20250310

3.89

0

0

0

0

0

0

0

20250316

국민은행

1644-9999

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.84</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>부산은행</organId><callCenter>1588-6200</callCenter></item>
20250310

3.84

0

0

0

0

0

0

0

20250316

부산은행

1588-6200

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.05</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>농협은행</organId><callCenter>1588-2100</callCenter></item>
20250310

4.05

0

0

0

0

0

0

0

20250316

농협은행

1588-2100

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>기업은행</organId><callCenter>1566-2566</callCenter></item>
20250310

4.0

0

0

0

0

0

0

0

20250316

기업은행

1566-2566

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.11</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item>
20250310

4.11

0

0

0

0

0

0

0

20250316

광주은행

1600-4000

<item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.07</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>신한은행</organId><callCenter>1599-8000</callCenter></item>
20250310

4.07

0

0

0

0

0

0

0

20250316

신한은행

1599-8000

In [55]:
items=soup.select_one('items')
bssYmdStart_list=items.select("bssYmdStart")
interest4_1_list=items.select("interest4_1")
interest3_2_list=items.select("interest3_2")
interest4_2_list=items.select("interest4_2")
interest2_1_list=items.select("interest2_1")
interest1_2_list=items.select("interest1_2")
interest3_1_list=items.select("interest3_1")
interest2_2_list=items.select("interest2_2")
interest1_1_list=items.select("interest1_1")
bssYmdEnd_list=items.select("bssYmdEnd")
organId_list=items.select("organId")
callCenter_list=items.select("callCenter")

In [56]:
tag_list=[bssYmdStart_list,interest4_1_list,interest3_2_list,interest4_2_list,interest2_1_list,interest1_2_list,interest3_1_list,interest2_2_list,interest1_1_list,bssYmdEnd_list,organId_list,callCenter_list]

In [59]:
result={}
for tag in tag_list:
    for item in tag:
        result.setdefault(item.name, []).append(item.text)
result

{'bssYmdStart': ['20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310'],
 'interest4_1': ['0',
  '0',
  '0',
  '4.89',
  '0',
  '4.26',
  '4.64',
  '3.5',
  '3.38',
  '4.18',
  '3.74',
  '3.7',
  '3.89',
  '3.84',
  '4.05',
  '4.0',
  '4.11',
  '4.07'],
 'interest3_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest4_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest2_1': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest1_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest3_1': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest2_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest1_1': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'bssYmdEnd': ['20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316'],
 'organId': ['산업은행',
  '제주은행',
  'SC은행',
  '전북은행',
  '수협은행',
  '우리은행',
  '경남은행',
  '카카오뱅크',
  '아이엠뱅크',
  '하나은행',
  '토스뱅크',
  '케이뱅크',
  '국민은행',
  '부산은행',
  '농협은행',
  '기업은행',
  '광주은행',
  '신한은행'],
 'callCenter': ['1588-1500',
  '1588-0079',
  '1588-1599',
  '1588-4477',
  '1588-1515',
  '1599-5000',
  '1588-8585',
  '1599-3333',
  '1588-5050',
  '1599-1111',
  '1661-7654',
  '1522-1000',
  '1644-9999',
  '1588-6200',
  '1588-2100',
  '1566-2566',
  '1600-4000',
  '1599-8000']}

In [60]:
final_df=pd.DataFrame(result)
final_df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
10,20250310,3.74,0,0,0,0,0,0,0,20250316,토스뱅크,1661-7654
11,20250310,3.7,0,0,0,0,0,0,0,20250316,케이뱅크,1522-1000
12,20250310,3.89,0,0,0,0,0,0,0,20250316,국민은행,1644-9999
13,20250310,3.84,0,0,0,0,0,0,0,20250316,부산은행,1588-6200
14,20250310,4.05,0,0,0,0,0,0,0,20250316,농협은행,1588-2100
15,20250310,4.0,0,0,0,0,0,0,0,20250316,기업은행,1566-2566
16,20250310,4.11,0,0,0,0,0,0,0,20250316,광주은행,1600-4000
17,20250310,4.07,0,0,0,0,0,0,0,20250316,신한은행,1599-8000

# 반복문으로 태그를 자동으로 추출해서 만들기

In [61]:
for item in soup.select("*"):
    print(item.name) #모든 태그가 나옴

response
header
resultCode
resultMsg
body
pageNo
totalCount
numOfRows
items
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter
item
bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter

In [62]:
result={}
for item in soup.select("items"):
    for tags in item:
        for tag in tags:
            print(tag.name, tag.text)

bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 산업은행
callCenter 1588-1500
bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 제주은행
callCenter 1588-0079
bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId SC은행
callCenter 1588-1599
bssYmdStart 20250310
interest4_1 4.89
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 전북은행
callCenter 1588-4477
bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 수협은행
callCenter 1588-1515
bssYmdStart 20250310
interest4_1 4.26
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 우리은행
callCenter 1599-5000
bssYmdStart 20250310
interest4_1 4.64
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 경남은행
callCenter 1588-8585
bssYmdStart 20250310
interest4_1 3.5
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 카카오뱅크
callCenter 1599-3333
bssYmdStart 20250310
interest4_1 3.38
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 아이엠뱅크
callCenter 1588-5050
bssYmdStart 20250310
interest4_1 4.18
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 하나은행
callCenter 1599-1111
bssYmdStart 20250310
interest4_1 3.74
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 토스뱅크
callCenter 1661-7654
bssYmdStart 20250310
interest4_1 3.7
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 케이뱅크
callCenter 1522-1000
bssYmdStart 20250310
interest4_1 3.89
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 국민은행
callCenter 1644-9999
bssYmdStart 20250310
interest4_1 3.84
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 부산은행
callCenter 1588-6200
bssYmdStart 20250310
interest4_1 4.05
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 농협은행
callCenter 1588-2100
bssYmdStart 20250310
interest4_1 4.0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 기업은행
callCenter 1566-2566
bssYmdStart 20250310
interest4_1 4.11
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 광주은행
callCenter 1600-4000
bssYmdStart 20250310
interest4_1 4.07
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 신한은행
callCenter 1599-8000

# xml에 있는 모든 key를 추출하기

In [63]:
tag_names=[]
for tags in soup.select("*"):
    tag_names.append(tags.name)
tag_names

['response',
 'header',
 'resultCode',
 'resultMsg',
 'body',
 'pageNo',
 'totalCount',
 'numOfRows',
 'items',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'item',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter']

# 집합자료형 set : 중복 없는 데이터 집합 만들기

In [64]:
tags = set(tag_names)
tags

{'body',
 'bssYmdEnd',
 'bssYmdStart',
 'callCenter',
 'header',
 'interest1_1',
 'interest1_2',
 'interest2_1',
 'interest2_2',
 'interest3_1',
 'interest3_2',
 'interest4_1',
 'interest4_2',
 'item',
 'items',
 'numOfRows',
 'organId',
 'pageNo',
 'response',
 'resultCode',
 'resultMsg',
 'totalCount'}

# 공공데이터 서민대출 데이터 수집
* 금융위원회_서민금융상품 기본정보

In [2]:
serviceKey='bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj/eEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai+Nt11O7Bupwnz7usNQ=='

In [137]:
def extract_data(soup):
    s_data={}
    for item in soup.select('items'):
        for tags in item:
            try:
                for tag in tags:
                    if type(tag).__name__ == 'NavigableString':
                        pass
                    #print(type(tag))
                    else:
                        #print(tag.name,'&',tag.text)
                        s_data.setdefault(tag.name,[]).append(tag.text)
            except:
                pass
    s_df=pd.DataFrame(s_data)
    return s_df

In [141]:
all_data=[]
page=1
while True:
    url="https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
    payload=dict(serviceKey=serviceKey,numOfRows=100,pageNo=page)
    r=requests.get(url,params=payload)
    print(r.url)
    print(r.status_code)
    r=r.text
    soup=bs(r,'xml')
    all_data.append(extract_data(soup))
    total_pages=int(soup.find('totalCount').text) // 100 +1
    if page<total_pages:
        page+=1
    else:
        break
all_data=pd.concat(all_data)
all_data

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=1
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=2
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=3
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=4
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=5
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=6
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=7
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=8
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=9
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=10
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=11
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=12
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=13
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=14
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=15
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=16
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=17
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=18
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=19
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=20
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=21
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=22
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=23
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=24
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=25
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=26
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=27
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=28
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=29
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=30
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=31
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=32
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=33
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=34
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=35
200

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=36
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=37
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=38
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=39
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=40
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=41
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=42
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=43
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=44
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=45
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=46
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=47
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=100&pageNo=48
200

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
37,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
38,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
39,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,,1,대출상품,,,,,,202502010700
40,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700

In [17]:
total_pages=int(soup.find('totalCount').text) // 100 +1
total_pages

48

In [116]:
items=soup.find('items')
for tags in items:
    print(type(tags))
    if type(tags).__name__ == 'NavigableString':
        pass
    else:
        print(yes)
        
    
    #for tag in tags:
        #print(tag.name)

<class 'bs4.element.NavigableString'>
<class 'bs4.element.Tag'>

NameError: name 'yes' is not defined

# key_list를 만들고 select로 직접 추출하기

In [159]:
page=1
df_list=[]
while True:
    url="https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo"
    payload=dict(serviceKey=serviceKey,numOfRows=1000,pageNo=page)
    r=requests.get(url,params=payload)
    print(r.url)
    print(r.status_code)
    r=r.content
    soup=bs(r,'xml')
    total_pages=int(soup.find('totalCount').text) // 100 +1
    key_list={}
    for item in soup.select("*"):
            key_list.setdefault(item.name,"")
    key_list = list(key_list.keys())
    result={}
    for key in key_list[10:]:
        for item in soup.select(key):
            result.setdefault(item.name,[]).append(item.text)
    df_list.append(pd.DataFrame(result))
    if page < total_pages :
        page +=1
    else:
        break
df_list

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=1
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=2
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=3
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=4
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=5
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=6
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=7
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=8
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=9
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=10
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=11
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=12
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=13
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=14
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=15
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=16
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=17
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=18
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=19
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=20
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=21
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=22
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=23
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=24
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=25
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=26
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=27
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=28
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=29
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=30
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=31
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=32
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=33
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=34
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=35
200

https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=36
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=37
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=38
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=39
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=40
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=41
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=42
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=43
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=44
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=45
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=46
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=47
200
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo?serviceKey=bHIFU42JHODEOxpBSDyY7WlZ4HXUgbArtj%2FeEIuIVUws7xuPefS8R6sRYYZtC13Fr7ai%2BNt11O7Bupwnz7usNQ%3D%3D&numOfRows=1000&pageNo=48
200

[      basYm  snq                                          finPrdNm  \
 0    202503    1                                            새희망홀씨Ⅱ
 1    202503    2                                             징검다리론
 2    202503    3                       우리지역 氣-Up 서포트론(영세 소기업,소상공인)
 3    202503    4  경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업)
 4    202503    5                                  i-ONE근로자생활안정자금대출
 ..      ...  ...                                               ...
 995  202501  300                     익산시 희망더드림 특례보증(Track1 튼튼소상공인)
 996  202501  301                     익산시 희망더드림 특례보증(Track2 탄탄소상공인)
 997  202501  302                               전주시 희망더드림 안심연장 특례보증
 998  202501  303                                      전북 위기극복 특례보증
 999  202501  304                                    사회성과 우수기업 특례보증

                                  lnLmt irtCtg                    irt  \
 0                               3500만원   변동금리                 은행별 상이
 1                               3000만원   변동금리                 은행별 상이
 2    5,00010,000 (코로나 19 피해 소기업, 소상공인)   변동금리             6.27~8.97%
 3                               9000만원   변동금리                 은행별 상이
 4                               1000만원   고정금리  1.5 / 2.6 / 1.0 / 3.0
 ..                                 ...    ...                    ...
 995                             5000만원   변동금리                 ~2.68%
 996                             5000만원   변동금리                 ~1.68%
 997                                  -   변동금리                ~ 2.48%
 998                            20000만원   변동금리                ~ 3.07%
 999                            20000만원   변동금리                 ~3.07%

                                            maxTotLnTrm maxDfrmTrm maxRdptTrm  \
 0                                               은행별 상이          -          -
 1                                                   5년         1년         4년
 2                                                   5년         1년         4년
 3                                     임대차계약기간 이내 최대 2년         0년         0년
 4    근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...         6년         5년
 ..                                                 ...        ...        ...
 995                                                1~5         1년      4, 5년
 996                                                1~5         1년      4, 5년
 997                                                 9년         1년         8년
 998                                                1~5          -          -
 999                                                10년         1년         9년

         rdptMthd  ... prdExisYn cv19Rfrc prdCtg prdNm cv19SuprCtg cv19SuprCtn  \
 0    원(리)금균등분할상환  ...         Y        -      1  대출상품           -           -
 1    원(리)금균등분할상환  ...         Y        -      1  대출상품           -           -
 2       원금균등분할상환  ...         Y        -      1  대출상품           -           -
 3           일시상환  ...         Y        -      1  대출상품           -           -
 4    원(리)금균등분할상환  ...         Y        -      1  대출상품           -           -
 ..           ...  ...       ...      ...    ...   ...         ...         ...
 995     원금균등분할상환  ...         Y        -      1  대출상품           -           -
 996     원금균등분할상환  ...         Y        -      1  대출상품           -           -
 997     원금균등분할상환  ...         Y        -      1  대출상품           -           -
 998         일시상환  ...         Y        -      1  대출상품           -           -
 999     원금균등분할상환  ...         Y        -      1  대출상품           -           -

     cv19SuprTgtDtlCtn mgmDln prdCtg2     fileWrtDt
 0                   -     상시       -  202504010700
 1                   -  기관 문의       -  202504010700
 2                   -     상시       -  202504010700
 3                   -     상시       -  202504010700
 4                   -     상시       -  202504010700
 ..                ...    ...     ...           ...
 995                 -  기관 문의       -  202502071556
 996                 -  기관 문의       -  202502071556
 997                 -  기관 문의       -  202502071556
 998                 -  기관 문의       -  202502071556
 999                 -  기관 문의       -  202502071556

 [1000 rows x 47 columns],
       basYm  snq                   finPrdNm    lnLmt irtCtg      irt  \
 0    202501  305             군산시 희망더드림 특례보증   5000만원   변동금리  ~ 2.62%
 1    202501  306        취약계층 소상공인 금융지원 협약보증   2000만원      -        -
 2    202501  307            기업정주여건(기숙사)조성지원  30000만원   변동금리    2.31%
 3    202501  308                 가족친화기업특별자금  30000만원   고정금리       3%
 4    202501  309                 탄소저감시설지원자금  50000만원   고정금리       3%
 ..      ...  ...                        ...      ...    ...      ...
 995  202201  111           저소득 주민생활 안정자금 지원   1000만원   고정금리       2%
 996  202201  112  국민기초생활안정융자금 융자제도(사업,전세자금)   2000만원   고정금리       2%
 997  202201  113      국민기초생활안정융자금 융자제도(학자금)    400만원   고정금리       0%
 998  202201  114         기초생활보장기금 생활안정자금 융자   1000만원   고정금리       1%
 999  202201  115           저소득주민 생활안정자금(일반)   1000만원   고정금리       1%

     maxTotLnTrm maxDfrmTrm maxRdptTrm     rdptMthd  ... prdExisYn cv19Rfrc  \
 0            5년         1년         4년     원금균등분할상환  ...         Y        -
 1            5년         1년         4년     원금균등분할상환  ...         Y        -
 2            3년         1년         2년       균등분할상환  ...         Y        -
 3            2년         0년         0년         일시상환  ...         Y        -
 4            5년         2년         3년       균등분할상환  ...         Y        -
 ..          ...        ...        ...          ...  ...       ...      ...
 995          6년         1년         5년  원(리)금균등분할상환  ...         Y
 996         12년         2년        10년       균등분할상환  ...         Y
 997          7년         4년         3년       균등분할상환  ...         Y
 998          5년         2년         3년       균등분할상환  ...         Y
 999          6년         2년         4년       균등분할상환  ...         N

     prdCtg prdNm cv19SuprCtg cv19SuprCtn cv19SuprTgtDtlCtn             mgmDln  \
 0        1  대출상품           -           -                 -              기관 문의
 1        1  대출상품           -           -                 -          한도 소진 시까지
 2        1  대출상품           -           -                 -           자금 소진시까지
 3        1  대출상품           -           -                 -           자금 소진시까지
 4        1  대출상품           -           -                 -           자금 소진시까지
 ..     ...   ...         ...         ...               ...                ...
 995      1  대출상품                                            지자체 사업계획에 따라 상시모집
 996      1  대출상품                                            지자체 사업계획에 따라 상시모집
 997      1  대출상품                                            지자체 사업계획에 따라 상시모집
 998      1  대출상품                                            지자체 사업계획에 따라 상시모집
 999      1  대출상품

     prdCtg2     fileWrtDt
 0         -  202502071556
 1         -  202502071556
 2         -  202502071556
 3         -  202502071556
 4         -  202502071556
 ..      ...           ...
 995  지자체·복지  202201040923
 996  지자체·복지  202201040923
 997  지자체·복지  202201040923
 998  지자체·복지  202201040923
 999          202201040923

 [1000 rows x 47 columns],
       basYm  snq                       finPrdNm   lnLmt irtCtg irt  \
 0    202201  116              저소득주민 생활안정자금(학자금)   500만원   고정금리  0%
 1    202201  117           저소득주민 생활안정자금 융자 (일반)   500만원   고정금리  3%
 2    202201  118          저소득주민 생활안정자금 융자 (학자금)   200만원   고정금리  0%
 3    202201  119   기초생활수급자 등 생활안정자금 융자 및 관리(일반)  1000만원   고정금리  1%
 4    202201  120  기초생활수급자 등 생활안정자금 융자 및 관리(학자금)   400만원   고정금리  0%
 ..      ...  ...                            ...     ...    ...  ..
 995  202112  284       미소금융 특별자금(코로나19, 특별재난지역)
 996  202112  285                  신복위 채무조정 상환유예
 997  202112  286               국민행복기금 및 캠코 상환유예
 998  202112  287                     코로나19 직접대출
 999  202112  288               코로나 피해 소상공인 특례보증

     maxTotLnTrm maxDfrmTrm maxRdptTrm rdptMthd  ... prdExisYn  \
 0            6년         3년         3년   균등분할상환  ...         N
 1            6년         2년         4년   균등분할상환  ...         Y
 2            6년         3년         3년   균등분할상환  ...         Y
 3            7년         1년         6년   균등분할상환  ...         N
 4            6년         3년         3년   균등분할상환  ...         N
 ..          ...        ...        ...      ...  ...       ...
 995                                             ...         Y
 996                                             ...         Y
 997                                             ...         Y
 998                                             ...         Y
 999                                             ...         Y

                   cv19Rfrc prdCtg    prdNm cv19SuprCtg  \
 0                               1     대출상품
 1                               1     대출상품
 2                               1     대출상품
 3                               1     대출상품
 4                               1     대출상품
 ..                     ...    ...      ...         ...
 995             (국번없이)1397      2  코로나19상품        자금지원
 996              1600-5500      2  코로나19상품        상환유예
 997              1588-3570      2  코로나19상품  이자감면, 상환유예
 998  중소기업통합콜센터 (국번없이 1357)      2  코로나19상품        자금지원
 999              1588-7365      2  코로나19상품        자금지원

                          cv19SuprCtn  \
 0
 1
 2
 3
 4
 ..                               ...
 995  상품별 대출한도 1.5배 확대, 연 2.0%로 금리 인하
 996               조정채무의 상환을 6개월 간 유예
 997       최대 6개월 채무상환유예, 연체가산이자 면제 등
 998                 자금구분별 한도 및 금리 상이
 999               지역신용보증재단별 지원 내용 상이

                                      cv19SuprTgtDtlCtn mgmDln prdCtg2  \
 0
 1                                                       기관 문의  지자체·복지
 2                                                       기관 문의  지자체·복지
 3
 4
 ..                                                 ...    ...     ...
 995  1인당 최대 7천만원(기존 미소금융 상품별 대출한도 1.5배 확대), 연 금리 2....
 996  조정채무의 상환을 6개월 간 유예→6개월 경과 후부터 상환계획 재이행 (유예기간 동...
 997  (무담보채무자) 채무조정 약정자 최대 6개월 채무 상환유예, 미약정자 신규 약정시 ...
 998  자금구분별 한도 및 금리 상이<br>* (자금종류) 소공인특화자금, 소상공인 사관학...
 999                                 지역신용보증재단별 지원 내용 상이

         fileWrtDt
 0    202201040923
 1    202201040923
 2    202201040923
 3    202201040923
 4    202201040923
 ..            ...
 995  202112011012
 996  202112011012
 997  202112011012
 998  202112011012
 999  202112011012

 [1000 rows x 47 columns],
       basYm  snq                   finPrdNm   lnLmt irtCtg       irt  \
 0    202112  289                     초저금리대출
 1    202112  290       힘내라 대한민국 특별운영자금 (일반)
 2    202112  291       힘내라 대한민국 특별운영자금 (신속)
 3    202112  292           중소기업 긴급경영안정자금 지원
 4    202112  293            코로나19 위기극복 특례보증
 ..      ...  ...                        ...     ...    ...       ...
 995  202111  460  2021 강원도 소상공인 경영안정자금 협약보증  5000만원   변동금리         -
 996  202111  461                부산광역시 청년부비론  1500만원   고정금리        1%
 997  202111  462                  서울특별시 한강론  1200만원   고정금리        3%
 998  202111  463                충청남도 더행복충남론  1500만원   고정금리  2.0~4.0%
 999  202111  464                 전라남도 행복드림론  1500만원   고정금리  2.0~3.5%

     maxTotLnTrm maxDfrmTrm                             maxRdptTrm   rdptMthd  \
 0
 1
 2
 3
 4
 ..          ...        ...                                    ...        ...
 995          5년         0년  5년이내<br/>(최초 보증기간 2년으로 1년단위로 기한연장 가능)          -
 996          5년         0년                                     5년  원리금균등분할상환
 997          5년         0년                                     5년  원리금균등분할상환
 998          5년         0년                                     5년  원리금균등분할상환
 999          5년         0년                                     5년  원리금균등분할상환

      ... prdExisYn                  cv19Rfrc prdCtg    prdNm  cv19SuprCtg  \
 0    ...         N                 1588-2588      2  코로나19상품  자금지원, 보증료감면
 1    ...         Y  02-877-5612, 02-787-5615      2  코로나19상품         자금지원
 2    ...         Y  02-877-5612, 02-787-5615      2  코로나19상품         자금지원
 3    ...         Y                      1357      2  코로나19상품         자금지원
 4    ...         Y                 1588-6565      2  코로나19상품  자금지원, 보증료감면
 ..   ...       ...                       ...    ...      ...          ...
 995  ...         Y                                1     대출상품
 996  ...         Y                                1     대출상품
 997  ...         Y                                1     대출상품
 998  ...         Y                                1     대출상품
 999  ...         Y                                1     대출상품

                                          cv19SuprCtn  \
 0               업체당 1억원, 금리 3년간 최저 1.5% (보증료 1년 감면),
 1         중소 및 기타기업(공공기관  제외) 500억원, 중견기업 1,000억원 이내
 2            중소 및 기타기업(공공기관 제외) 100억원, 중견기업 200억원 이내
 3                                     기업당 최대 10억원 이내
 4    기업당 최대 3억원, 최대95% 부분보증비율, 보증료율 최대0.3%p차감(최대 1%)
 ..                                               ...
 995
 996
 997
 998
 999

                                      cv19SuprTgtDtlCtn              mgmDln  \
 0        업체당 1억원, 금리 3년간 최저 1.5% (보증료 1년 감면), 기간 최대 8년
 1    중소 및 기타기업(공공기관  제외) 500억원, 중견기업 1,000억원 이내<br>...
 2    중소 및 기타기업(공공기관 제외) 100억원, 중견기업 200억원 이내<br>자금운...
 3    기업당 최대 10억원 이내, 대출기간 5년 이내(거치기간 2년 이내)<br>- 정책...
 4    기업당 최대 3억원, 최대95% 부분보증비율, 보증료율 최대0.3%p차감(최대 1%...          ~2021.6.30
 ..                                                 ...                 ...
 995                                                     2021.2.2~한도 소진시 까지
 996                                                                     상시
 997                                                                     상시
 998                                                                     상시
 999                                                                     상시

     prdCtg2     fileWrtDt
 0            202112011012
 1            202112011012
 2            202112011012
 3            202112011012
 4            202112011012
 ..      ...           ...
 995    정책자금  202111151046
 996    정책자금  202111151046
 997    정책자금  202111151046
 998    정책자금  202111151046
 999    정책자금  202111151046

 [1000 rows x 47 columns],
       basYm  snq                     finPrdNm     lnLmt       irtCtg  \
 0    202111  465                  전라북도 더불어행복론    1500만원         고정금리
 1    202111  466               소상공인 고용연계 융자지원    1000만원         고정금리
 2    202111  467                소상공인 사업장 구입자금  100000만원       은행별 상이
 3    202111  468          취약계층 소상공인 희망드림 특례보증    2000만원       은행별 상이
 4    202111  469         코로나19 위기극복 소상공인 특례보증    2000만원         고정금리
 ..      ...  ...                          ...       ...          ...
 736  202110  425              온(溫, ON)택트 특례보증    2850만원         변동금리
 737  202110  426                 위기업종 지원 협약보증    5000만원            -
 738  202110  427  익산시 소상공인 특례보증(2023 하나은행 출연)    5000만원         고정금리
 739  202110  428               중소벤처기업부 소상공인자금    7000만원  자금별 별도금리 적용
 740  202110  429           착한가격업소 활성화 지원 특별보증    2000만원            -

                  irt maxTotLnTrm maxDfrmTrm      maxRdptTrm  \
 0           2.0~4.0%          5년         0년              5년
 1                 2%          5년         2년              3년
 2           은행금리-1.0      15년 이내        1~5  은행별 상이 (8~10년)
 3    연 1.5% 지원 (인천시)          5년         1년              4년
 4               2.7%       2, 5년      0, 2년              0년
 ..               ...         ...        ...             ...
 736      대출실행 은행에 문의          5년         1년              4년
 737                -       1, 5년         1년              4년
 738           약 1.6%          5년         1년              4년
 739                -          5년         2년              3년
 740                -          5년          -               -

                        rdptMthd  ... prdExisYn cv19Rfrc prdCtg prdNm  \
 0                     원리금균등분할상환  ...         Y               1  대출상품
 1    거치기간 후 상환기간 동안 매월 원금균등분할상환  ...         Y               1  대출상품
 2                일시상환방식, 분할상환방식  ...         Y               1  대출상품
 3                        원금분할상환  ...         Y               1  대출상품
 4                        만기일시상환  ...         Y               1  대출상품
 ..                          ...  ...       ...      ...    ...   ...
 736                    원금균등분할상환  ...         Y               1  대출상품
 737                    원금균등분할상환  ...         Y               1  대출상품
 738                    원금균등분할상환  ...         Y               1  대출상품
 739                        분할상환  ...         Y               1  대출상품
 740                           -  ...         Y               1  대출상품

     cv19SuprCtg cv19SuprCtn cv19SuprTgtDtlCtn               mgmDln prdCtg2  \
 0                                                               상시    정책자금
 1                                              2021.4.12~자금 소진 시까지    정책자금
 2                                               2021.4.1~자금 소진 시까지    정책자금
 3                                              2021.3.22∼자금 소진 시까지    정책자금
 4                                                        한도 소진 시까지    정책자금
 ..          ...         ...               ...                  ...     ...
 736
 737
 738
 739
 740

         fileWrtDt
 0    202111151046
 1    202111151046
 2    202111151046
 3    202111151046
 4    202111151046
 ..            ...
 736  202502010700
 737  202502010700
 738  202502010700
 739  202502010700
 740  202502010700

 [741 rows x 47 columns],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: []]

In [162]:
df_final=pd.concat(df_list)
df_final=df_final.reset_index(drop=True)
df_final.to_csv("서민금융상품_대출정보.csv",encoding="utf-8",index=False)

In [158]:
total_pages=int(soup.find('totalCount').text) // 100 +1
total_pages

48

In [153]:
key_list={}
for item in soup.select("*"):
        key_list.setdefault(item.name,"")
key_list = list(key_list.keys())
key_list

['response',
 'header',
 'resultCode',
 'resultMsg',
 'body',
 'numOfRows',
 'pageNo',
 'totalCount',
 'items',
 'item',
 'basYm',
 'snq',
 'finPrdNm',
 'lnLmt',
 'irtCtg',
 'irt',
 'maxTotLnTrm',
 'maxDfrmTrm',
 'maxRdptTrm',
 'rdptMthd',
 'usge',
 'trgt',
 'instCtg',
 'ofrInstNm',
 'rsdAreaPamtEqltIstm',
 'suprTgtDtlCond',
 'age',
 'incm',
 'rsdArea',
 'crdtSc',
 'anin',
 'housHoldCnt',
 'housAr',
 'lnTgtHous',
 'rfrcCnpl',
 'grnInst',
 'jnMthd',
 'rpymdCfe',
 'lnIcdcst',
 'ovItrYr',
 'prftAddIrtCond',
 'etcRefSbjc',
 'hdlInst',
 'cnpl',
 'rltSite',
 'tgtFltr',
 'hdlInstDtlVw',
 'prdExisYn',
 'cv19Rfrc',
 'prdCtg',
 'prdNm',
 'cv19SuprCtg',
 'cv19SuprCtn',
 'cv19SuprTgtDtlCtn',
 'mgmDln',
 'prdCtg2',
 'fileWrtDt']

In [155]:
result={}
for key in key_list:
    for item in soup.select(key):
        result.setdefault(item.name,[]).append(item.text)
df=pd.DataFrame(result)
df

ValueError: All arrays must be of the same length