In [1]:
import requests
import pandas as pd
import time
import os
from bs4 import BeautifulSoup as bs

In [3]:
url="https://kind.krx.co.kr/corpgeneral/corpList.do?method=loadInitPage"

In [4]:
r=requests.get(url)
print(r.status_code)
soup = bs(r.content, 'lxml')
soup
# 기업 정보는 실시간 반영되는 형태라 html로 저장되어있지 않아서 위 코드로는 확인 불가

200

<!DOCTYPE html>
<html lang="ko">
<head>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="kr" http-equiv="content-language"/>
<meta content="text/css" http-equiv="content-style-type"/>
<meta content="no-cache" http-equiv="pragma"/>
<meta content="no-cache" http-equiv="cache-control"/>
<meta content="no" http-equiv="imagetoolbar"/>
<meta content="대한민국 대표 기업공시채널 KIND(c)2014" name="copyright"/>
<meta content="대한민국 대표 기업공시채널 KIND" name="description"/>
<meta content="대한민국 대표 기업공시채널 KIND" name="keywords"/>
<title>대한민국 대표 기업공시채널 KIND</title>
<link href="../images/kind.ico" rel="shortcut icon"/>
<link href="../js/jquery/themes-base/jquery-ui.min.css" media="all" rel="stylesheet" type="text/css"/>
<link href="../css/default_new.css" media="all" rel="stylesheet" type="text/css"/>
<link href="../css/common.css?version=20240927" media="all" rel="stylesheet" type="text/css"/>
<link href="../css/style.css?version=20240524" media="all" rel="stylesheet" type="text/css"/>
<link href="../esg/notoSans.css?20240524" media="all" rel="stylesheet" type="text/css"/>
<!--[if lt IE 9]>
<script type="text/javascript" src="../js/html5shiv.js"></script>
<![endif]-->
<script src="../js/dtree.js" type="text/javascript"></script>
<script src="../js/trans.js" type="text/javascript"></script>
<script src="../js/jquery/jquery.js" type="text/javascript"></script>
<script src="../js/jquery/jquery-ui.min.js" type="text/javascript"></script>
<script src="../js/jquery/jquery.placeholder.js" type="text/javascript"></script>
<script src="../js/common.js?version=20240927" type="text/javascript"></script>
<script src="../js/common-ajax.js" type="text/javascript"></script>
<script src="../js/JCommon.js?version=20240809" type="text/javascript"></script>
<script src="../js/common-sort.js" type="text/javascript"></script>
</head>
<body>
<!-- 화면 확대/축소 안내 START-->
<section class="notice popup modal type-00 hide">
<div class="container">
<div class="wrapper">
<hgroup class="handle"><h2>화면 확대/축소 안내</h2></hgroup>
<a class="btn-pop-close btn_close" href="#">닫기</a>
<section class="body">
<ul class="msg type-99 fc01">
<li>※ IE8 이하의 웹브라우저에서는 다음과 같은 방법으로 화면의 확대/축소 기능을 이용하실 수 있습니다.</li>
</ul>
<img alt="화면확대 화면축소" src="../images/common/notice.png"/>
</section>
</div>
<img alt="배경이미지" class="tl" src="../images/common/pop-type-00-tl.png"/>
<img alt="배경이미지" class="bl" src="../images/common/pop-type-00-bl.png"/>
<img alt="배경이미지" class="tr" src="../images/common/pop-type-00-tr.png"/>
<img alt="배경이미지" class="br" src="../images/common/pop-type-00-br.png"/>
<div class="tm"></div>
<div class="lm"></div>
<div class="bm"></div>
<div class="rm"></div>
</div>
</section>
<!-- HEADER 영역 START -->
<header class="container">
<div class="container_line">
<div class="wrapper-super">
<hgroup>
<h1 class="logo"><a href="/main.do?method=loadInitPage&amp;scrnmode=1" title="대한민국 대표 기업공시채널 KIND"><img alt="대한민국 대표 기업공시채널 KIND" src="../images/main/logo.gif"/></a></h1>
</hgroup>
<ul class="util">
<li class="first"><a href="/common/JLDDST35000.html" onclick="winCommPopOpen('1'); return false;" title="KIND 소개 새창"><img alt="KIND 소개" src="../images/common/util_intro.gif"/></a></li>
<li>
<a href="https://engkind.krx.co.kr/" target="_blank" title="KIND 영문사이트 바로가기"><img alt="ENGLISH KIND" src="../images/common/util_eng.gif"/></a>
</li>
<li class="btn-group">
<img alt="화면크기" class="ttl" src="../images/common/ttl_screen.gif"/>
<a class="plus zoom_btn-in" href="#"><span>확대</span></a>
<a class="reset zoom_btn-reset" href="#"><span>원래대로</span></a>
<a class="minus zoom_btn-out" href="#"><span>축소</span></a>
</li>
</ul>
<div class="clear"></div>
<form id="AKCFrm" name="AKCFrm">
<input id="method" name="method" type="hidden" value="disclosureSimpleSearchMain"/>
<input id="searchCodeType" name="searchCodeType" type="hidden" value=""/>
<input id="repIsuSrtCd" name="repIsuSrtCd" type="hidden" value=""/>
<input id="isurCd" name="isurCd" type="hidden" value=""/>
<input id="AKCKwdCode" name="AKCKwdCode" type="hidden" value=""/>
<section class="search auto_complete top-akc-sub">
<div class="autoKey">
<input autocomplete="off" class="search-txt dval" id="AKCKwdTop" name="searchCorpName" onblur="chkValidChar_top(this); fnMainCorpType();" placeholder="회사명 또는 종목코드를 입력해 주세요." type="text"/>
<div class="tselect">
<img alt="자동완성 열기" class="autoc_open" id="AKCArrowTop" src="../images/common/icn_autoc_open.gif"/>
<div class="AKCDivTop" id="AKCDivTop" style="display:none;">
<iframe frameborder="0" id="AKCIfrmTop" name="AKCIfrmTop" scrolling="no" src="../common/akc_top.html?version=20220624" title="자동완성"></iframe>
</div>
</div>
</div>
<input alt="검색" class="submit" onclick="fnTopAKCKwdSearch(); return false;" src="../images/common/btn_search.gif" type="image"/>
<div class="clear"></div>
</section>
</form>
<a class="btn sitemap open" href="#"><img alt="전체메뉴보기" src="../images/common/btn_sitemap.gif"/></a>
</div>
</div>
<div class="sitemap-wrapper">
<!-- TOP MENU START -->
<section class="sitemap">
<article class="mymenu">
<h3><img alt="나만의 메뉴" src="../images/common/ttl_sitemap_my.png"/></h3>
<div class="list">
<ul id="myMenuTop">
<li class="active"><a href="/disclosure/todaydisclosure.do?method=searchTodayDisclosureMain">오늘의공시</a></li>
<li><a href="/disclosure/searchdisclosurebycorp.do?method=searchDisclosureByCorpMain">회사별검색</a></li>
<li><a href="/disclosure/searchtotalinfo.do?method=searchTotalInfoMain">통합검색</a></li>
<li><a href="/disclosure/details.do?method=searchDetailsMain">상세검색</a></li>
<li><a href="/corpdetail/totalinfo.do?method=loadInitPage">종합정보</a></li>
</ul>
</div>
<a class="btn_sitemap-set" href="#"><img alt="설정" src="../images/common/btn_sitemap_set.png"/></a>
</article>
<section class="list-wrapper links">
<article class="list">
<h3>공시</h3>
<ul>
<li><a class="first" href="/disclosure/todaydisclosure.do?method=searchTodayDisclosureMain">오늘의공시</a></li>
<li><a class="first" href="/disclosure/searchdisclosurebycorp.do?method=searchDisclosureByCorpMain">회사별검색</a></li>
<li><a class="first" href="/disclosure/details.do?method=searchDetailsMain">상세검색</a></li>
<li><a class="first" href="#" onclick="krxPaPago_open(); return false;">KRX-Papago번역기</a></li>
<li><a class="first" href="/disclosure/searchtotalinfo.do?method=searchTotalInfoMain">통합검색</a></li>
<li><a class="first" href="/disclosure/searchbondcorpdisclosure.do?method=searchBondCorpDisclosureMain">채권공시</a></li>
<li><a class="more" href="#">ETF/ELW/ETN<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeEtf">ETF</a>
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeElw">ELW</a>
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeEtn">ETN</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="more" href="#">펀드공시<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeRestinvstcom">부동산투자회사</a>
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeShipinvstcom">선박투자회사</a>
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeInvstcom">투자회사</a>
<a class="lmn" href="/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeBenfcert">수익증권</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/disclosure/misccorpdiscls.do?method=searchMiscCorpDisclsMain">기타법인공시</a></li>
<li><a class="more" href="#">의결권행사공시<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/disclosure/disclosurebyvote.do?method=searchDisclosurebyVoteMain">의결권행사공시</a>
<a class="lmn" href="https://dis.kofia.or.kr/websquare/index.jsp?w2xPath=/wq/compann/DISFndVoteRightView.xml&amp;divisionId=MDIS02003010000000&amp;serviceId=SDIS02003010000#!" target="_blank">운용사 펀드의결권행사공시</a>
<a class="lmn" href="https://dis.kofia.or.kr/websquare/index.jsp?w2xPath=/wq/compann/DISFndVoteRightViewDet.xml&amp;divisionId=MDIS02003011000000&amp;serviceId=SDIS02003011000" target="_blank">펀드별 의결권행사공시</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/corpdetail/chart.do?method=loadInitPage">공시차트</a></li>
<li><a class="first" href="/disclosure/searchErrorTradeRelief.do?method=searchErrorTradeReliefMain">착오매매구제신청</a></li>
<!-- 신종증권 메뉴 제외 -->
<!--<li><a href="#" class="more">신종증권<span><img src="../images/common/bg_gnb_gmn2.gif" alt="메뉴 더보기"/></span></a></li>
						<DIV id="sub" class="gnb1-wrapper">
							<nav id="gnb1">
							<DL>
							<DD>
							<DIV class="lnb">
								<DIV class="wrapper">
									<A class="lmn" href="/digital/digitalList.do?method=digitalList">비금전신탁수익증권</A>
									<A class="lmn" href="/digital/digitalInvstList.do?method=digitalInvstList">투자계약증권</A>
									<IMG class="arrow" src="../images/common/lnb_arrow_sub.png" />
									<IMG class="tl" src="../images/common/lnb_tl.png" />
									<IMG class="tr" src="../images/common/lnb_tr.png" />
									<IMG class="bl" src="../images/common/lnb_bl.png" />
									<IMG class="br" src="../images/common/lnb_br.png" />
								</DIV>
							</DIV>
							</DD>
							</DL>
							</nav>
						</DIV>
						-->
</ul>
</article>
<article class="list">
<h3>상장법인상세정보</h3>
<ul>
<li><a class="first" href="/corpdetail/totalinfo.do?method=loadInitPage">종합정보</a></li>
<li><a class="first" href="/corpgeneral/listedIssueStatus.do?method=loadInitPage">상장종목현황</a></li>
<li><a class="first" href="/corpgeneral/corpList.do?method=loadInitPage">상장법인목록</a></li>
<li><a class="first" href="/corpgeneral/stockissuelist.do?method=loadInitPage">주식발행내역</a></li>
<li><a class="more" href="#">기업지배구조<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/corpgeneral/companyGovernance.do?method=loadInitPage">기업지배구조 보고서</a>
<a class="lmn" href="http://www.cgs.or.kr/business/esg_tab04.jsp" target="_blank">ESG등급</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/corpgeneral/treasurystk.do?method=loadInitPage">자사주취득/처분</a></li>
<li><a class="more" href="#">IR일정/IR자료실<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/corpgeneral/irschedule.do?method=searchIRScheduleMain&amp;gubun=iRSchedule">IR일정</a>
<a class="lmn" href="/corpgeneral/irschedule.do?method=searchIRScheduleMain&amp;gubun=iRMaterials">IR자료실</a>
<a class="lmn" href="https://www.youtube.com/playlist?list=PLAgvDyD2zN6ry9AVlh2emmvoJy4K39KT7" target="_blank">영상자료</a>
<a class="lmn" href="/corpgeneral/irschedule.do?method=searchIRScheduleMain&amp;gubun=iRScheduleCalendar">IR일정 달력</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="more" href="#">기업분석보고서<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/corpgeneral/companyAnalysisReport.do?method=listingForeignCompanyMain&amp;searchGubun=companyAnalysisReport">기업분석리포트</a>
<a class="lmn" href="/corpgeneral/newListingForeignCompany.do?method=listingForeignCompanyMain&amp;searchGubun=newListingForeignCompany">신규상장기업분석보고서</a>
<a class="lmn" href="/corpgeneral/growthReport.do?method=listingForeignCompanyMain&amp;searchGubun=growthReport">사업모델 평가보고서 및 기업 계속성 보고서</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/corpgeneral/corpGroup.do?method=loadInitPage">기업집단</a></li>
<li><a class="more" href="#">배당정보<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/disclosureinfo/dividendinfo.do?method=searchDividendInfoMain">배당정보</a>
<a class="lmn" href="http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201010107" target="_blank">업종배당수익율</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/compfinance/financialinfo.do?method=loadInitPage&amp;searchgubun=corporation">회사재무비교</a></li>
<li><a class="first" href="/corpgeneral/excntDisclsCompany.do?method=loadInitPage">공시우수법인</a></li>
<li><a class="first" href="/corpdetail/ventureFundInvest.do?method=corpListMain">벤처펀드투자기업(코)</a></li>
<!-- 신종증권 메뉴 제외 -->
<!--<li><a href="/digital/digitalCorpList.do?method=digitalCorpList" class="first">상장종목(신종증권)</a></li>-->
</ul>
</article>
<article class="list">
<h3>기업 밸류업 정보</h3>
<ul>
<li><a class="first" href="/valueup/intro.do?method=valueupIntroMain">기업 밸류업 소개</a></li>
<li><a class="first" href="/valueup/notice.do?method=valueupNoticeMain">공지사항</a></li>
<li><a class="first" href="/valueup/disclsstat.do?method=valueupDisclsStatMain">공시현황</a></li>
<li><a class="more" href="#">투자지표<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/valueup/invstindicsectors.do?method=valueupInvstIndicRankIndMain">업종별 투자지표 순위</a>
<a class="lmn" href="/valueup/invstindicstocks.do?method=valueupInvstIndicRankIsuMain">종목별 투자지표 추이</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="first" href="/valueup/idx.do?method=valueupIdxMain">인덱스</a></li>
<li><a class="first" href="/valueup/excntcorp.do?method=valueupExcntCorpMain">기업 밸류업 우수법인</a></li>
<li><a class="first" href="/valueup/resoroom.do?method=valueupResoroomMain">자료실</a></li>
</ul>
</article>
<article class="list weight">
<h3>투자유의사항</h3>
<ul>
<li><a class="first" href="/investwarn/adminissue.do?method=searchAdminIssueList">관리종목</a></li>
<li><a class="first" href="/investwarn/hwangiissue.do?method=searchHwangiIssueMain">투자주의환기종목(코)</a></li>
<li><a class="first" href="/investwarn/tradinghaltissue.do?method=searchTradingHaltIssueMain">매매거래정지종목</a></li>
<li><a class="first" href="/investwarn/undisclosure.do?method=searchUnfaithfulDisclosureCorpList">불성실공시법인</a></li>
<li><a class="first" href="/investwarn/investattentwarnrisky.do?method=investattentwarnriskyMain">투자주의/경고/위험종목</a></li>
<li><a class="first" href="/corpgeneral/delistRealInvstg.do?method=searchDelistRealInvstgMain">실질심사법인</a></li>
<li><a class="first" href="/investwarn/investattentEmbezzlement.do?method=searchInvestAttentEmbezzlementMain">횡령 등</a></li>
<li><a class="first" href="/investwarn/investattentLargeShareChange.do?method=searchInvestAttentLargeShareChangeMain">최대주주변경2회이상</a></li>
<li><a class="more" href="#">기타사항<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/investwarn/investattentEtcMarket.do?method=searchInvestAttentEtcMarketMain">기타 시장안내</a>
<a class="lmn" href="/investwarn/prtdepoStat.do?method=searchPrtdepoStatMain">의무보유현황(유가)</a>
<a class="lmn" href="/investwarn/penalty.do?method=searchPenaltyImprovementList">벌점및개선계획서 현황</a>
<a class="lmn" href="/investwarn/delcompany.do?method=searchDelCompanyMain">상장폐지현황</a>
<a class="lmn" href="/investwarn/delListDelibRec.do?method=searchDelListDelibRecMain">상장폐지최종심의의사록</a>
<a class="lmn" href="/investwarn/investwarnGuide.do?method=searchInvestGuideMain">투자유의안내</a>
<a class="lmn" href="/disclosureinfo/nfaithdisclsdecl.do?method=insertNfaithdisclsDeclMain">불성실공시 신고포상</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
</ul>
</article>
<article class="list">
<h3>IPO현황</h3>
<ul>
<li><a class="first" href="/listinvstg/listinvstgcom.do?method=searchListInvstgCorpMain">예비심사기업</a></li>
<li><a class="first" href="/listinvstg/listapplcom.do?method=searchListApplCorpMain">코넥스 상장신청기업</a></li>
<li><a class="more" href="#">공모기업<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/listinvstg/pubofrprogcom.do?method=searchPubofrProgComMain">공모기업현황</a>
<a class="lmn" href="/listinvstg/pubofrschdl.do?method=searchPubofrScholMain">공모일정</a>
<img class="arrow" src="../images/common/lnb_arrow_sub.png"/>
<img class="tl" src="../images/common/lnb_tl.png"/>
<img class="tr" src="../images/common/lnb_tr.png"/>
<img class="bl" src="../images/common/lnb_bl.png"/>
<img class="br" src="../images/common/lnb_br.png"/>
</div>
</div>
</dd>
</dl></nav>
</div>
<li><a class="more" href="#">신규상장기업<span><img alt="메뉴 더보기" src="../images/common/bg_gnb_gmn2.gif"/></span></a></li>
<div class="gnb1-wrapper" id="sub">
<nav id="gnb1"><dl>
<dd>
<div class="lnb">
<div class="wrapper">
<a class="lmn" href="/listinvstg/listingcompany.do?method=searchListingTypeMain">신규상장기업현황</a>
<a class="lmn" href="/listinvstg/mergeListingCompany.do?method=searchMergeListingCompMain">합병상장기업현황</a>
<a class="lmn" href="/listinvstg/genfinance.do?method=searchGenFinanaceMain">재무현황</a>

In [6]:
soup.select_one("#companysum").text  #태그 자체가 없음

AttributeError: 'NoneType' object has no attribute 'text'

In [ ]:
#페이지 payload에서 페이지 변환 가능 확인
https://kind.krx.co.kr/corpgeneral/corpList.do?

method=searchCorpList&pageIndex=1&currentPageSize=100&comAbbrv=&beginIndex=&orderMode=3&orderStat=D&isurCd=&repIsuSrtCd=&searchCodeType=&marketType=&searchType=13&industry=&fiscalYearEnd=all&comAbbrvTmp=&location=all

#pageIndex만 바꾸면 페이지 이동

In [7]:
url2='https://kind.krx.co.kr/corpgeneral/corpList.do'

In [8]:
url2='https://kind.krx.co.kr/corpgeneral/corpList.do'
payload = dict(method='searchCorpList', pageIndex=1, currentPageSize=100, orderMode=3, orderStat='D', searchType=13, fiscalYearEnd='all', location='all')

In [11]:
r=requests.post(url2,data=payload)
print(r.status_code)
soup = bs(r.content, 'lxml')
soup

200

<html><body><section class="scrarea type-00">
<table class="list type-00 tmt30" summary="회사명, 업종, 주요제품, 상장일, 결산월, 대표자명, 홈페이지, 지역">
<caption>목록</caption>
<colgroup>
<col width="*"/>
<col width="15%"/>
<col width="20%"/>
<col width="11%"/>
<col width="8%"/>
<col width="10%"/>
<col width="8%"/>
<col width="12%"/>
</colgroup>
<thead>
<tr class="first" id="title-contents">
</tr>
</thead>
<tbody>
<tr class="first">
<td class="first" title="한국피아이엠(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('44890'); return false;" title="한국피아이엠"> 한국피아이엠</a> </td>
<td class="textOverflow" title="자동차 신품 부품 제조업">자동차 신품 부품 제조업</td>
<td class="textOverflow" title="내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)">내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)</td>
<td class="txc">2025-04-04</td>
<td class="txc">12월</td>
<td class="txc" title="송준호">송준호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.pimkorea.com" target="_blank" title="http://www.pimkorea.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">대구광역시</td>
</tr>
<tr>
<td class="first" title="(주)에이유브랜즈"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48107'); return false;" title="에이유브랜즈"> 에이유브랜즈</a> </td>
<td class="textOverflow" title="섬유, 의복, 신발 및 가죽제품 소매업">섬유, 의복, 신발 및 가죽제품 소매업</td>
<td class="textOverflow" title="레인부츠, 스니커즈, 겨울화, 패션잡화 등">레인부츠, 스니커즈, 겨울화, 패션잡화 등</td>
<td class="txc">2025-04-03</td>
<td class="txc">12월</td>
<td class="txc" title="김지훈">김지훈</td>
<td class="txc">
<a class="btn ico homepage" href="http://aubrandz.irpage.co.kr" target="_blank" title="http://aubrandz.irpage.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="우양에이치씨(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('10197'); return false;" title="우양에이치씨"> 우양에이치씨</a> </td>
<td class="textOverflow" title="구조용 금속제품, 탱크 및 증기발생기 제조업">구조용 금속제품, 탱크 및 증기발생기 제조업</td>
<td class="textOverflow" title="화공 플랜트, 에너지 플랜트">화공 플랜트, 에너지 플랜트</td>
<td class="txc">2025-03-28</td>
<td class="txc">12월</td>
<td class="txc" title="김진태">김진태</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.wooyang.co.kr" target="_blank" title="http://www.wooyang.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)더즌"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('46286'); return false;" title="더즌"> 더즌</a> </td>
<td class="textOverflow" title="전기 통신업">전기 통신업</td>
<td class="textOverflow" title="디지털뱅킹 솔루션(B2B 금융 서비스)">디지털뱅킹 솔루션(B2B 금융 서비스)</td>
<td class="txc">2025-03-24</td>
<td class="txc">12월</td>
<td class="txc" title="조철한">조철한</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.dozn.co.kr/" target="_blank" title="http://www.dozn.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)심플랫폼"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('44453'); return false;" title="심플랫폼"> 심플랫폼</a> </td>
<td class="textOverflow" title="소프트웨어 개발 및 공급업">소프트웨어 개발 및 공급업</td>
<td class="textOverflow" title="NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)">NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)</td>
<td class="txc">2025-03-21</td>
<td class="txc">12월</td>
<td class="txc" title="임대근, 강태신">임대근..</td>
<td class="txc">
<a class="btn ico homepage" href="http://simplatform.com/" target="_blank" title="http://simplatform.com/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="주식회사 티엑스알로보틱스"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48481'); return false;" title="티엑스알로보틱스"> 티엑스알로보틱스</a> </td>
<td class="textOverflow" title="일반 목적용 기계 제조업">일반 목적용 기계 제조업</td>
<td class="textOverflow" title="물류자동화, 로봇자동화, AMR/AGV">물류자동화, 로봇자동화, AMR/AGV</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="엄인섭">엄인섭</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.txr.kr" target="_blank" title="http://www.txr.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)한텍"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('09807'); return false;" title="한텍"> 한텍</a> </td>
<td class="textOverflow" title="일반 목적용 기계 제조업">일반 목적용 기계 제조업</td>
<td class="textOverflow" title="열교환기 등 화공기기, 저장용 탱크">열교환기 등 화공기기, 저장용 탱크</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="김강식">김강식</td>
<td class="txc">
<a class="btn ico homepage" href="http://hantechltd.com" target="_blank" title="http://hantechltd.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">울산광역시</td>
</tr>
<tr>
<td class="first" title="한화플러스제5호기업인수목적(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('49839'); return false;" title="한화플러스제5호스팩"> 한화플러스제5호스팩</a> </td>
<td class="textOverflow" title="금융 지원 서비스업">금융 지원 서비스업</td>
<td class="textOverflow" title="-">-</td>
<td class="txc">2025-03-20</td>
<td class="txc">12월</td>
<td class="txc" title="김광후">김광후</td>
<td class="txc">
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)씨케이솔루션"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48037'); return false;" title="씨케이솔루션"> 씨케이솔루션</a> </td>
<td class="textOverflow" title="건축기술, 엔지니어링 및 관련 기술 서비스업">건축기술, 엔지니어링 및 관련 기술 서비스업</td>
<td class="textOverflow" title="드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업">드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업</td>
<td class="txc">2025-03-17</td>
<td class="txc">12월</td>
<td class="txc" title="김유곤, 안근표 (공동 대표이사)">김유곤..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.cksolution.co.kr/" target="_blank" title="http://www.cksolution.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="서울보증보험(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('03121'); return false;" title="서울보증보험"> 서울보증보험</a> </td>
<td class="textOverflow" title="보험업">보험업</td>
<td class="textOverflow" title="보증보험, 신용보험 등">보증보험, 신용보험 등</td>
<td class="txc">2025-03-14</td>
<td class="txc">12월</td>
<td class="txc" title="이명순">이명순</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.sgic.co.kr" target="_blank" title="http://www.sgic.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)에스엠씨지"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('46087'); return false;" title="에스엠씨지"> 에스엠씨지</a> </td>
<td class="textOverflow" title="유리 및 유리제품 제조업">유리 및 유리제품 제조업</td>
<td class="textOverflow" title="화장품 유리용기">화장품 유리용기</td>
<td class="txc">2025-03-07</td>
<td class="txc">12월</td>
<td class="txc" title="최승호">최승호</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.somangglass.co.kr" target="_blank" title="http://www.somangglass.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="엠디바이스 주식회사"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('22659'); return false;" title="엠디바이스"> 엠디바이스</a> </td>
<td class="textOverflow" title="전자부품 제조업">전자부품 제조업</td>
<td class="textOverflow" title="반도체기억장치">반도체기억장치</td>
<td class="txc">2025-03-07</td>
<td class="txc">12월</td>
<td class="txc" title="조호경">조호경</td>
<td class="txc">
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="대진첨단소재(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('39397'); return false;" title="대진첨단소재"> 대진첨단소재</a> </td>
<td class="textOverflow" title="플라스틱제품 제조업">플라스틱제품 제조업</td>
<td class="textOverflow" title="이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름">이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름</td>
<td class="txc">2025-03-06</td>
<td class="txc">12월</td>
<td class="txc" title="유성준, 장현주">유성준..</td>
<td class="txc">
<a class="btn ico homepage" href="http://daejin2019.com" target="_blank" title="http://daejin2019.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)에르코스 농업회사법인"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('43557'); return false;" title="에르코스"> 에르코스</a> </td>
<td class="textOverflow" title="도시락 및 식사용 조리식품 제조업">도시락 및 식사용 조리식품 제조업</td>
<td class="textOverflow" title="영유아식, 고령친화식품, 식물기반 대체식품">영유아식, 고령친화식품, 식물기반 대체식품</td>
<td class="txc">2025-02-28</td>
<td class="txc">12월</td>
<td class="txc" title="김슬기">김슬기</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.ercohs.com" target="_blank" title="http://www.ercohs.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">대전광역시</td>
</tr>
<tr>
<td class="first" title="(주)엘케이켐"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48950'); return false;" title="엘케이켐"> 엘케이켐</a> </td>
<td class="textOverflow" title="기타 화학제품 제조업">기타 화학제품 제조업</td>
<td class="textOverflow" title="반도체 소재(CP, PCP, DIS) 등">반도체 소재(CP, PCP, DIS) 등</td>
<td class="txc">2025-02-25</td>
<td class="txc">12월</td>
<td class="txc" title="이창엽">이창엽</td>
<td class="txc">
<a class="btn ico homepage" href="http://lkchem.co.kr" target="_blank" title="http://lkchem.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">충청남도</td>
</tr>
<tr>
<td class="first" title="(주)위너스"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('47996'); return false;" title="위너스"> 위너스</a> </td>
<td class="textOverflow" title="기타 전기장비 제조업">기타 전기장비 제조업</td>
<td class="textOverflow" title="배선기구(스위치, 콘센트, 멀티탭), 전기차 충전기(급속, 완속)">배선기구(스위치, 콘센트, 멀티탭), 전기차 충전기(급속, 완속)</td>
<td class="txc">2025-02-24</td>
<td class="txc">12월</td>
<td class="txc" title="김창성">김창성</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.wns21.co.kr/" target="_blank" title="http://www.wns21.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc"></td>
</tr>
<tr>
<td class="first" title="모티브링크(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('46348'); return false;" title="모티브링크"> 모티브링크</a> </td>
<td class="textOverflow" title="전자부품 제조업">전자부품 제조업</td>
<td class="textOverflow" title="EV용 Main Transformer, EV용 Line Filter">EV용 Main Transformer, EV용 Line Filter</td>
<td class="txc">2025-02-20</td>
<td class="txc">12월</td>
<td class="txc" title="김기한">김기한</td>
<td class="txc">
<a class="btn ico homepage" href="http://evpart.co.kr" target="_blank" title="http://evpart.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="동국생명과학(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('30381'); return false;" title="동국생명과학"> 동국생명과학</a> </td>
<td class="textOverflow" title="의약품 제조업">의약품 제조업</td>
<td class="textOverflow" title="조영제 완제 및 원료, 의료기기 유통">조영제 완제 및 원료, 의료기기 유통</td>
<td class="txc">2025-02-17</td>
<td class="txc">12월</td>
<td class="txc" title="박재원">박재원</td>
<td class="txc">
<a class="btn ico homepage" href="http://dkls.co.kr" target="_blank" title="http://dkls.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="오름테라퓨틱 주식회사"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('47583'); return false;" title="오름테라퓨틱"> 오름테라퓨틱</a> </td>
<td class="textOverflow" title="기초 의약물질 제조업">기초 의약물질 제조업</td>
<td class="textOverflow" title="항체약물접합체(ADC) 단백질 분해제(TPD) 연구 개발">항체약물접합체(ADC) 단백질 분해제(TPD) 연구 개발</td>
<td class="txc">2025-02-14</td>
<td class="txc">12월</td>
<td class="txc" title="이승주">이승주</td>
<td class="txc">
</td>
<td class="txc">대전광역시</td>
</tr>
<tr>
<td class="first" title="(주)동방메디컬"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('24055'); return false;" title="동방메디컬"> 동방메디컬</a> </td>
<td class="textOverflow" title="의료용 기기 제조업">의료용 기기 제조업</td>
<td class="textOverflow" title="필러, 한방침">필러, 한방침</td>
<td class="txc">2025-02-13</td>
<td class="txc">12월</td>
<td class="txc" title="김근식">김근식</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.dongbangmedical.co.kr/" target="_blank" title="http://www.dongbangmedical.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">충청남도</td>
</tr>
<tr>
<td class="first" title="(주)아이에스티이"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('21271'); return false;" title="아이에스티이"> 아이에스티이</a> </td>
<td class="textOverflow" title="반도체 제조업">반도체 제조업</td>
<td class="textOverflow" title="반도체 제조용 장비">반도체 제조용 장비</td>
<td class="txc">2025-02-12</td>
<td class="txc">12월</td>
<td class="txc" title="조창현">조창현</td>
<td class="txc">
<a class="btn ico homepage" href="http://iste.co.kr/" target="_blank" title="http://iste.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)엘지씨엔에스"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('06440'); return false;" title="LG씨엔에스"> LG씨엔에스</a> </td>
<td class="textOverflow" title="컴퓨터 프로그래밍, 시스템 통합 및 관리업">컴퓨터 프로그래밍, 시스템 통합 및 관리업</td>
<td class="textOverflow" title="컨설팅, 시스템 구축/운영, 토탈 아웃소싱 및 AI, 클라우드·스마트팩토리 등 IT신기술 기반의 DX사업">컨설팅, 시스템 구축/운영, 토탈 아웃소싱 및 AI, 클라우드·스마트팩토리 등 IT신기술 기반의 DX사업</td>
<td class="txc">2025-02-05</td>
<td class="txc">12월</td>
<td class="txc" title="현신균">현신균</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.lgcns.com" target="_blank" title="http://www.lgcns.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)아이지넷"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('46298'); return false;" title="아이지넷"> 아이지넷</a> </td>
<td class="textOverflow" title="기타 정보 서비스업">기타 정보 서비스업</td>
<td class="textOverflow" title="보험 서비스 어플리케이션, 기업용 보험 솔루션">보험 서비스 어플리케이션, 기업용 보험 솔루션</td>
<td class="txc">2025-02-04</td>
<td class="txc">12월</td>
<td class="txc" title="김창균, 김지태">김창균..</td>
<td class="txc">
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)피아이이"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('45245'); return false;" title="피아이이"> 피아이이</a> </td>
<td class="textOverflow" title="특수 목적용 기계 제조업">특수 목적용 기계 제조업</td>
<td class="textOverflow" title="AI 비전 솔루션 및 스마트팩토리 솔루션">AI 비전 솔루션 및 스마트팩토리 솔루션</td>
<td class="txc">2025-02-04</td>
<td class="txc">12월</td>
<td class="txc" title="최정일, 김현준">최정일..</td>
<td class="txc">
<a class="btn ico homepage" href="http://piegroup.co.kr" target="_blank" title="http://piegroup.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)삼양엔씨켐"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('48263'); return false;" title="삼양엔씨켐"> 삼양엔씨켐</a> </td>
<td class="textOverflow" title="기타 화학제품 제조업">기타 화학제품 제조업</td>
<td class="textOverflow" title="반도체 포토레지스트용 기초화합물(KrF PR용 소재, ArF PR용 소재, Wet Chemical)">반도체 포토레지스트용 기초화합물(KrF PR용 소재, ArF PR용 소재, Wet Chemical)</td>
<td class="txc">2025-02-03</td>
<td class="txc">12월</td>
<td class="txc" title="정회식">정회식</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.samyangncchem.com" target="_blank" title="http://www.samyangncchem.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)데이원컴퍼니"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('37316'); return false;" title="데이원컴퍼니"> 데이원컴퍼니</a> </td>
<td class="textOverflow" title="기타 교육기관">기타 교육기관</td>
<td class="textOverflow" title="성인대상 교육서비스">성인대상 교육서비스</td>
<td class="txc">2025-01-24</td>
<td class="txc">12월</td>
<td class="txc" title="이강민">이강민</td>
<td class="txc">
<a class="btn ico homepage" href="http://day1company.co.kr/" target="_blank" title="http://day1company.co.kr/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)아스테라시스"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('45095'); return false;" title="아스테라시스"> 아스테라시스</a> </td>
<td class="textOverflow" title="의료용 기기 제조업">의료용 기기 제조업</td>
<td class="textOverflow" title="피부 미용의료기기 제조, 판매">피부 미용의료기기 제조, 판매</td>
<td class="txc">2025-01-24</td>
<td class="txc">12월</td>
<td class="txc" title="서은택">서은택</td>
<td class="txc">
<a class="btn ico homepage" href="http://asterasys.com" target="_blank" title="http://asterasys.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)와이즈넛"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('09625'); return false;" title="와이즈넛"> 와이즈넛</a> </td>
<td class="textOverflow" title="소프트웨어 개발 및 공급업">소프트웨어 개발 및 공급업</td>
<td class="textOverflow" title="검색엔진, 챗봇, 클라우드서비스">검색엔진, 챗봇, 클라우드서비스</td>
<td class="txc">2025-01-24</td>
<td class="txc">12월</td>
<td class="txc" title="강용성">강용성</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.wisenut.com/" target="_blank" title="http://www.wisenut.com/"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)미트박스글로벌"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('47546'); return false;" title="미트박스"> 미트박스</a> </td>
<td class="textOverflow" title="기타 정보 서비스업">기타 정보 서비스업</td>
<td class="textOverflow" title="축산물 도소매 판매 및 중개">축산물 도소매 판매 및 중개</td>
<td class="txc">2025-01-23</td>
<td class="txc">12월</td>
<td class="txc" title="김기봉">김기봉</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.meatbox.co.kr" target="_blank" title="http://www.meatbox.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="유안타제17호기업인수목적 주식회사"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('49379'); return false;" title="유안타제17호스팩"> 유안타제17호스팩</a> </td>
<td class="textOverflow" title="금융 지원 서비스업">금융 지원 서비스업</td>
<td class="textOverflow" title="금융 지원 서비스업">금융 지원 서비스업</td>
<td class="txc">2025-01-23</td>
<td class="txc">12월</td>
<td class="txc" title="윤원도">윤원도</td>
<td class="txc">
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>

In [108]:
for a in soup.select('td'):
    print(a.get('title', a.text.strip()))

    if a.find('a'):
        if not a.find('a').get('href') == '#companysum':
            print(a.find('a').get('href'))

한국피아이엠(주)
자동차 신품 부품 제조업
내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)
2025-04-04
12월
송준호
홈페이지 보기
http://www.pimkorea.com
대구광역시
(주)에이유브랜즈
섬유, 의복, 신발 및 가죽제품 소매업
레인부츠, 스니커즈, 겨울화, 패션잡화 등
2025-04-03
12월
김지훈
홈페이지 보기
http://aubrandz.irpage.co.kr
서울특별시
우양에이치씨(주)
구조용 금속제품, 탱크 및 증기발생기 제조업
화공 플랜트, 에너지 플랜트
2025-03-28
12월
김진태
홈페이지 보기
http://www.wooyang.co.kr
경기도
(주)더즌
전기 통신업
디지털뱅킹 솔루션(B2B 금융 서비스)
2025-03-24
12월
조철한
홈페이지 보기
http://www.dozn.co.kr/
서울특별시
(주)심플랫폼
소프트웨어 개발 및 공급업
NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)
2025-03-21
12월
임대근, 강태신
홈페이지 보기
http://simplatform.com/
서울특별시
주식회사 티엑스알로보틱스
일반 목적용 기계 제조업
물류자동화, 로봇자동화, AMR/AGV
2025-03-20
12월
엄인섭
홈페이지 보기
http://www.txr.kr
경기도
(주)한텍
일반 목적용 기계 제조업
열교환기 등 화공기기, 저장용 탱크
2025-03-20
12월
김강식
홈페이지 보기
http://hantechltd.com
울산광역시
한화플러스제5호기업인수목적(주)
금융 지원 서비스업
-
2025-03-20
12월
김광후

서울특별시
(주)씨케이솔루션
건축기술, 엔지니어링 및 관련 기술 서비스업
드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업
2025-03-17
12월
김유곤, 안근표 (공동 대표이사)
홈페이지 보기
http://www.cksolution.co.kr/
경기도
서울보증보험(주)
보험업
보증보험, 신용보험 등
2025-03-14
12월
이명순
홈페이지 보기
http://www.sgic.co.kr
서울특별시
(주)에스엠씨지
유리 및 유리제품 제조업
화장품 유리용기
2025-03-07
12월
최승호
홈페이지 보기
http://www.somangglass.co.kr
경기도
엠디바이스 주식회사
전자부품 제조업
반도체기억장치
2025-03-07
12월
조호경

경기도
대진첨단소재(주)
플라스틱제품 제조업
이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름
2025-03-06
12월
유성준, 장현주
홈페이지 보기
http://daejin2019.com
서울특별시
(주)에르코스 농업회사법인
도시락 및 식사용 조리식품 제조업
영유아식, 고령친화식품, 식물기반 대체식품
2025-02-28
12월
김슬기
홈페이지 보기
http://www.ercohs.com
대전광역시
(주)엘케이켐
기타 화학제품 제조업
반도체 소재(CP, PCP, DIS) 등
2025-02-25
12월
이창엽
홈페이지 보기
http://lkchem.co.kr
충청남도
(주)위너스
기타 전기장비 제조업
배선기구(스위치, 콘센트, 멀티탭), 전기차 충전기(급속, 완속)
2025-02-24
12월
김창성
홈페이지 보기
http://www.wns21.co.kr/

모티브링크(주)
전자부품 제조업
EV용 Main Transformer, EV용 Line Filter
2025-02-20
12월
김기한
홈페이지 보기
http://evpart.co.kr
경기도
동국생명과학(주)
의약품 제조업
조영제 완제 및 원료, 의료기기 유통
2025-02-17
12월
박재원
홈페이지 보기
http://dkls.co.kr
서울특별시
오름테라퓨틱 주식회사
기초 의약물질 제조업
항체약물접합체(ADC) 단백질 분해제(TPD) 연구 개발
2025-02-14
12월
이승주

대전광역시
(주)동방메디컬
의료용 기기 제조업
필러, 한방침
2025-02-13
12월
김근식
홈페이지 보기
http://www.dongbangmedical.co.kr/
충청남도
(주)아이에스티이
반도체 제조업
반도체 제조용 장비
2025-02-12
12월
조창현
홈페이지 보기
http://iste.co.kr/
경기도
(주)엘지씨엔에스
컴퓨터 프로그래밍, 시스템 통합 및 관리업
컨설팅, 시스템 구축/운영, 토탈 아웃소싱 및 AI, 클라우드·스마트팩토리 등 IT신기술 기반의 DX사업
2025-02-05
12월
현신균
홈페이지 보기
http://www.lgcns.com
서울특별시
(주)아이지넷
기타 정보 서비스업
보험 서비스 어플리케이션, 기업용 보험 솔루션
2025-02-04
12월
김창균, 김지태

서울특별시
(주)피아이이
특수 목적용 기계 제조업
AI 비전 솔루션 및 스마트팩토리 솔루션
2025-02-04
12월
최정일, 김현준
홈페이지 보기
http://piegroup.co.kr
경기도
(주)삼양엔씨켐
기타 화학제품 제조업
반도체 포토레지스트용 기초화합물(KrF PR용 소재, ArF PR용 소재, Wet Chemical)
2025-02-03
12월
정회식
홈페이지 보기
http://www.samyangncchem.com
경기도
(주)데이원컴퍼니
기타 교육기관
성인대상 교육서비스
2025-01-24
12월
이강민
홈페이지 보기
http://day1company.co.kr/
서울특별시
(주)아스테라시스
의료용 기기 제조업
피부 미용의료기기 제조, 판매
2025-01-24
12월
서은택
홈페이지 보기
http://asterasys.com
서울특별시
(주)와이즈넛
소프트웨어 개발 및 공급업
검색엔진, 챗봇, 클라우드서비스
2025-01-24
12월
강용성
홈페이지 보기
http://www.wisenut.com/
경기도
(주)미트박스글로벌
기타 정보 서비스업
축산물 도소매 판매 및 중개
2025-01-23
12월
김기봉
홈페이지 보기
http://www.meatbox.co.kr
서울특별시
유안타제17호기업인수목적 주식회사
금융 지원 서비스업
금융 지원 서비스업
2025-01-23
12월
윤원도

서울특별시
주식회사 블랙야크아이앤씨
신발 및 신발 부분품 제조업
산업용 안전화, 안전복 및 안전용품
2025-01-21
12월
김태효
홈페이지 보기
http://www.blackyakinc.com
서울특별시
오션스바이오 주식회사
의료용 기기 제조업
전자약
2025-01-14
12월
이현웅

경상남도
엠에프씨(주)
기초 의약물질 제조업
원료의약품(API) 및 핵심소재
2024-12-26
12월
황성관, 서기형(각자 대표이사)
홈페이지 보기
http://www.mfcglobal.co.kr
경기도
주식회사 파인메딕스
의료용 기기 제조업
인젝터, 스네어, 나이프, 포셉 등 내시경용 시술기구
2024-12-26
12월
전성우, 김성철

대구광역시
쓰리에이로직스(주)
반도체 제조업
NFC/IoT SoC 및 모듈
2024-12-24
12월
박광범, 이평한
홈페이지 보기
http://www.3alogics.com/
경기도
(주)지에스피앤엘
기타 금융업
지주회사
2024-12-23
12월
김원식
홈페이지 보기
http://www.gspnl.com
서울특별시
신한제14호기업인수목적 주식회사
금융 지원 서비스업
금융 지원 서비스업
2024-12-23
12월
정우주

서울특별시
(주)유비씨
소프트웨어 개발 및 공급업
디지털트윈 구현 플랫폼(Flexing CPS, Flexing DT 등)
2024-12-23
12월
조규종
홈페이지 보기
http://uvc.co.kr
경기도
(주)창대정밀
특수 목적용 기계 제조업
정밀금형 및 사출품
2024-12-23
12월
박제현, 박순민
홈페이지 보기
http://www.i-changdae.com/
경기도
(주)듀켐바이오
의약품 제조업
방사성의약품
2024-12-20
12월
김상우
홈페이지 보기
http://www.duchembio.com
서울특별시
키움제10호기업인수목적 주식회사
금융 지원 서비스업
기업 인수합병
2024-12-20
12월
김대식

서울특별시
(주)에스지헬스케어
의료용 기기 제조업
의료용 영상진단기기
2024-12-19
12월
김정수
홈페이지 보기
http://sghealthcare.com/
경기도
온코닉테라퓨틱스(주)
자연과학 및 공학 연구개발업
자큐보정(Zastaprazan, 소화기질환 신약), Nesuparib(표적항암제 신약)
2024-12-19
12월
김존
홈페이지 보기
http://onconic.co.kr
서울특별시
주식회사 온코크로스
자연과학 및 공학 연구개발업
AI플랫폼 기반 신약개발 용역서비스
2024-12-18
12월
김이랑, 강지훈 (각자대표)
홈페이지 보기
http://www.oncocross.com/
서울특별시
(주)벡트
영상 및 음향기기 제조업
프로젝터, 전자칠판, 전자교탁 및 관련 영상 소프트웨어, 콘텐츠 등
2024-12-16
12월
유창수
홈페이지 보기
http://vect.co.kr
서울특별시
주식회사 엠앤씨솔루션
특수 목적용 기계 제조업
방위산업용 유압식/전기식 부품 및 시스템
2024-12-16
12월
김병근
홈페이지 보기
http://www.mncsolution.com
경상남도
(주)셀로맥스사이언스
기타 식품 제조업
건강기능식품
2024-12-13
12월
서정민
홈페이지 보기
http://cellromax.kr/
경기도
주식회사 에이엠시지
의료용 기기 제조업
심자계
2024-12-13
12월
서용성
홈페이지 보기
http://www.amcg.kr/
서울특별시
케이비제31호기업인수목적(주)
금융 지원 서비스업
기업인수합병
2024-12-12
12월
김형철

서울특별시
키움제11호기업인수목적 주식회사
금융 지원 서비스업
기업 인수합병
2024-12-11
12월
조선희

서울특별시
케이비발해인프라투융자회사
신탁업 및 집합투자업

2024-11-29
12월
법인이사 케이비자산운용(주)

서울특별시
디비금융제13호기업인수목적 주식회사
기타 금융업
기업인수 및 합병
2024-11-28
12월
양준석

서울특별시
교보17호기업인수목적 주식회사
금융 지원 서비스업
기업인수합병
2024-11-21
12월
장정훈

서울특별시
대신밸런스제19호기업인수목적(주)
금융 지원 서비스업
기업 인수 및 합병
2024-11-20
12월
임병완

서울특별시
(주)위츠
전자부품 제조업
무선충전소재, 부품 제조
2024-11-20
12월
김응태
홈페이지 보기
http://www.ewits.co.kr/kr/
경기도
(주)유디엠텍
소프트웨어 개발 및 공급업
PLC eXpert, OPTRA Black-box, OPTRA Tracker
2024-11-20
12월
왕지남
홈페이지 보기
http://www.udmtek.com
경기도
알에프시스템즈(주)
기타 금속 가공제품 제조업
방산제품(레이더시스템, 안테나시스템, 환경제어시스템 등)
2024-11-19
12월
한기우
홈페이지 보기
http://www.rf-systems.co.kr/
경기도
(주)사이냅소프트
소프트웨어 개발 및 공급업
웹 기반 문서뷰어, 문서필터, 웹 에디터 등
2024-11-19
12월
전경헌
홈페이지 보기
http:///www.synapsoft.co.kr
서울특별시
하나34호기업인수목적 주식회사
금융 지원 서비스업
기업인수목적
2024-11-19
12월
송하용

서울특별시
주식회사 에스켐
기타 화학제품 제조업
OLED 유기화합물 등
2024-11-18
12월
염호영
홈페이지 보기
http://www.s-chem.co.kr
충청북도
(주)엠오티
특수 목적용 기계 제조업
이차전지 제조 자동화 설비
2024-11-18
12월
마점래
홈페이지 보기
http://www.motfa.com
경상남도
신한제15호기업인수목적 주식회사
금융 지원 서비스업
금융 지원 서비스업
2024-11-15
12월
연오흠

서울특별시
(주)쓰리빌리언
의료용 기기 제조업
유전체 분석 기반 희귀 유전질환 진단 검사 서비스
2024-11-14
12월
금창원

서울특별시
(주)닷밀
영화, 비디오물, 방송프로그램 제작 및 배급업
실감미디어 콘텐츠 및 시설 구축, 전시 및 테마파크 운영
2024-11-13
12월
정해운

서울특별시
(주)노머스
창작 및 예술관련 서비스업
공연기획 및 MD, Fromm 플랫폼
2024-11-12
12월
김영준
홈페이지 보기
http://knowmerce.com
서울특별시
㈜에어레인
일반 목적용 기계 제조업
기체분리막 모듈 및 시스템
2024-11-08
12월
하성용
홈페이지 보기
http://www.airrane.com
충청북도
(주)토모큐브
사진장비 및 광학기기 제조업
홀로토모그래피 HT-X1, HT-2H
2024-11-07
12월
박용근
홈페이지 보기
http://www.tomocube.com
대전광역시
주식회사 더본코리아
상품 종합 도매업
프랜차이즈
2024-11-06
12월
백종원, 강석원
홈페이지 보기
http://www.theborn.co.kr/
서울특별시
주식회사 에이치이엠파마
자연과학 및 공학 연구개발업
맞춤형 헬스케어, LBP 디스커버리 플랫폼
2024-11-05
12월
지요셉
홈페이지 보기
http://www.hempharma.bio
경기도
주식회사 에이럭스
그외 기타 제품 제조업
교육용 드론/로봇 및 코딩 콘텐츠
2024-11-01
12월
이치헌
홈페이지 보기
http://www.aluxonline.com
서울특별시
(주)탑런토탈솔루션
전자부품 제조업
전장디스플레이 및 pOLED 부품
2024-11-01
12월
각 자 대표이사 박영근, 손종술
홈페이지 보기
http://toprun.co.kr/
경상북도
(주)성우
일차전지 및 이차전지 제조업
이차전지 부품(2170 Topcap Ass'y, S4623 등), 자동차 전장부품(Motor Housing, EV Relay 등)
2024-10-31
12월
박종헌
홈페이지 보기
http://www.e-sungwoo.co.kr
경상북도
유진기업인수목적11호 주식회사
금융 지원 서비스업
기업인수합병
2024-10-31
12월
박홍식

서울특별시
(주)타조엔터테인먼트
창작 및 예술관련 서비스업
공연기획, 방송·공연
2024-10-30
12월
이성호
홈페이지 보기
http://tajoyent.com/
서울특별시
주식회사 클로봇
소프트웨어 개발 및 공급업
로봇 소프트웨어(카멜레온, 크롬스)
2024-10-28
12월
각자 대표이사 김창구, 김경필
홈페이지 보기
http://clobot.co.kr
경기도
에이치엔에스하이텍(주)
전자부품 제조업
ACF(이방성전도필름), 수정진동자/수정발진기
2024-10-25
12월
김정희
홈페이지 보기
http://www.hnshightech.com/
대전광역시
(주)웨이비스
반도체 제조업
GaN RF 칩, 패키지 트랜지스터, 모듈 등
2024-10-25
12월
한민석
홈페이지 보기
http://www.wavice.com/
경기도
(주)씨메스
특수 목적용 기계 제조업
AI 기반 로봇 솔루션 및 3D 비전 솔루션
2024-10-24
12월
이성호
홈페이지 보기
http://www.cmesrobotics.ai/
서울특별시
(주)한켐
기초 화학물질 제조업
OLED 발광층 소재 등
2024-10-22
12월
이상조
홈페이지 보기
http://www.hanchem.net
대전광역시
루미르 주식회사
항공기,우주선 및 부품 제조업
인공위성 시스템 및 전장품, 위성 영상 및 정보
2024-10-21
12월
남명용
홈페이지 보기
http://www.lumir.space
경기도
와이제이링크(주)
특수 목적용 기계 제조업
SMT(PCB 표면실장) 이송 및 추적장비 등 스마트 공정장비
2024-10-18
12월
박순일
홈페이지 보기
http://www.yjlink.com
대구광역시
인스피언(주)
소프트웨어 개발 및 공급업
SAP 보안 솔루션, SAP PO/CPI 컨설팅, EDI SaaS 플랫폼
2024-10-18
12월
최정규
홈페이지 보기
http://www.inspien.co.kr
서울특별시
주식회사 셀비온
의약품 제조업
셀비온그린주, 셀비온메브로페닌주, 도페정 등
2024-10-16
12월
김권
홈페이지 보기
http://cellbion.co.kr
서울특별시
제닉스(주)
특수 목적용 기계 제조업
Stocker, AGV/AMR
2024-09-30
12월
배성관
홈페이지 보기
http://www.zenixkorea.co.kr/
충청남도
(주)차이커뮤니케이션
광고업
광고대행, 광고물 작성
2024-09-27
12월
최영섭
홈페이지 보기
http://www.artistchai.co.kr
서울특별시
한화비전(주)
기타 금융업
비금융지주회사
2024-09-27
12월
안순홍
홈페이지 보기
http://www.hanwhavision.com
경기도
케이비제30호기업인수목적(주)
금융 지원 서비스업
기업인수합병
2024-09-25
12월
박홍진

서울특별시
(주)아이언디바이스
반도체 제조업
스마트폰용 오디오 앰프 반도체 Soc
2024-09-23
12월
박기태
홈페이지 보기
http://www.irondevice.com/index.html
서울특별시
미래에셋비전기업인수목적7호 주식회사
금융 지원 서비스업
기업인수합병
2024-09-11
12월
송우영

서울특별시
(주)아이비젼웍스
특수 목적용 기계 제조업
이차전지 검사시스템 및 검사시스템 설치셋업용역
2024-09-03
12월
길기재
홈페이지 보기
http://www.ivw.co.kr/kor/main/
대전광역시
(주)아이스크림미디어
소프트웨어 개발 및 공급업
교육출판, 커머스, 연수
2024-08-30
12월
허주환, 현준우(각자대표)
홈페이지 보기
http://www.i-screammedia.com
경기도
이엔셀(주)
기초 의약물질 제조업
첨단바이오의약품 위탁개발생산(CDMO) 서비스 / 차세대 세포,유전자 치료제
2024-08-23
12월
장종욱
홈페이지 보기
http://www.encellinc.com/
서울특별시
(주)엠83
영화, 비디오물, 방송프로그램 제작 및 배급업
VFX
2024-08-22
12월
정성진
홈페이지 보기
http://m83.co.kr
서울특별시
대신밸런스제18호기업인수목적(주)
금융 지원 서비스업
금융 지원 서비스업
2024-08-22
12월
문병식

서울특별시
(주)티디에스팜
의약품 제조업
경피약물전달시스템(습포제, 첩부제)
2024-08-21
12월
김철준
홈페이지 보기
http://www.tdspharm.com
경기도
(주)넥스트바이오메디컬
의료용 기기 제조업
내시경용 지혈재, 혈관색전 미립구
2024-08-20
12월
이돈행
홈페이지 보기
http://www.nextbiomedical.co.kr
인천광역시
(주)케이쓰리아이
소프트웨어 개발 및 공급업
XR 실감형콘텐츠
2024-08-20
12월
이재영
홈페이지 보기
http://www.k3i.co.kr
대전광역시
전진건설로봇(주)
특수 목적용 기계 제조업
콘크리트 펌프카
2024-08-19
12월
고현국

충청북도
(주)유라클
소프트웨어 개발 및 공급업
모바일 앱 개발 플랫폼
2024-08-16
12월
조준희
홈페이지 보기
http://www.uracle.co.kr/
서울특별시
교보16호기업인수목적 주식회사
금융 지원 서비스업
기업인수합병
2024-08-13
12월
정시화

서울특별시

In [75]:
industry=[]
for ind in soup.select('td.textOverflow'):
    industry.append(ind.text)
industry

['자동차 신품 부품 제조업',
 '내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)',
 '섬유, 의복, 신발 및 가죽제품 소매업',
 '레인부츠, 스니커즈, 겨울화, 패션잡화 등',
 '구조용 금속제품, 탱크 및 증기발생기 제조업',
 '화공 플랜트, 에너지 플랜트',
 '전기 통신업',
 '디지털뱅킹 솔루션(B2B 금융 서비스)',
 '소프트웨어 개발 및 공급업',
 'NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)',
 '일반 목적용 기계 제조업',
 '물류자동화, 로봇자동화, AMR/AGV',
 '일반 목적용 기계 제조업',
 '열교환기 등 화공기기, 저장용 탱크',
 '금융 지원 서비스업',
 '-',
 '건축기술, 엔지니어링 및 관련 기술 서비스업',
 '드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업',
 '보험업',
 '보증보험, 신용보험 등',
 '유리 및 유리제품 제조업',
 '화장품 유리용기',
 '전자부품 제조업',
 '반도체기억장치',
 '플라스틱제품 제조업',
 '이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름',
 '도시락 및 식사용 조리식품 제조업',
 '영유아식, 고령친화식품, 식물기반 대체식품',
 '기타 화학제품 제조업',
 '반도체 소재(CP, PCP, DIS) 등',
 '기타 전기장비 제조업',
 '배선기구(스위치, 콘센트, 멀티탭), 전기차 충전기(급속, 완속)',
 '전자부품 제조업',
 'EV용 Main Transformer, EV용 Line Filter',
 '의약품 제조업',
 '조영제 완제 및 원료, 의료기기 유통',
 '기초 의약물질 제조업',
 '항체약물접합체(ADC) 단백질 분해제(TPD) 연구 개발',
 '의료용 기기 제조업',
 '필러, 한방침',
 '반도체 제조업',
 '반도체 제조용 장비',
 '컴퓨터 프로그래밍, 시스템 통합 및 관리업',
 '컨설팅, 시스템 구축/운영, 토탈 아웃소싱 및 AI, 클라우드·스마트팩토리 등 IT신기술 기반의 DX사업',
 '기타 정보 서비스업',
 '보험 서비스 어플리케이션, 기업용 보험 솔루션',
 '특수 목적용 기계 제조업',
 'AI 비전 솔루션 및 스마트팩토리 솔루션',
 '기타 화학제품 제조업',
 '반도체 포토레지스트용 기초화합물(KrF PR용 소재, ArF PR용 소재, Wet Chemical)',
 '기타 교육기관',
 '성인대상 교육서비스',
 '의료용 기기 제조업',
 '피부 미용의료기기 제조, 판매',
 '소프트웨어 개발 및 공급업',
 '검색엔진, 챗봇, 클라우드서비스',
 '기타 정보 서비스업',
 '축산물 도소매 판매 및 중개',
 '금융 지원 서비스업',
 '금융 지원 서비스업',
 '신발 및 신발 부분품 제조업',
 '산업용 안전화, 안전복 및 안전용품',
 '의료용 기기 제조업',
 '전자약',
 '기초 의약물질 제조업',
 '원료의약품(API) 및 핵심소재',
 '의료용 기기 제조업',
 '인젝터, 스네어, 나이프, 포셉 등 내시경용 시술기구',
 '반도체 제조업',
 'NFC/IoT SoC 및 모듈',
 '기타 금융업',
 '지주회사',
 '금융 지원 서비스업',
 '금융 지원 서비스업',
 '소프트웨어 개발 및 공급업',
 '디지털트윈 구현 플랫폼(Flexing CPS, Flexing DT 등)',
 '특수 목적용 기계 제조업',
 '정밀금형 및 사출품',
 '의약품 제조업',
 '방사성의약품',
 '금융 지원 서비스업',
 '기업 인수합병',
 '의료용 기기 제조업',
 '의료용 영상진단기기',
 '자연과학 및 공학 연구개발업',
 '자큐보정(Zastaprazan, 소화기질환 신약), Nesuparib(표적항암제 신약)',
 '자연과학 및 공학 연구개발업',
 'AI플랫폼 기반 신약개발 용역서비스',
 '영상 및 음향기기 제조업',
 '프로젝터, 전자칠판, 전자교탁 및 관련 영상 소프트웨어, 콘텐츠 등',
 '특수 목적용 기계 제조업',
 '방위산업용 유압식/전기식 부품 및 시스템',
 '기타 식품 제조업',
 '건강기능식품',
 '의료용 기기 제조업',
 '심자계',
 '금융 지원 서비스업',
 '기업인수합병',
 '금융 지원 서비스업',
 '기업 인수합병',
 '신탁업 및 집합투자업',
 '',
 '기타 금융업',
 '기업인수 및 합병',
 '금융 지원 서비스업',
 '기업인수합병',
 '금융 지원 서비스업',
 '기업 인수 및 합병',
 '전자부품 제조업',
 '무선충전소재, 부품 제조',
 '소프트웨어 개발 및 공급업',
 'PLC eXpert, OPTRA Black-box, OPTRA Tracker',
 '기타 금속 가공제품 제조업',
 '방산제품(레이더시스템, 안테나시스템, 환경제어시스템 등)',
 '소프트웨어 개발 및 공급업',
 '웹 기반 문서뷰어, 문서필터, 웹 에디터 등',
 '금융 지원 서비스업',
 '기업인수목적',
 '기타 화학제품 제조업',
 'OLED 유기화합물 등',
 '특수 목적용 기계 제조업',
 '이차전지 제조 자동화 설비',
 '금융 지원 서비스업',
 '금융 지원 서비스업',
 '의료용 기기 제조업',
 '유전체 분석 기반 희귀 유전질환 진단 검사 서비스',
 '영화, 비디오물, 방송프로그램 제작 및 배급업',
 '실감미디어 콘텐츠 및 시설 구축, 전시 및 테마파크 운영',
 '창작 및 예술관련 서비스업',
 '공연기획 및 MD, Fromm 플랫폼',
 '일반 목적용 기계 제조업',
 '기체분리막 모듈 및 시스템',
 '사진장비 및 광학기기 제조업',
 '홀로토모그래피 HT-X1, HT-2H',
 '상품 종합 도매업',
 '프랜차이즈',
 '자연과학 및 공학 연구개발업',
 '맞춤형 헬스케어, LBP 디스커버리 플랫폼',
 '그외 기타 제품 제조업',
 '교육용 드론/로봇 및 코딩 콘텐츠',
 '전자부품 제조업',
 '전장디스플레이 및 pOLED 부품',
 '일차전지 및 이차전지 제조업',
 "이차전지 부품(2170 Topcap Ass'y, S4623 등), 자동차 전장부품(Motor Housing, EV Relay 등)",
 '금융 지원 서비스업',
 '기업인수합병',
 '창작 및 예술관련 서비스업',
 '공연기획, 방송·공연',
 '소프트웨어 개발 및 공급업',
 '로봇 소프트웨어(카멜레온, 크롬스)',
 '전자부품 제조업',
 'ACF(이방성전도필름), 수정진동자/수정발진기',
 '반도체 제조업',
 'GaN RF 칩, 패키지 트랜지스터, 모듈 등',
 '특수 목적용 기계 제조업',
 'AI 기반 로봇 솔루션 및 3D 비전 솔루션',
 '기초 화학물질 제조업',
 'OLED 발광층 소재 등',
 '항공기,우주선 및 부품 제조업',
 '인공위성 시스템 및 전장품, 위성 영상 및 정보',
 '특수 목적용 기계 제조업',
 'SMT(PCB 표면실장) 이송 및 추적장비 등 스마트 공정장비',
 '소프트웨어 개발 및 공급업',
 'SAP 보안 솔루션, SAP PO/CPI 컨설팅, EDI SaaS 플랫폼',
 '의약품 제조업',
 '셀비온그린주, 셀비온메브로페닌주, 도페정 등',
 '특수 목적용 기계 제조업',
 'Stocker, AGV/AMR',
 '광고업',
 '광고대행, 광고물 작성',
 '기타 금융업',
 '비금융지주회사',
 '금융 지원 서비스업',
 '기업인수합병',
 '반도체 제조업',
 '스마트폰용 오디오 앰프 반도체 Soc',
 '금융 지원 서비스업',
 '기업인수합병',
 '특수 목적용 기계 제조업',
 '이차전지 검사시스템 및 검사시스템 설치셋업용역',
 '소프트웨어 개발 및 공급업',
 '교육출판, 커머스, 연수',
 '기초 의약물질 제조업',
 '첨단바이오의약품 위탁개발생산(CDMO) 서비스 / 차세대 세포,유전자 치료제',
 '영화, 비디오물, 방송프로그램 제작 및 배급업',
 'VFX',
 '금융 지원 서비스업',
 '금융 지원 서비스업',
 '의약품 제조업',
 '경피약물전달시스템(습포제, 첩부제)',
 '의료용 기기 제조업',
 '내시경용 지혈재, 혈관색전 미립구',
 '소프트웨어 개발 및 공급업',
 'XR 실감형콘텐츠',
 '특수 목적용 기계 제조업',
 '콘크리트 펌프카',
 '소프트웨어 개발 및 공급업',
 '모바일 앱 개발 플랫폼',
 '금융 지원 서비스업',
 '기업인수합병']

In [54]:
for etc in soup.select('tr.first>td.txc'):
    if etc.find('a'):
        #print("a 태그 포함:", etc.text.strip())
        print(etc.find('a').get('href'))
    else:
        print(etc.text)

2025-04-04
12월
송준호
http://www.pimkorea.com
대구광역시

In [96]:
for etc in soup.select('td'):
    if etc.find('a'):
        print(etc.find('a').get('href'))

#companysum
http://www.pimkorea.com
#companysum
http://aubrandz.irpage.co.kr
#companysum
http://www.wooyang.co.kr
#companysum
http://www.dozn.co.kr/
#companysum
http://simplatform.com/
#companysum
http://www.txr.kr
#companysum
http://hantechltd.com
#companysum
#companysum
http://www.cksolution.co.kr/
#companysum
http://www.sgic.co.kr
#companysum
http://www.somangglass.co.kr
#companysum
#companysum
http://daejin2019.com
#companysum
http://www.ercohs.com
#companysum
http://lkchem.co.kr
#companysum
http://www.wns21.co.kr/
#companysum
http://evpart.co.kr
#companysum
http://dkls.co.kr
#companysum
#companysum
http://www.dongbangmedical.co.kr/
#companysum
http://iste.co.kr/
#companysum
http://www.lgcns.com
#companysum
#companysum
http://piegroup.co.kr
#companysum
http://www.samyangncchem.com
#companysum
http://day1company.co.kr/
#companysum
http://asterasys.com
#companysum
http://www.wisenut.com/
#companysum
http://www.meatbox.co.kr
#companysum
#companysum
http://www.blackyakinc.com
#companysum
#companysum
http://www.mfcglobal.co.kr
#companysum
#companysum
http://www.3alogics.com/
#companysum
http://www.gspnl.com
#companysum
#companysum
http://uvc.co.kr
#companysum
http://www.i-changdae.com/
#companysum
http://www.duchembio.com
#companysum
#companysum
http://sghealthcare.com/
#companysum
http://onconic.co.kr
#companysum
http://www.oncocross.com/
#companysum
http://vect.co.kr
#companysum
http://www.mncsolution.com
#companysum
http://cellromax.kr/
#companysum
http://www.amcg.kr/
#companysum
#companysum
#companysum
#companysum
#companysum
#companysum
#companysum
http://www.ewits.co.kr/kr/
#companysum
http://www.udmtek.com
#companysum
http://www.rf-systems.co.kr/
#companysum
http:///www.synapsoft.co.kr
#companysum
#companysum
http://www.s-chem.co.kr
#companysum
http://www.motfa.com
#companysum
#companysum
#companysum
#companysum
http://knowmerce.com
#companysum
http://www.airrane.com
#companysum
http://www.tomocube.com
#companysum
http://www.theborn.co.kr/
#companysum
http://www.hempharma.bio
#companysum
http://www.aluxonline.com
#companysum
http://toprun.co.kr/
#companysum
http://www.e-sungwoo.co.kr
#companysum
#companysum
http://tajoyent.com/
#companysum
http://clobot.co.kr
#companysum
http://www.hnshightech.com/
#companysum
http://www.wavice.com/
#companysum
http://www.cmesrobotics.ai/
#companysum
http://www.hanchem.net
#companysum
http://www.lumir.space
#companysum
http://www.yjlink.com
#companysum
http://www.inspien.co.kr
#companysum
http://cellbion.co.kr
#companysum
http://www.zenixkorea.co.kr/
#companysum
http://www.artistchai.co.kr
#companysum
http://www.hanwhavision.com
#companysum
#companysum
http://www.irondevice.com/index.html
#companysum
#companysum
http://www.ivw.co.kr/kor/main/
#companysum
http://www.i-screammedia.com
#companysum
http://www.encellinc.com/
#companysum
http://m83.co.kr
#companysum
#companysum
http://www.tdspharm.com
#companysum
http://www.nextbiomedical.co.kr
#companysum
http://www.k3i.co.kr
#companysum
#companysum
http://www.uracle.co.kr/
#companysum

# 찾을 자료를 1개씩 찾아보기

In [145]:
soup.select("tbody > tr")[0].select('td:nth-child(1)')

[<td class="first" title="한국피아이엠(주)"><img alt="코스닥" class="vmiddle legend" src="/images/common/icn_t_ko.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('44890'); return false;" title="한국피아이엠"> 한국피아이엠</a> </td>]

In [146]:
#주식종목
soup.select("tbody > tr")[0].select_one('td:nth-child(1) > img')['alt']

'코스닥'

In [148]:
#회사이름
soup.select("tbody > tr")[0].select_one('td:nth-child(1) > a')['title']

'한국피아이엠'

In [151]:
#종목코드
soup.select("tbody > tr")[0].select_one('td:nth-child(1) > a')['onclick'].split("'")[1]

'44890'

In [156]:
#업종
soup.select("tbody > tr")[0].select_one('td:nth-child(2)')['title']

'자동차 신품 부품 제조업'

In [157]:
#주요제품
soup.select("tbody > tr")[0].select_one('td:nth-child(3)')['title']

'내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)'

In [160]:
#상장일
soup.select("tbody > tr")[0].select_one('td:nth-child(4)').text

'2025-04-04'

In [161]:
#결산월
soup.select("tbody > tr")[0].select_one('td:nth-child(5)').text

'12월'

In [162]:
#대표자명
soup.select("tbody > tr")[0].select_one('td:nth-child(6)')['title']

'송준호'

In [165]:
#홈페이지(url)
soup.select("tbody > tr")[0].select_one('td:nth-child(7) > a')['href']

'http://www.pimkorea.com'

In [166]:
#지역
soup.select("tbody > tr")[0].select_one('td:nth-child(8)').text

'대구광역시'

In [180]:
#전체페이지
total_page=int(soup.select_one('.info.type-00 > em').text.replace(',','')) // 100 +1
total_page

28

In [184]:
# 컬럼명
columns = soup.select_one('table')['summary'].split(", ")
columns.insert(0,'주식종목')
columns.insert(2,'종목코드')

In [185]:
columns

['주식종목', '회사명', '종목코드', '업종', '주요제품', '상장일', '결산월', '대표자명', '홈페이지', '지역']

# 코드 합쳐서 1페이지 정보 모두 추출하기

In [188]:
for i in range(100):
    tr= soup.select("tbody > tr")[i]
    stock_type= tr.select_one('td:nth-child(1) > img')['alt']
    company_name= tr.select_one('td:nth-child(1) > a')['title']
    stock_code= tr.select_one('td:nth-child(1) > a')['onclick'].split("'")[1]
    business_type=tr.select_one('td:nth-child(2)')['title']
    product=tr.select_one('td:nth-child(3)')['title']
    resi_date=tr.select_one('td:nth-child(4)').text
    settlement=tr.select_one('td:nth-child(5)').text
    ceo=tr.select_one('td:nth-child(6)')['title']
    homepage=tr.select_one('td:nth-child(7) > a')['href'] if tr.select_one('td:nth-child(7) > a') !=None else ""
    region=tr.select_one('td:nth-child(8)').text
    print(stock_type,company_name,stock_code,business_type,product,resi_date,settlement,ceo,homepage,region)

코스닥 한국피아이엠 44890 자동차 신품 부품 제조업 내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스) 2025-04-04 12월 송준호 http://www.pimkorea.com 대구광역시
코스닥 에이유브랜즈 48107 섬유, 의복, 신발 및 가죽제품 소매업 레인부츠, 스니커즈, 겨울화, 패션잡화 등 2025-04-03 12월 김지훈 http://aubrandz.irpage.co.kr 서울특별시
코스닥 우양에이치씨 10197 구조용 금속제품, 탱크 및 증기발생기 제조업 화공 플랜트, 에너지 플랜트 2025-03-28 12월 김진태 http://www.wooyang.co.kr 경기도
코스닥 더즌 46286 전기 통신업 디지털뱅킹 솔루션(B2B 금융 서비스) 2025-03-24 12월 조철한 http://www.dozn.co.kr/ 서울특별시
코스닥 심플랫폼 44453 소프트웨어 개발 및 공급업 NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영) 2025-03-21 12월 임대근, 강태신 http://simplatform.com/ 서울특별시
코스닥 티엑스알로보틱스 48481 일반 목적용 기계 제조업 물류자동화, 로봇자동화, AMR/AGV 2025-03-20 12월 엄인섭 http://www.txr.kr 경기도
코스닥 한텍 09807 일반 목적용 기계 제조업 열교환기 등 화공기기, 저장용 탱크 2025-03-20 12월 김강식 http://hantechltd.com 울산광역시
코스닥 한화플러스제5호스팩 49839 금융 지원 서비스업 - 2025-03-20 12월 김광후  서울특별시
유가증권 씨케이솔루션 48037 건축기술, 엔지니어링 및 관련 기술 서비스업 드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업 2025-03-17 12월 김유곤, 안근표 (공동 대표이사) http://www.cksolution.co.kr/ 경기도
유가증권 서울보증보험 03121 보험업 보증보험, 신용보험 등 2025-03-14 12월 이명순 http://www.sgic.co.kr 서울특별시
코스닥 에스엠씨지 46087 유리 및 유리제품 제조업 화장품 유리용기 2025-03-07 12월 최승호 http://www.somangglass.co.kr 경기도
코스닥 엠디바이스 22659 전자부품 제조업 반도체기억장치 2025-03-07 12월 조호경  경기도
코스닥 대진첨단소재 39397 플라스틱제품 제조업 이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름 2025-03-06 12월 유성준, 장현주 http://daejin2019.com 서울특별시
코스닥 에르코스 43557 도시락 및 식사용 조리식품 제조업 영유아식, 고령친화식품, 식물기반 대체식품 2025-02-28 12월 김슬기 http://www.ercohs.com 대전광역시
코스닥 엘케이켐 48950 기타 화학제품 제조업 반도체 소재(CP, PCP, DIS) 등 2025-02-25 12월 이창엽 http://lkchem.co.kr 충청남도
코스닥 위너스 47996 기타 전기장비 제조업 배선기구(스위치, 콘센트, 멀티탭), 전기차 충전기(급속, 완속) 2025-02-24 12월 김창성 http://www.wns21.co.kr/
코스닥 모티브링크 46348 전자부품 제조업 EV용 Main Transformer, EV용 Line Filter 2025-02-20 12월 김기한 http://evpart.co.kr 경기도
코스닥 동국생명과학 30381 의약품 제조업 조영제 완제 및 원료, 의료기기 유통 2025-02-17 12월 박재원 http://dkls.co.kr 서울특별시
코스닥 오름테라퓨틱 47583 기초 의약물질 제조업 항체약물접합체(ADC) 단백질 분해제(TPD) 연구 개발 2025-02-14 12월 이승주  대전광역시
코스닥 동방메디컬 24055 의료용 기기 제조업 필러, 한방침 2025-02-13 12월 김근식 http://www.dongbangmedical.co.kr/ 충청남도
코스닥 아이에스티이 21271 반도체 제조업 반도체 제조용 장비 2025-02-12 12월 조창현 http://iste.co.kr/ 경기도
유가증권 LG씨엔에스 06440 컴퓨터 프로그래밍, 시스템 통합 및 관리업 컨설팅, 시스템 구축/운영, 토탈 아웃소싱 및 AI, 클라우드·스마트팩토리 등 IT신기술 기반의 DX사업 2025-02-05 12월 현신균 http://www.lgcns.com 서울특별시
코스닥 아이지넷 46298 기타 정보 서비스업 보험 서비스 어플리케이션, 기업용 보험 솔루션 2025-02-04 12월 김창균, 김지태  서울특별시
코스닥 피아이이 45245 특수 목적용 기계 제조업 AI 비전 솔루션 및 스마트팩토리 솔루션 2025-02-04 12월 최정일, 김현준 http://piegroup.co.kr 경기도
코스닥 삼양엔씨켐 48263 기타 화학제품 제조업 반도체 포토레지스트용 기초화합물(KrF PR용 소재, ArF PR용 소재, Wet Chemical) 2025-02-03 12월 정회식 http://www.samyangncchem.com 경기도
코스닥 데이원컴퍼니 37316 기타 교육기관 성인대상 교육서비스 2025-01-24 12월 이강민 http://day1company.co.kr/ 서울특별시
코스닥 아스테라시스 45095 의료용 기기 제조업 피부 미용의료기기 제조, 판매 2025-01-24 12월 서은택 http://asterasys.com 서울특별시
코스닥 와이즈넛 09625 소프트웨어 개발 및 공급업 검색엔진, 챗봇, 클라우드서비스 2025-01-24 12월 강용성 http://www.wisenut.com/ 경기도
코스닥 미트박스 47546 기타 정보 서비스업 축산물 도소매 판매 및 중개 2025-01-23 12월 김기봉 http://www.meatbox.co.kr 서울특별시
코스닥 유안타제17호스팩 49379 금융 지원 서비스업 금융 지원 서비스업 2025-01-23 12월 윤원도  서울특별시
코스닥 블랙야크아이앤씨 47856 신발 및 신발 부분품 제조업 산업용 안전화, 안전복 및 안전용품 2025-01-21 12월 김태효 http://www.blackyakinc.com 서울특별시
코넥스 오션스바이오 33219 의료용 기기 제조업 전자약 2025-01-14 12월 이현웅  경상남도
코스닥 엠에프씨 43298 기초 의약물질 제조업 원료의약품(API) 및 핵심소재 2024-12-26 12월 황성관, 서기형(각자 대표이사) http://www.mfcglobal.co.kr 경기도
코스닥 파인메딕스 38757 의료용 기기 제조업 인젝터, 스네어, 나이프, 포셉 등 내시경용 시술기구 2024-12-26 12월 전성우, 김성철  대구광역시
코스닥 쓰리에이로직스 17790 반도체 제조업 NFC/IoT SoC 및 모듈 2024-12-24 12월 박광범, 이평한 http://www.3alogics.com/ 경기도
유가증권 GS피앤엘 49979 기타 금융업 지주회사 2024-12-23 12월 김원식 http://www.gspnl.com 서울특별시
코스닥 신한제14호스팩 48736 금융 지원 서비스업 금융 지원 서비스업 2024-12-23 12월 정우주  서울특별시
코넥스 유비씨 49581 소프트웨어 개발 및 공급업 디지털트윈 구현 플랫폼(Flexing CPS, Flexing DT 등) 2024-12-23 12월 조규종 http://uvc.co.kr 경기도
코넥스 창대정밀 36803 특수 목적용 기계 제조업 정밀금형 및 사출품 2024-12-23 12월 박제현, 박순민 http://www.i-changdae.com/ 경기도
코스닥 듀켐바이오 17675 의약품 제조업 방사성의약품 2024-12-20 12월 김상우 http://www.duchembio.com 서울특별시
코스닥 키움제10호스팩 48772 금융 지원 서비스업 기업 인수합병 2024-12-20 12월 김대식  서울특별시
코스닥 에스지헬스케어 39812 의료용 기기 제조업 의료용 영상진단기기 2024-12-19 12월 김정수 http://sghealthcare.com/ 경기도
코스닥 온코닉테라퓨틱스 47606 자연과학 및 공학 연구개발업 자큐보정(Zastaprazan, 소화기질환 신약), Nesuparib(표적항암제 신약) 2024-12-19 12월 김존 http://onconic.co.kr 서울특별시
코스닥 온코크로스 38215 자연과학 및 공학 연구개발업 AI플랫폼 기반 신약개발 용역서비스 2024-12-18 12월 김이랑, 강지훈 (각자대표) http://www.oncocross.com/ 서울특별시
코스닥 벡트 45760 영상 및 음향기기 제조업 프로젝터, 전자칠판, 전자교탁 및 관련 영상 소프트웨어, 콘텐츠 등 2024-12-16 12월 유창수 http://vect.co.kr 서울특별시
유가증권 엠앤씨솔루션 48487 특수 목적용 기계 제조업 방위산업용 유압식/전기식 부품 및 시스템 2024-12-16 12월 김병근 http://www.mncsolution.com 경상남도
코스닥 셀로맥스사이언스 47182 기타 식품 제조업 건강기능식품 2024-12-13 12월 서정민 http://cellromax.kr/ 경기도
코넥스 에이엠시지 49590 의료용 기기 제조업 심자계 2024-12-13 12월 서용성 http://www.amcg.kr/ 서울특별시
코스닥 KB제31호스팩 49222 금융 지원 서비스업 기업인수합병 2024-12-12 12월 김형철  서울특별시
코스닥 키움제11호스팩 48948 금융 지원 서비스업 기업 인수합병 2024-12-11 12월 조선희  서울특별시
유가증권 KB발해인프라 41564 신탁업 및 집합투자업  2024-11-29 12월 법인이사 케이비자산운용(주)  서울특별시
코스닥 디비금융제13호스팩 48973 기타 금융업 기업인수 및 합병 2024-11-28 12월 양준석  서울특별시
코스닥 교보17호스팩 48921 금융 지원 서비스업 기업인수합병 2024-11-21 12월 장정훈  서울특별시
코스닥 대신밸런스제19호스팩 48269 금융 지원 서비스업 기업 인수 및 합병 2024-11-20 12월 임병완  서울특별시
코스닥 위츠 45910 전자부품 제조업 무선충전소재, 부품 제조 2024-11-20 12월 김응태 http://www.ewits.co.kr/kr/ 경기도
코스닥 유디엠텍 38968 소프트웨어 개발 및 공급업 PLC eXpert, OPTRA Black-box, OPTRA Tracker 2024-11-20 12월 왕지남 http://www.udmtek.com 경기도
코스닥 RF시스템즈 47461 기타 금속 가공제품 제조업 방산제품(레이더시스템, 안테나시스템, 환경제어시스템 등) 2024-11-19 12월 한기우 http://www.rf-systems.co.kr/ 경기도
코스닥 사이냅소프트 46641 소프트웨어 개발 및 공급업 웹 기반 문서뷰어, 문서필터, 웹 에디터 등 2024-11-19 12월 전경헌 http:///www.synapsoft.co.kr 서울특별시
코스닥 하나34호스팩 48413 금융 지원 서비스업 기업인수목적 2024-11-19 12월 송하용  서울특별시
코스닥 에스켐 47566 기타 화학제품 제조업 OLED 유기화합물 등 2024-11-18 12월 염호영 http://www.s-chem.co.kr 충청북도
코스닥 엠오티 41339 특수 목적용 기계 제조업 이차전지 제조 자동화 설비 2024-11-18 12월 마점래 http://www.motfa.com 경상남도
코스닥 신한제15호스팩 48783 금융 지원 서비스업 금융 지원 서비스업 2024-11-15 12월 연오흠  서울특별시
코스닥 쓰리빌리언 39480 의료용 기기 제조업 유전체 분석 기반 희귀 유전질환 진단 검사 서비스 2024-11-14 12월 금창원  서울특별시
코스닥 닷밀 46458 영화, 비디오물, 방송프로그램 제작 및 배급업 실감미디어 콘텐츠 및 시설 구축, 전시 및 테마파크 운영 2024-11-13 12월 정해운  서울특별시
코스닥 노머스 47398 창작 및 예술관련 서비스업 공연기획 및 MD, Fromm 플랫폼 2024-11-12 12월 김영준 http://knowmerce.com 서울특별시
코스닥 에어레인 16328 일반 목적용 기계 제조업 기체분리막 모듈 및 시스템 2024-11-08 12월 하성용 http://www.airrane.com 충청북도
코스닥 토모큐브 47596 사진장비 및 광학기기 제조업 홀로토모그래피 HT-X1, HT-2H 2024-11-07 12월 박용근 http://www.tomocube.com 대전광역시
유가증권 더본코리아 47556 상품 종합 도매업 프랜차이즈 2024-11-06 12월 백종원, 강석원 http://www.theborn.co.kr/ 서울특별시
코스닥 에이치이엠파마 37627 자연과학 및 공학 연구개발업 맞춤형 헬스케어, LBP 디스커버리 플랫폼 2024-11-05 12월 지요셉 http://www.hempharma.bio 경기도
코스닥 에이럭스 47558 그외 기타 제품 제조업 교육용 드론/로봇 및 코딩 콘텐츠 2024-11-01 12월 이치헌 http://www.aluxonline.com 서울특별시
코스닥 탑런토탈솔루션 33668 전자부품 제조업 전장디스플레이 및 pOLED 부품 2024-11-01 12월 각 자 대표이사 박영근, 손종술 http://toprun.co.kr/ 경상북도
코스닥 성우 45865 일차전지 및 이차전지 제조업 이차전지 부품(2170 Topcap Ass'y, S4623 등), 자동차 전장부품(Motor Housing, EV Relay 등) 2024-10-31 12월 박종헌 http://www.e-sungwoo.co.kr 경상북도
코스닥 유진스팩11호 48806 금융 지원 서비스업 기업인수합병 2024-10-31 12월 박홍식  서울특별시
코넥스 타조엔터테인먼트 47671 창작 및 예술관련 서비스업 공연기획, 방송·공연 2024-10-30 12월 이성호 http://tajoyent.com/ 서울특별시
코스닥 클로봇 46610 소프트웨어 개발 및 공급업 로봇 소프트웨어(카멜레온, 크롬스) 2024-10-28 12월 각자 대표이사 김창구, 김경필 http://clobot.co.kr 경기도
코스닥 에이치엔에스하이텍 04499 전자부품 제조업 ACF(이방성전도필름), 수정진동자/수정발진기 2024-10-25 12월 김정희 http://www.hnshightech.com/ 대전광역시
코스닥 웨이비스 28993 반도체 제조업 GaN RF 칩, 패키지 트랜지스터, 모듈 등 2024-10-25 12월 한민석 http://www.wavice.com/ 경기도
코스닥 씨메스 47540 특수 목적용 기계 제조업 AI 기반 로봇 솔루션 및 3D 비전 솔루션 2024-10-24 12월 이성호 http://www.cmesrobotics.ai/ 서울특별시
코스닥 한켐 45737 기초 화학물질 제조업 OLED 발광층 소재 등 2024-10-22 12월 이상조 http://www.hanchem.net 대전광역시
코스닥 루미르 47417 항공기,우주선 및 부품 제조업 인공위성 시스템 및 전장품, 위성 영상 및 정보 2024-10-21 12월 남명용 http://www.lumir.space 경기도
코스닥 와이제이링크 20964 특수 목적용 기계 제조업 SMT(PCB 표면실장) 이송 및 추적장비 등 스마트 공정장비 2024-10-18 12월 박순일 http://www.yjlink.com 대구광역시
코스닥 인스피언 46548 소프트웨어 개발 및 공급업 SAP 보안 솔루션, SAP PO/CPI 컨설팅, EDI SaaS 플랫폼 2024-10-18 12월 최정규 http://www.inspien.co.kr 서울특별시
코스닥 셀비온 30843 의약품 제조업 셀비온그린주, 셀비온메브로페닌주, 도페정 등 2024-10-16 12월 김권 http://cellbion.co.kr 서울특별시
코스닥 제닉스 38162 특수 목적용 기계 제조업 Stocker, AGV/AMR 2024-09-30 12월 배성관 http://www.zenixkorea.co.kr/ 충청남도
코스닥 차이커뮤니케이션 35187 광고업 광고대행, 광고물 작성 2024-09-27 12월 최영섭 http://www.artistchai.co.kr 서울특별시
유가증권 한화비전 48979 기타 금융업 비금융지주회사 2024-09-27 12월 안순홍 http://www.hanwhavision.com 경기도
코스닥 KB제30호스팩 48663 금융 지원 서비스업 기업인수합병 2024-09-25 12월 박홍진  서울특별시
코스닥 아이언디바이스 46450 반도체 제조업 스마트폰용 오디오 앰프 반도체 Soc 2024-09-23 12월 박기태 http://www.irondevice.com/index.html 서울특별시
코스닥 미래에셋비전스팩7호 48268 금융 지원 서비스업 기업인수합병 2024-09-11 12월 송우영  서울특별시
코스닥 아이비젼웍스 46975 특수 목적용 기계 제조업 이차전지 검사시스템 및 검사시스템 설치셋업용역 2024-09-03 12월 길기재 http://www.ivw.co.kr/kor/main/ 대전광역시
코스닥 아이스크림미디어 46130 소프트웨어 개발 및 공급업 교육출판, 커머스, 연수 2024-08-30 12월 허주환, 현준우(각자대표) http://www.i-screammedia.com 경기도
코스닥 이엔셀 45607 기초 의약물질 제조업 첨단바이오의약품 위탁개발생산(CDMO) 서비스 / 차세대 세포,유전자 치료제 2024-08-23 12월 장종욱 http://www.encellinc.com/ 서울특별시

코스닥 M83 47608 영화, 비디오물, 방송프로그램 제작 및 배급업 VFX 2024-08-22 12월 정성진 http://m83.co.kr 서울특별시
코스닥 대신밸런스제18호스팩 47878 금융 지원 서비스업 금융 지원 서비스업 2024-08-22 12월 문병식  서울특별시
코스닥 티디에스팜 46428 의약품 제조업 경피약물전달시스템(습포제, 첩부제) 2024-08-21 12월 김철준 http://www.tdspharm.com 경기도
코스닥 넥스트바이오메디컬 38965 의료용 기기 제조업 내시경용 지혈재, 혈관색전 미립구 2024-08-20 12월 이돈행 http://www.nextbiomedical.co.kr 인천광역시
코스닥 케이쓰리아이 43119 소프트웨어 개발 및 공급업 XR 실감형콘텐츠 2024-08-20 12월 이재영 http://www.k3i.co.kr 대전광역시
유가증권 전진건설로봇 07990 특수 목적용 기계 제조업 콘크리트 펌프카 2024-08-19 12월 고현국  충청북도
코스닥 유라클 08834 소프트웨어 개발 및 공급업 모바일 앱 개발 플랫폼 2024-08-16 12월 조준희 http://www.uracle.co.kr/ 서울특별시
코스닥 교보16호스팩 48252 금융 지원 서비스업 기업인수합병 2024-08-13 12월 정시화  서울특별시

In [2]:
page=1
company_infos=[]
while True:
    url2='https://kind.krx.co.kr/corpgeneral/corpList.do'
    payload = dict(method='searchCorpList', pageIndex=page, currentPageSize=100, 
                   orderMode=3, orderStat='D', searchType=13, fiscalYearEnd='all', 
                   location='all')
    r=requests.post(url2,data=payload)
    #print(r.status_code)
    soup = bs(r.content, 'lxml')
    total_page=int(soup.select_one('.info.type-00 > em').text.replace(',','')) // 100 +1
    for idx,tr in enumerate(soup.select("tbody>tr")):
        print(f'{page}/{total_page} 중 {idx+1}/{len(soup.select("tbody>tr"))} 작업중', end="\r")
        #tr= soup.select("tbody > tr")[i]
        stock_type= tr.select_one('td:nth-child(1) > img')['alt']
        company_name= tr.select_one('td:nth-child(1) > a')['title']
        stock_code= tr.select_one('td:nth-child(1) > a')['onclick'].split("'")[1]
        business_type=tr.select_one('td:nth-child(2)')['title']
        product=tr.select_one('td:nth-child(3)')['title']
        resi_date=tr.select_one('td:nth-child(4)').text
        settlement=tr.select_one('td:nth-child(5)').text
        ceo=tr.select_one('td:nth-child(6)')['title']
        homepage=tr.select_one('td:nth-child(7) > a')['href'] if tr.select_one('td:nth-child(7) > a') !=None else ""
        region=tr.select_one('td:nth-child(8)').text
        company_infos.append((stock_type,company_name,stock_code,business_type,product,resi_date,settlement,ceo,homepage,region))
    if page < total_page:
        page+=1
    else:
        break
    
company_infos

[('코스닥',
  '한국피아이엠',
  '44890',
  '자동차 신품 부품 제조업',
  '내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행 부품(카메라 모듈 케이스)',
  '2025-04-04',
  '12월',
  '송준호',
  'http://www.pimkorea.com',
  '대구광역시'),
 ('코스닥',
  '에이유브랜즈',
  '48107',
  '섬유, 의복, 신발 및 가죽제품 소매업',
  '레인부츠, 스니커즈, 겨울화, 패션잡화 등',
  '2025-04-03',
  '12월',
  '김지훈',
  'http://aubrandz.irpage.co.kr',
  '서울특별시'),
 ('코스닥',
  '우양에이치씨',
  '10197',
  '구조용 금속제품, 탱크 및 증기발생기 제조업',
  '화공 플랜트, 에너지 플랜트',
  '2025-03-28',
  '12월',
  '김진태',
  'http://www.wooyang.co.kr',
  '경기도'),
 ('코스닥',
  '더즌',
  '46286',
  '전기 통신업',
  '디지털뱅킹 솔루션(B2B 금융 서비스)',
  '2025-03-24',
  '12월',
  '조철한',
  'http://www.dozn.co.kr/',
  '서울특별시'),
 ('코스닥',
  '심플랫폼',
  '44453',
  '소프트웨어 개발 및 공급업',
  'NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영)',
  '2025-03-21',
  '12월',
  '임대근, 강태신',
  'http://simplatform.com/',
  '서울특별시'),
 ('코스닥',
  '티엑스알로보틱스',
  '48481',
  '일반 목적용 기계 제조업',
  '물류자동화, 로봇자동화, AMR/AGV',
  '2025-03-20',
  '12월',
  '엄인섭',
  'http://www.txr.kr',
  '경기도'),
 ('코스닥',
  '한텍',
  '09807',
  '일반 목적용 기계 제조업',
  '열교환기 등 화공기기, 저장용 탱크',
  '2025-03-20',
  '12월',
  '김강식',
  'http://hantechltd.com',
  '울산광역시'),
 ('코스닥',
  '한화플러스제5호스팩',
  '49839',
  '금융 지원 서비스업',
  '-',
  '2025-03-20',
  '12월',
  '김광후',
  '',
  '서울특별시'),
 ('유가증권',
  '씨케이솔루션',
  '48037',
  '건축기술, 엔지니어링 및 관련 기술 서비스업',
  '드라이룸/클린룸 등 건물용 기계, 장비 설치 공사업',
  '2025-03-17',
  '12월',
  '김유곤, 안근표 (공동 대표이사)',
  'http://www.cksolution.co.kr/',
  '경기도'),
 ('유가증권',
  '서울보증보험',
  '03121',
  '보험업',
  '보증보험, 신용보험 등',
  '2025-03-14',
  '12월',
  '이명순',
  'http://www.sgic.co.kr',
  '서울특별시'),
 ('코스닥',
  '에스엠씨지',
  '46087',
  '유리 및 유리제품 제조업',
  '화장품 유리용기',
  '2025-03-07',
  '12월',
  '최승호',
  'http://www.somangglass.co.kr',
  '경기도'),
 ('코스닥',
  '엠디바이스',
  '22659',
  '전자부품 제조업',
  '반도체기억장치',
  '2025-03-07',
  '12월',
  '조호경',
  '',
  '경기도'),
 ('코스닥',
  '대진첨단소재',
  '39397',
  '플라스틱제품 제조업',
  '이차전지 공정용 대전방지트레이, 대전방지코팅액, 이차전지용 PET이형필름',
  '2025-03-06',
  '12월',
  '유성준, 장현주',
  'http://daejin2019.com',
  '서울특별시'),
 ('코스닥',
  '에르코스',
  '43557',
  '도시락 및 식사용 조리식품 제조업',
  '영유아식, 고령친화식품, 식물기반 대체식품',
  '2025-02-28',
  '12월',
  '김슬기',
  'http://www.ercohs.com',
  '대전광역시'),
 ('코스닥',
  '엘케이켐',
  '48950',
  '기타 화학제품 제조업',
  '반도체 소재(CP, PCP, DIS) 등',
  '2025-02-25',
  '12월',
  '이창엽',
  'http://lkchem.co.kr',
  '충청남도'),
 ('코스닥',
  '위너스',
  '47996',
  '기타 전기장비 제조업',
  '배선기구(스위치, 콘센트, 멀티탭), 전기차 충전기(급속, 완속)',
  '2025-02-24',
  '12월',
  '김창성',
  'http://www.wns21.co.kr/',
  ''),
 ('코스닥',
  '모티브링크',
  '46348',
  '전자부품 제조업',
  'EV용 Main Transformer, EV용 Line Filter',
  '2025-02-20',
  '12월',
  '김기한',
  'http://evpart.co.kr',
  '경기도'),
 ('코스닥',
  '동국생명과학',
  '30381',
  '의약품 제조업',
  '조영제 완제 및 원료, 의료기기 유통',
  '2025-02-17',
  '12월',
  '박재원',
  'http://dkls.co.kr',
  '서울특별시'),
 ('코스닥',
  '오름테라퓨틱',
  '47583',
  '기초 의약물질 제조업',
  '항체약물접합체(ADC) 단백질 분해제(TPD) 연구 개발',
  '2025-02-14',
  '12월',
  '이승주',
  '',
  '대전광역시'),
 ('코스닥',
  '동방메디컬',
  '24055',
  '의료용 기기 제조업',
  '필러, 한방침',
  '2025-02-13',
  '12월',
  '김근식',
  'http://www.dongbangmedical.co.kr/',
  '충청남도'),
 ('코스닥',
  '아이에스티이',
  '21271',
  '반도체 제조업',
  '반도체 제조용 장비',
  '2025-02-12',
  '12월',
  '조창현',
  'http://iste.co.kr/',
  '경기도'),
 ('유가증권',
  'LG씨엔에스',
  '06440',
  '컴퓨터 프로그래밍, 시스템 통합 및 관리업',
  '컨설팅, 시스템 구축/운영, 토탈 아웃소싱 및 AI, 클라우드·스마트팩토리 등 IT신기술 기반의 DX사업',
  '2025-02-05',
  '12월',
  '현신균',
  'http://www.lgcns.com',
  '서울특별시'),
 ('코스닥',
  '아이지넷',
  '46298',
  '기타 정보 서비스업',
  '보험 서비스 어플리케이션, 기업용 보험 솔루션',
  '2025-02-04',
  '12월',
  '김창균, 김지태',
  '',
  '서울특별시'),
 ('코스닥',
  '피아이이',
  '45245',
  '특수 목적용 기계 제조업',
  'AI 비전 솔루션 및 스마트팩토리 솔루션',
  '2025-02-04',
  '12월',
  '최정일, 김현준',
  'http://piegroup.co.kr',
  '경기도'),
 ('코스닥',
  '삼양엔씨켐',
  '48263',
  '기타 화학제품 제조업',
  '반도체 포토레지스트용 기초화합물(KrF PR용 소재, ArF PR용 소재, Wet Chemical)',
  '2025-02-03',
  '12월',
  '정회식',
  'http://www.samyangncchem.com',
  '경기도'),
 ('코스닥',
  '데이원컴퍼니',
  '37316',
  '기타 교육기관',
  '성인대상 교육서비스',
  '2025-01-24',
  '12월',
  '이강민',
  'http://day1company.co.kr/',
  '서울특별시'),
 ('코스닥',
  '아스테라시스',
  '45095',
  '의료용 기기 제조업',
  '피부 미용의료기기 제조, 판매',
  '2025-01-24',
  '12월',
  '서은택',
  'http://asterasys.com',
  '서울특별시'),
 ('코스닥',
  '와이즈넛',
  '09625',
  '소프트웨어 개발 및 공급업',
  '검색엔진, 챗봇, 클라우드서비스',
  '2025-01-24',
  '12월',
  '강용성',
  'http://www.wisenut.com/',
  '경기도'),
 ('코스닥',
  '미트박스',
  '47546',
  '기타 정보 서비스업',
  '축산물 도소매 판매 및 중개',
  '2025-01-23',
  '12월',
  '김기봉',
  'http://www.meatbox.co.kr',
  '서울특별시'),
 ('코스닥',
  '유안타제17호스팩',
  '49379',
  '금융 지원 서비스업',
  '금융 지원 서비스업',
  '2025-01-23',
  '12월',
  '윤원도',
  '',
  '서울특별시'),
 ('코스닥',
  '블랙야크아이앤씨',
  '47856',
  '신발 및 신발 부분품 제조업',
  '산업용 안전화, 안전복 및 안전용품',
  '2025-01-21',
  '12월',
  '김태효',
  'http://www.blackyakinc.com',
  '서울특별시'),
 ('코넥스',
  '오션스바이오',
  '33219',
  '의료용 기기 제조업',
  '전자약',
  '2025-01-14',
  '12월',
  '이현웅',
  '',
  '경상남도'),
 ('코스닥',
  '엠에프씨',
  '43298',
  '기초 의약물질 제조업',
  '원료의약품(API) 및 핵심소재',
  '2024-12-26',
  '12월',
  '황성관, 서기형(각자 대표이사)',
  'http://www.mfcglobal.co.kr',
  '경기도'),
 ('코스닥',
  '파인메딕스',
  '38757',
  '의료용 기기 제조업',
  '인젝터, 스네어, 나이프, 포셉 등 내시경용 시술기구',
  '2024-12-26',
  '12월',
  '전성우, 김성철',
  '',
  '대구광역시'),
 ('코스닥',
  '쓰리에이로직스',
  '17790',
  '반도체 제조업',
  'NFC/IoT SoC 및 모듈',
  '2024-12-24',
  '12월',
  '박광범, 이평한',
  'http://www.3alogics.com/',
  '경기도'),
 ('유가증권',
  'GS피앤엘',
  '49979',
  '기타 금융업',
  '지주회사',
  '2024-12-23',
  '12월',
  '김원식',
  'http://www.gspnl.com',
  '서울특별시'),
 ('코스닥',
  '신한제14호스팩',
  '48736',
  '금융 지원 서비스업',
  '금융 지원 서비스업',
  '2024-12-23',
  '12월',
  '정우주',
  '',
  '서울특별시'),
 ('코넥스',
  '유비씨',
  '49581',
  '소프트웨어 개발 및 공급업',
  '디지털트윈 구현 플랫폼(Flexing CPS, Flexing DT 등)',
  '2024-12-23',
  '12월',
  '조규종',
  'http://uvc.co.kr',
  '경기도'),
 ('코넥스',
  '창대정밀',
  '36803',
  '특수 목적용 기계 제조업',
  '정밀금형 및 사출품',
  '2024-12-23',
  '12월',
  '박제현, 박순민',
  'http://www.i-changdae.com/',
  '경기도'),
 ('코스닥',
  '듀켐바이오',
  '17675',
  '의약품 제조업',
  '방사성의약품',
  '2024-12-20',
  '12월',
  '김상우',
  'http://www.duchembio.com',
  '서울특별시'),
 ('코스닥',
  '키움제10호스팩',
  '48772',
  '금융 지원 서비스업',
  '기업 인수합병',
  '2024-12-20',
  '12월',
  '김대식',
  '',
  '서울특별시'),
 ('코스닥',
  '에스지헬스케어',
  '39812',
  '의료용 기기 제조업',
  '의료용 영상진단기기',
  '2024-12-19',
  '12월',
  '김정수',
  'http://sghealthcare.com/',
  '경기도'),
 ('코스닥',
  '온코닉테라퓨틱스',
  '47606',
  '자연과학 및 공학 연구개발업',
  '자큐보정(Zastaprazan, 소화기질환 신약), Nesuparib(표적항암제 신약)',
  '2024-12-19',
  '12월',
  '김존',
  'http://onconic.co.kr',
  '서울특별시'),
 ('코스닥',
  '온코크로스',
  '38215',
  '자연과학 및 공학 연구개발업',
  'AI플랫폼 기반 신약개발 용역서비스',
  '2024-12-18',
  '12월',
  '김이랑, 강지훈 (각자대표)',
  'http://www.oncocross.com/',
  '서울특별시'),
 ('코스닥',
  '벡트',
  '45760',
  '영상 및 음향기기 제조업',
  '프로젝터, 전자칠판, 전자교탁 및 관련 영상 소프트웨어, 콘텐츠 등',
  '2024-12-16',
  '12월',
  '유창수',
  'http://vect.co.kr',
  '서울특별시'),
 ('유가증권',
  '엠앤씨솔루션',
  '48487',
  '특수 목적용 기계 제조업',
  '방위산업용 유압식/전기식 부품 및 시스템',
  '2024-12-16',
  '12월',
  '김병근',
  'http://www.mncsolution.com',
  '경상남도'),
 ('코스닥',
  '셀로맥스사이언스',
  '47182',
  '기타 식품 제조업',
  '건강기능식품',
  '2024-12-13',
  '12월',
  '서정민',
  'http://cellromax.kr/',
  '경기도'),
 ('코넥스',
  '에이엠시지',
  '49590',
  '의료용 기기 제조업',
  '심자계',
  '2024-12-13',
  '12월',
  '서용성',
  'http://www.amcg.kr/',
  '서울특별시'),
 ('코스닥',
  'KB제31호스팩',
  '49222',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-12-12',
  '12월',
  '김형철',
  '',
  '서울특별시'),
 ('코스닥',
  '키움제11호스팩',
  '48948',
  '금융 지원 서비스업',
  '기업 인수합병',
  '2024-12-11',
  '12월',
  '조선희',
  '',
  '서울특별시'),
 ('유가증권',
  'KB발해인프라',
  '41564',
  '신탁업 및 집합투자업',
  '',
  '2024-11-29',
  '12월',
  '법인이사 케이비자산운용(주)',
  '',
  '서울특별시'),
 ('코스닥',
  '디비금융제13호스팩',
  '48973',
  '기타 금융업',
  '기업인수 및 합병',
  '2024-11-28',
  '12월',
  '양준석',
  '',
  '서울특별시'),
 ('코스닥',
  '교보17호스팩',
  '48921',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-11-21',
  '12월',
  '장정훈',
  '',
  '서울특별시'),
 ('코스닥',
  '대신밸런스제19호스팩',
  '48269',
  '금융 지원 서비스업',
  '기업 인수 및 합병',
  '2024-11-20',
  '12월',
  '임병완',
  '',
  '서울특별시'),
 ('코스닥',
  '위츠',
  '45910',
  '전자부품 제조업',
  '무선충전소재, 부품 제조',
  '2024-11-20',
  '12월',
  '김응태',
  'http://www.ewits.co.kr/kr/',
  '경기도'),
 ('코스닥',
  '유디엠텍',
  '38968',
  '소프트웨어 개발 및 공급업',
  'PLC eXpert, OPTRA Black-box, OPTRA Tracker',
  '2024-11-20',
  '12월',
  '왕지남',
  'http://www.udmtek.com',
  '경기도'),
 ('코스닥',
  'RF시스템즈',
  '47461',
  '기타 금속 가공제품 제조업',
  '방산제품(레이더시스템, 안테나시스템, 환경제어시스템 등)',
  '2024-11-19',
  '12월',
  '한기우',
  'http://www.rf-systems.co.kr/',
  '경기도'),
 ('코스닥',
  '사이냅소프트',
  '46641',
  '소프트웨어 개발 및 공급업',
  '웹 기반 문서뷰어, 문서필터, 웹 에디터 등',
  '2024-11-19',
  '12월',
  '전경헌',
  'http:///www.synapsoft.co.kr',
  '서울특별시'),
 ('코스닥',
  '하나34호스팩',
  '48413',
  '금융 지원 서비스업',
  '기업인수목적',
  '2024-11-19',
  '12월',
  '송하용',
  '',
  '서울특별시'),
 ('코스닥',
  '에스켐',
  '47566',
  '기타 화학제품 제조업',
  'OLED 유기화합물 등',
  '2024-11-18',
  '12월',
  '염호영',
  'http://www.s-chem.co.kr',
  '충청북도'),
 ('코스닥',
  '엠오티',
  '41339',
  '특수 목적용 기계 제조업',
  '이차전지 제조 자동화 설비',
  '2024-11-18',
  '12월',
  '마점래',
  'http://www.motfa.com',
  '경상남도'),
 ('코스닥',
  '신한제15호스팩',
  '48783',
  '금융 지원 서비스업',
  '금융 지원 서비스업',
  '2024-11-15',
  '12월',
  '연오흠',
  '',
  '서울특별시'),
 ('코스닥',
  '쓰리빌리언',
  '39480',
  '의료용 기기 제조업',
  '유전체 분석 기반 희귀 유전질환 진단 검사 서비스',
  '2024-11-14',
  '12월',
  '금창원',
  '',
  '서울특별시'),
 ('코스닥',
  '닷밀',
  '46458',
  '영화, 비디오물, 방송프로그램 제작 및 배급업',
  '실감미디어 콘텐츠 및 시설 구축, 전시 및 테마파크 운영',
  '2024-11-13',
  '12월',
  '정해운',
  '',
  '서울특별시'),
 ('코스닥',
  '노머스',
  '47398',
  '창작 및 예술관련 서비스업',
  '공연기획 및 MD, Fromm 플랫폼',
  '2024-11-12',
  '12월',
  '김영준',
  'http://knowmerce.com',
  '서울특별시'),
 ('코스닥',
  '에어레인',
  '16328',
  '일반 목적용 기계 제조업',
  '기체분리막 모듈 및 시스템',
  '2024-11-08',
  '12월',
  '하성용',
  'http://www.airrane.com',
  '충청북도'),
 ('코스닥',
  '토모큐브',
  '47596',
  '사진장비 및 광학기기 제조업',
  '홀로토모그래피 HT-X1, HT-2H',
  '2024-11-07',
  '12월',
  '박용근',
  'http://www.tomocube.com',
  '대전광역시'),
 ('유가증권',
  '더본코리아',
  '47556',
  '상품 종합 도매업',
  '프랜차이즈',
  '2024-11-06',
  '12월',
  '백종원, 강석원',
  'http://www.theborn.co.kr/',
  '서울특별시'),
 ('코스닥',
  '에이치이엠파마',
  '37627',
  '자연과학 및 공학 연구개발업',
  '맞춤형 헬스케어, LBP 디스커버리 플랫폼',
  '2024-11-05',
  '12월',
  '지요셉',
  'http://www.hempharma.bio',
  '경기도'),
 ('코스닥',
  '에이럭스',
  '47558',
  '그외 기타 제품 제조업',
  '교육용 드론/로봇 및 코딩 콘텐츠',
  '2024-11-01',
  '12월',
  '이치헌',
  'http://www.aluxonline.com',
  '서울특별시'),
 ('코스닥',
  '탑런토탈솔루션',
  '33668',
  '전자부품 제조업',
  '전장디스플레이 및 pOLED 부품',
  '2024-11-01',
  '12월',
  '각 자 대표이사 박영근, 손종술',
  'http://toprun.co.kr/',
  '경상북도'),
 ('코스닥',
  '성우',
  '45865',
  '일차전지 및 이차전지 제조업',
  "이차전지 부품(2170 Topcap Ass'y, S4623 등), 자동차 전장부품(Motor Housing, EV Relay 등)",
  '2024-10-31',
  '12월',
  '박종헌',
  'http://www.e-sungwoo.co.kr',
  '경상북도'),
 ('코스닥',
  '유진스팩11호',
  '48806',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-10-31',
  '12월',
  '박홍식',
  '',
  '서울특별시'),
 ('코넥스',
  '타조엔터테인먼트',
  '47671',
  '창작 및 예술관련 서비스업',
  '공연기획, 방송·공연',
  '2024-10-30',
  '12월',
  '이성호',
  'http://tajoyent.com/',
  '서울특별시'),
 ('코스닥',
  '클로봇',
  '46610',
  '소프트웨어 개발 및 공급업',
  '로봇 소프트웨어(카멜레온, 크롬스)',
  '2024-10-28',
  '12월',
  '각자 대표이사 김창구, 김경필',
  'http://clobot.co.kr',
  '경기도'),
 ('코스닥',
  '에이치엔에스하이텍',
  '04499',
  '전자부품 제조업',
  'ACF(이방성전도필름), 수정진동자/수정발진기',
  '2024-10-25',
  '12월',
  '김정희',
  'http://www.hnshightech.com/',
  '대전광역시'),
 ('코스닥',
  '웨이비스',
  '28993',
  '반도체 제조업',
  'GaN RF 칩, 패키지 트랜지스터, 모듈 등',
  '2024-10-25',
  '12월',
  '한민석',
  'http://www.wavice.com/',
  '경기도'),
 ('코스닥',
  '씨메스',
  '47540',
  '특수 목적용 기계 제조업',
  'AI 기반 로봇 솔루션 및 3D 비전 솔루션',
  '2024-10-24',
  '12월',
  '이성호',
  'http://www.cmesrobotics.ai/',
  '서울특별시'),
 ('코스닥',
  '한켐',
  '45737',
  '기초 화학물질 제조업',
  'OLED 발광층 소재 등',
  '2024-10-22',
  '12월',
  '이상조',
  'http://www.hanchem.net',
  '대전광역시'),
 ('코스닥',
  '루미르',
  '47417',
  '항공기,우주선 및 부품 제조업',
  '인공위성 시스템 및 전장품, 위성 영상 및 정보',
  '2024-10-21',
  '12월',
  '남명용',
  'http://www.lumir.space',
  '경기도'),
 ('코스닥',
  '와이제이링크',
  '20964',
  '특수 목적용 기계 제조업',
  'SMT(PCB 표면실장) 이송 및 추적장비 등 스마트 공정장비',
  '2024-10-18',
  '12월',
  '박순일',
  'http://www.yjlink.com',
  '대구광역시'),
 ('코스닥',
  '인스피언',
  '46548',
  '소프트웨어 개발 및 공급업',
  'SAP 보안 솔루션, SAP PO/CPI 컨설팅, EDI SaaS 플랫폼',
  '2024-10-18',
  '12월',
  '최정규',
  'http://www.inspien.co.kr',
  '서울특별시'),
 ('코스닥',
  '셀비온',
  '30843',
  '의약품 제조업',
  '셀비온그린주, 셀비온메브로페닌주, 도페정 등',
  '2024-10-16',
  '12월',
  '김권',
  'http://cellbion.co.kr',
  '서울특별시'),
 ('코스닥',
  '제닉스',
  '38162',
  '특수 목적용 기계 제조업',
  'Stocker, AGV/AMR',
  '2024-09-30',
  '12월',
  '배성관',
  'http://www.zenixkorea.co.kr/',
  '충청남도'),
 ('코스닥',
  '차이커뮤니케이션',
  '35187',
  '광고업',
  '광고대행, 광고물 작성',
  '2024-09-27',
  '12월',
  '최영섭',
  'http://www.artistchai.co.kr',
  '서울특별시'),
 ('유가증권',
  '한화비전',
  '48979',
  '기타 금융업',
  '비금융지주회사',
  '2024-09-27',
  '12월',
  '안순홍',
  'http://www.hanwhavision.com',
  '경기도'),
 ('코스닥',
  'KB제30호스팩',
  '48663',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-09-25',
  '12월',
  '박홍진',
  '',
  '서울특별시'),
 ('코스닥',
  '아이언디바이스',
  '46450',
  '반도체 제조업',
  '스마트폰용 오디오 앰프 반도체 Soc',
  '2024-09-23',
  '12월',
  '박기태',
  'http://www.irondevice.com/index.html',
  '서울특별시'),
 ('코스닥',
  '미래에셋비전스팩7호',
  '48268',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-09-11',
  '12월',
  '송우영',
  '',
  '서울특별시'),
 ('코스닥',
  '아이비젼웍스',
  '46975',
  '특수 목적용 기계 제조업',
  '이차전지 검사시스템 및 검사시스템 설치셋업용역',
  '2024-09-03',
  '12월',
  '길기재',
  'http://www.ivw.co.kr/kor/main/',
  '대전광역시'),
 ('코스닥',
  '아이스크림미디어',
  '46130',
  '소프트웨어 개발 및 공급업',
  '교육출판, 커머스, 연수',
  '2024-08-30',
  '12월',
  '허주환, 현준우(각자대표)',
  'http://www.i-screammedia.com',
  '경기도'),
 ('코스닥',
  '이엔셀',
  '45607',
  '기초 의약물질 제조업',
  '첨단바이오의약품 위탁개발생산(CDMO) 서비스 / 차세대 세포,유전자 치료제',
  '2024-08-23',
  '12월',
  '장종욱',
  'http://www.encellinc.com/',
  '서울특별시'),
 ('코스닥',
  'M83',
  '47608',
  '영화, 비디오물, 방송프로그램 제작 및 배급업',
  'VFX',
  '2024-08-22',
  '12월',
  '정성진',
  'http://m83.co.kr',
  '서울특별시'),
 ('코스닥',
  '대신밸런스제18호스팩',
  '47878',
  '금융 지원 서비스업',
  '금융 지원 서비스업',
  '2024-08-22',
  '12월',
  '문병식',
  '',
  '서울특별시'),
 ('코스닥',
  '티디에스팜',
  '46428',
  '의약품 제조업',
  '경피약물전달시스템(습포제, 첩부제)',
  '2024-08-21',
  '12월',
  '김철준',
  'http://www.tdspharm.com',
  '경기도'),
 ('코스닥',
  '넥스트바이오메디컬',
  '38965',
  '의료용 기기 제조업',
  '내시경용 지혈재, 혈관색전 미립구',
  '2024-08-20',
  '12월',
  '이돈행',
  'http://www.nextbiomedical.co.kr',
  '인천광역시'),
 ('코스닥',
  '케이쓰리아이',
  '43119',
  '소프트웨어 개발 및 공급업',
  'XR 실감형콘텐츠',
  '2024-08-20',
  '12월',
  '이재영',
  'http://www.k3i.co.kr',
  '대전광역시'),
 ('유가증권',
  '전진건설로봇',
  '07990',
  '특수 목적용 기계 제조업',
  '콘크리트 펌프카',
  '2024-08-19',
  '12월',
  '고현국',
  '',
  '충청북도'),
 ('코스닥',
  '유라클',
  '08834',
  '소프트웨어 개발 및 공급업',
  '모바일 앱 개발 플랫폼',
  '2024-08-16',
  '12월',
  '조준희',
  'http://www.uracle.co.kr/',
  '서울특별시'),
 ('코스닥',
  '교보16호스팩',
  '48252',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-08-13',
  '12월',
  '정시화',
  '',
  '서울특별시'),
 ('코스닥',
  '뱅크웨어글로벌',
  '19948',
  '소프트웨어 개발 및 공급업',
  '국내외 은행 및 금융기업 대상 코어뱅킹 소프트웨어',
  '2024-08-12',
  '12월',
  '이경조, 이은중',
  'http://bankwareglobal.com',
  '서울특별시'),
 ('코스닥',
  '아이빔테크놀로지',
  '46047',
  '사진장비 및 광학기기 제조업',
  '생체현미경, CRO 서비스',
  '2024-08-06',
  '12월',
  '김필한',
  'http://www.ivimtech.com',
  '대전광역시'),
 ('코스닥',
  '피앤에스미캐닉스',
  '46094',
  '의료용 기기 제조업',
  '보행재활로봇 시스템',
  '2024-07-31',
  '12월',
  '박광훈',
  'http://walkbot.co.kr',
  '서울특별시'),
 ('유가증권',
  'HS효성',
  '48757',
  '기타 금융업',
  '지주사업',
  '2024-07-29',
  '12월',
  '조현상, 안성훈',
  'http://www.hshyosung.com',
  '서울특별시'),
 ('유가증권',
  '산일전기',
  '06204',
  '전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업',
  '유입, 몰드, 주상, 건식 변압기 등',
  '2024-07-29',
  '12월',
  '박동석',
  'http://www.sanil.co.kr',
  '경기도'),
 ('코스닥',
  '엔에이치스팩31호',
  '48189',
  '금융 지원 서비스업',
  '금융지원서비스업',
  '2024-07-26',
  '12월',
  '이시형',
  '',
  '서울특별시'),
 ('코스닥',
  'SK증권제13호스팩',
  '47395',
  '금융 지원 서비스업',
  '기업인수목적 주식회사',
  '2024-07-25',
  '12월',
  '임율표',
  '',
  '서울특별시'),
 ('코스닥',
  '엑셀세라퓨틱스',
  '37311',
  '기초 의약물질 제조업',
  'CellCor SFD/CD(세포배양배지)',
  '2024-07-15',
  '12월',
  '이의일',
  '',
  '서울특별시'),
 ('코스닥',
  '이베스트스팩6호',
  '47811',
  '금융 지원 서비스업',
  '기업인수목적 주식회사',
  '2024-07-12',
  '12월',
  '박용',
  '',
  '서울특별시'),
 ('유가증권',
  '시프트업',
  '46287',
  '소프트웨어 개발 및 공급업',
  '게임 소프트웨어',
  '2024-07-11',
  '12월',
  '김형태',
  'http://shiftup.co.kr',
  '서울특별시'),
 ('코스닥',
  '하스',
  '45033',
  '의료용품 및 기타 의약 관련제품 제조업',
  '리튬디실리케이트 수복소재(Amber block, Amber Ingot 등), 지르코니아 유치관',
  '2024-07-03',
  '12월',
  '김용수',
  'http://www.hassbio.com',
  '강원특별자치도'),
 ('코스닥',
  '이노스페이스',
  '46235',
  '항공기,우주선 및 부품 제조업',
  '소형발사체, 로켓추진기관, 과학로켓, 시험평가용역',
  '2024-07-02',
  '12월',
  '김수종',
  'http://www.innospc.com/',
  '세종특별자치시'),
 ('유가증권',
  '신한글로벌액티브리츠',
  '48185',
  '신탁업 및 집합투자업',
  '신탁 및 집합투자',
  '2024-07-01',
  '02월',
  '조준우',
  'http://shglobalreit.com',
  '서울특별시'),
 ('코스닥',
  '에이치브이엠',
  '29531',
  '1차 비철금속 제조업',
  'Ni계 합금, Fe계 합금, 스퍼터링타겟, Cu계 합금 등',
  '2024-06-28',
  '12월',
  '문승호',
  'http://hvm.co.kr/',
  '경기도'),
 ('코넥스',
  '팡스카이',
  '26635',
  '소프트웨어 개발 및 공급업',
  '게임 개발 및 리퍼블리싱',
  '2024-06-28',
  '12월',
  '이병진(단독대표이사)',
  'http://www.panggame.com/',
  '서울특별시'),
 ('코스닥',
  '하이젠알앤엠',
  '16019',
  '전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업',
  '전동기 및 발전기 (범용모터, 서보모터)',
  '2024-06-27',
  '12월',
  '김재학',
  'http://higenrnm.com',
  '경상남도'),
 ('코스닥',
  '한국제15호스팩',
  '47988',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-06-26',
  '12월',
  '유한',
  '',
  '서울특별시'),
 ('코스닥',
  '에스오에스랩',
  '46408',
  '측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외',
  '산업용 및 차량용 라이다(LiDAR)',
  '2024-06-25',
  '12월',
  '정지성',
  'http://soslab.co',
  '광주광역시'),
 ('코스닥',
  '미래에셋비전스팩6호',
  '47844',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-06-24',
  '12월',
  '정명훈',
  '',
  '서울특별시'),
 ('코스닥',
  '에이치엠씨제7호스팩',
  '47734',
  '금융 지원 서비스업',
  '기타금융',
  '2024-06-24',
  '12월',
  '조한종',
  '',
  '서울특별시'),
 ('유가증권',
  '파라다이스',
  '03423',
  '유원지 및 기타 오락관련 서비스업',
  '카지노, 호텔, 복합리조트',
  '2024-06-24',
  '12월',
  '최종환',
  'http://www.paradise.co.kr/ko/main',
  '서울특별시'),
 ('코스닥',
  '한중엔시에스',
  '10764',
  '전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업',
  '수냉식 냉각시스템 ESS Parts, 공랭식 ESS Module Parts, EV Module 및 내연기관 Parts',
  '2024-06-24',
  '12월',
  '김환식',
  'http://www.hjncs.com',
  '경상북도'),
 ('코스닥',
  'KB제29호스팩',
  '47839',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-06-21',
  '12월',
  '서영화',
  '',
  '서울특별시'),
 ('코스닥',
  '미래에셋비전스팩5호',
  '47747',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-06-19',
  '12월',
  '김대호',
  '',
  '서울특별시'),
 ('코스닥',
  '씨어스테크놀로지',
  '45887',
  '의료용 기기 제조업',
  '심전도검사솔루션 입원환자모니터링솔루션',
  '2024-06-19',
  '12월',
  '이영신',
  'http://seerstech.com',
  '경기도'),
 ('코스닥',
  '한국제14호스팩',
  '47753',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-06-19',
  '12월',
  '변성환',
  '',
  '서울특별시'),
 ('코스닥',
  '디비금융스팩12호',
  '47776',
  '기타 금융업',
  '기업인수 및 합병',
  '2024-06-18',
  '12월',
  '김창희',
  '',
  '서울특별시'),
 ('코스닥',
  '라메디텍',
  '46251',
  '의료용 기기 제조업',
  '초소형 레이저 의료기기  및 미용기기',
  '2024-06-17',
  '12월',
  '최종석',
  '',
  '서울특별시'),
 ('코스닥',
  '그리드위즈',
  '45345',
  '그외 기타 전문, 과학 및 기술 서비스업',
  '수요관리 서비스, 전기차 충전기 모뎀 등',
  '2024-06-14',
  '12월',
  '김구환',
  'http://www.gridwiz.com',
  '경기도'),
 ('코스닥',
  '다원넥스뷰',
  '32335',
  '사진장비 및 광학기기 제조업',
  'LSMB(Laser Micro Bonding System)',
  '2024-06-11',
  '12월',
  '남기중',
  'http://www.nexview.co.kr',
  '경기도'),
 ('코스닥',
  '미래에셋비전스팩4호',
  '47738',
  '금융 지원 서비스업',
  '기업인수목적회사(기타금융서비스)',
  '2024-05-29',
  '12월',
  '김정수',
  '',
  '서울특별시'),
 ('코스닥',
  '노브랜드',
  '14517',
  '편조의복 제조업',
  'Knit, Woven 의류',
  '2024-05-23',
  '12월',
  '김기홍',
  'http://www.nobland.com',
  '서울특별시'),
 ('코스닥',
  'KB제28호스팩',
  '47647',
  '금융 지원 서비스업',
  '기업인수합병',
  '2024-05-17',
  '12월',
  '고광범',
  '',
  '서울특별시'),
 ('코스닥',
  '아이씨티케이',
  '45601',
  '반도체 제조업',
  'PUF반도체,보안솔루션(보안반도체,정보통신모듈기기,정보통신용반도체) 제조,개발',
  '2024-05-17',
  '12월',
  '이정원',
  'http://www.ictk.com',
  '서울특별시'),
 ('유가증권',
  'HD현대마린솔루션',
  '44306',
  '건축기술, 엔지니어링 및 관련 기술 서비스업',
  'AM(After Market) 솔루션, 친환경 Retrofit, 디지털 제어',
  '2024-05-08',
  '12월',
  '이기동',
  'http://www.hd-marinesolution.com/',
  '경기도'),
 ('코스닥',
  'SK증권제12호스팩',
  '47300',
  '금융 지원 서비스업',
  '기업인수목적 주식회사',
  '2024-05-07',
  '12월',
  '이재혁',
  '',
  '서울특별시'),
 ('코스닥',
  '코칩',
  '12673',
  '전자부품 제조업',
  '소형 및 초소형 슈퍼커패시터',
  '2024-05-07',
  '12월',
  '손진형',
  'http://www.korchip.com',
  '경기도'),
 ('코스닥',
  '민테크',
  '45220',
  '측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외',
  '배터리 진단시스템, 배터리 시스템, 충방전 검사장비',
  '2024-05-03',
  '12월',
  '홍영진',
  'http://www.g-mintech.co.kr',
  '대전광역시'),
 ('코스닥',
  '카티스',
  '14043',
  '컴퓨터 프로그래밍, 시스템 통합 및 관리업',

In [3]:
columns = soup.select_one('table')['summary'].split(", ")
columns.insert(0,'주식종목')
columns.insert(2,'종목코드')
#print(columns)
df=pd.DataFrame(company_infos,columns=columns)
df

,주식종목,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,코스닥,한국피아이엠,44890,자동차 신품 부품 제조업,"내연기관 부품(터보차저, DCT변속기), IT 부품(스마트워치/스마트링), 자율주행...",2025-04-04,12월,송준호,http://www.pimkorea.com,대구광역시
1,코스닥,에이유브랜즈,48107,"섬유, 의복, 신발 및 가죽제품 소매업","레인부츠, 스니커즈, 겨울화, 패션잡화 등",2025-04-03,12월,김지훈,http://aubrandz.irpage.co.kr,서울특별시
2,코스닥,우양에이치씨,10197,"구조용 금속제품, 탱크 및 증기발생기 제조업","화공 플랜트, 에너지 플랜트",2025-03-28,12월,김진태,http://www.wooyang.co.kr,경기도
3,코스닥,더즌,46286,전기 통신업,디지털뱅킹 솔루션(B2B 금융 서비스),2025-03-24,12월,조철한,http://www.dozn.co.kr/,서울특별시
4,코스닥,심플랫폼,44453,소프트웨어 개발 및 공급업,NUBISON AIoT(산업용 데이터 수집과 산업용 AI서비스 운영),2025-03-21,12월,"임대근, 강태신",http://simplatform.com/,서울특별시
...,...,...,...,...,...,...,...,...,...,...
2756,유가증권,유한양행,00010,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이사 조욱제,http://www.yuhan.co.kr,서울특별시
2757,유가증권,CJ대한통운,00012,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,"신영수, 민영학 (각자 대표)",http://www.cjlogistics.com,서울특별시
2758,유가증권,경방,00005,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준, 김담",http://www.kyungbang.co.kr,서울특별시
2759,유가증권,유수홀딩스,00070,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2760,유가증권,한진중공업홀딩스,00348,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,http://www.hhic-holdings.com,경기도

# 데이터를 수집한 날짜를 포함해서 파일명을 만들고 저장하기

In [214]:
from datetime import datetime
today=datetime.now()
print(f"{today.year}{today.month:02d}{today.day:02d}")
today=f"{today.year}{today.month:02d}{today.day:02d}"

20250404

In [215]:
df.to_csv(f"./scraping_results/상장기업정보({today}).csv",encoding="utf-8",index=False)

# 수집한 자료를 데이터베이스에 저장하기

In [217]:
from sqlalchemy import create_engine, text
import pymysql
pymysql.install_as_MySQLdb()

* sqlalchemy의 create_engine을 이용해서 mysql 서버에 접속
    * engine 생성
    * engine : 파이썬과 DB 연결 시 접속하게 되는 경로, id, password 등 입력해주는 것
    
engine = create_engine("mysql+pymysql://user id:password@ip주소:port번호/데이터베이스 이름")

* localhost=127.0.0.1

In [220]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/stock_info")

In [221]:
# engine.connect 하면 create_engine에 있는 정보로 DB접속
conn = engine.connect()

In [222]:
#데이터프레임을 DB에 저장하기
# 데이터프레임명.to_sql("테이블명", con=오픈한 db)
df.to_sql(f"stock_company_info_{today}",con=conn, if_exists='replace', index=False)
conn.close()

# 판다스의 read_html을 이용해서 table 자료 한번에 가져오기

In [8]:
from io import StringIO

In [4]:
soup.select_one('table')

<table class="list type-00 tmt30" summary="회사명, 업종, 주요제품, 상장일, 결산월, 대표자명, 홈페이지, 지역">
<caption>목록</caption>
<colgroup>
<col width="*"/>
<col width="15%"/>
<col width="20%"/>
<col width="11%"/>
<col width="8%"/>
<col width="10%"/>
<col width="8%"/>
<col width="12%"/>
</colgroup>
<thead>
<tr class="first" id="title-contents">
</tr>
</thead>
<tbody>
<tr class="first">
<td class="first" title="(주)디에이치오토넥스"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00030'); return false;" title="DH오토넥스"> DH오토넥스</a> <img alt="관리종목" class="vmiddle legend" src="/images/common/icn_t_kwan.gif"/> </td>
<td class="textOverflow" title="통신 및 방송 장비 제조업">통신 및 방송 장비 제조업</td>
<td class="textOverflow" title="유,무선 통신장비">유,무선 통신장비</td>
<td class="txc">1975-06-09</td>
<td class="txc">12월</td>
<td class="txc" title="최준용">최준용</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.dayouplus.co.kr" target="_blank" title="http://www.dayouplus.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">전북특별자치도</td>
</tr>
<tr>
<td class="first" title="(주)BYC"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00146'); return false;" title="BYC"> BYC</a> </td>
<td class="textOverflow" title="봉제의복 제조업">봉제의복 제조업</td>
<td class="textOverflow" title="메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급">메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급</td>
<td class="txc">1975-06-02</td>
<td class="txc">12월</td>
<td class="txc" title="김 대 환">김 대..</td>
<td class="txc">
<a class="btn ico homepage" href="http://home.byc.co.kr" target="_blank" title="http://home.byc.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="케이지모빌리티(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00362'); return false;" title="KG모빌리티"> KG모빌리티</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="자동차용 엔진 및 자동차 제조업">자동차용 엔진 및 자동차 제조업</td>
<td class="textOverflow" title="자동차,자동차부품,차륜,정비 제조/도소매">자동차,자동차부품,차륜,정비 제조/도소매</td>
<td class="txc">1975-05-29</td>
<td class="txc">12월</td>
<td class="txc" title="곽재선, 황기영, 박장호(각자대표이사)">곽재선..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.kg-mobility.com" target="_blank" title="http://www.kg-mobility.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)SPC삼립"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00561'); return false;" title="SPC삼립"> SPC삼립</a> </td>
<td class="textOverflow" title="기타 식품 제조업">기타 식품 제조업</td>
<td class="textOverflow" title="빵,아이스크림,과자,케익,유산균음료,인스턴트식품,병조림,면류,식용유 제조,판매">빵,아이스크림,과자,케익,유산균음료,인스턴트식품,병조림,면류,식용유 제조,판매</td>
<td class="txc">1975-05-02</td>
<td class="txc">12월</td>
<td class="txc" title="황종현, 김범수(각자 대표이사)">황종현..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.spcsamlip.co.kr" target="_blank" title="http://www.spcsamlip.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="흥국화재해상보험(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00054'); return false;" title="흥국화재"> 흥국화재</a> </td>
<td class="textOverflow" title="보험업">보험업</td>
<td class="textOverflow" title="손해보험">손해보험</td>
<td class="txc">1974-12-05</td>
<td class="txc">12월</td>
<td class="txc" title="송윤상">송윤상</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.insurance.co.kr" target="_blank" title="http://www.insurance.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="일양약품(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00757'); return false;" title="일양약품"> 일양약품</a> </td>
<td class="textOverflow" title="의약품 제조업">의약품 제조업</td>
<td class="textOverflow" title="일반의약품(원비디,영비천,아진탈,디세텔,노루모산),항암제(베타-이뮤난),전문의약품 제조,판매,수출입">일반의약품(원비디,영비천,아진탈,디세텔,노루모산),항암제(베타-이뮤난),전문의약품 제조,판매,수출입</td>
<td class="txc">1974-08-28</td>
<td class="txc">12월</td>
<td class="txc" title="김동연, 정유석">김동연..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.ilyang.co.kr" target="_blank" title="http://www.ilyang.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="(주)한진"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00232'); return false;" title="한진"> 한진</a> </td>
<td class="textOverflow" title="도로 화물 운송업">도로 화물 운송업</td>
<td class="textOverflow" title="포장화물,택배산업,항만하역,고속버스사업,운수보관">포장화물,택배산업,항만하역,고속버스사업,운수보관</td>
<td class="txc">1974-08-12</td>
<td class="txc">12월</td>
<td class="txc" title="노삼석">노삼석</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hanjin.com" target="_blank" title="http://www.hanjin.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="한국수출포장공업(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00220'); return false;" title="한국수출포장공업"> 한국수출포장공업</a> </td>
<td class="textOverflow" title="골판지, 종이 상자 및 종이용기 제조업">골판지, 종이 상자 및 종이용기 제조업</td>
<td class="textOverflow" title="골판지상자,골판지원지 제조,판매">골판지상자,골판지원지 제조,판매</td>
<td class="txc">1974-06-28</td>
<td class="txc">12월</td>
<td class="txc" title="대표이사 회장 허용삼
대표이사 사장 허정훈(각자대표이사)">대표이..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.keppack.co.kr" target="_blank" title="http://www.keppack.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="현대자동차(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00538'); return false;" title="현대자동차"> 현대자동차</a> <img alt="V100" class="vmiddle legend" src="/images/common/icn_t_v100.gif"/> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> <img alt="KTOP30" class="vmiddle legend" src="/images/common/icn_t_ktop.gif"/> </td>
<td class="textOverflow" title="자동차용 엔진 및 자동차 제조업">자동차용 엔진 및 자동차 제조업</td>
<td class="textOverflow" title="자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업">자동차(승용차,버스,트럭,특장차),자동차부품,자동차전착도료 제조,차량정비사업</td>
<td class="txc">1974-06-28</td>
<td class="txc">12월</td>
<td class="txc" title="정의선, 이동석, 무뇨스 바르셀로 호세 안토니오(각자 대표이사)">정의선..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hyundai.com" target="_blank" title="http://www.hyundai.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)모나미"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00536'); return false;" title="모나미"> 모나미</a> </td>
<td class="textOverflow" title="생활용품 도매업">생활용품 도매업</td>
<td class="textOverflow" title="BP153(BALL POINT PEN), P-3000(PLUS PEN), 유성매직, 보드마카, 네임펜, PARKER, WARTERMAN, 색연필">BP153(BALL POINT PEN), P-3000(PLUS PEN), 유성매직, 보드마카, 네임펜, PARKER, WARTERMAN, 색연필</td>
<td class="txc">1974-06-26</td>
<td class="txc">12월</td>
<td class="txc" title="송하경">송하경</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.monami.com" target="_blank" title="http://www.monami.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="한화솔루션(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00983'); return false;" title="한화솔루션"> 한화솔루션</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기초 화학물질 제조업">기초 화학물질 제조업</td>
<td class="textOverflow" title="합성수지,유화부문(LDPE,LLDPE)제품 제조,플라스틱가공품(PVC),CA,무기화학제품,부동산업">합성수지,유화부문(LDPE,LLDPE)제품 제조,플라스틱가공품(PVC),CA,무기화학제품,부동산업</td>
<td class="txc">1974-06-19</td>
<td class="txc">12월</td>
<td class="txc" title="남정운, 홍정권, 김동관">남정운..</td>
<td class="txc">
<a class="btn ico homepage" href="http://hcc.hanwha.co.kr" target="_blank" title="http://hcc.hanwha.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="아세아(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00203'); return false;" title="아세아"> 아세아</a> </td>
<td class="textOverflow" title="회사 본부 및 경영 컨설팅 서비스업">회사 본부 및 경영 컨설팅 서비스업</td>
<td class="textOverflow" title="회사본부,지주회사 및 경영컨설팅 서비스업">회사본부,지주회사 및 경영컨설팅 서비스업</td>
<td class="txc">1974-06-03</td>
<td class="txc">12월</td>
<td class="txc" title="이훈범, 오기호">이훈범..</td>
<td class="txc">
<a class="btn ico homepage" href="http://asiaholdings.co.kr" target="_blank" title="http://asiaholdings.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)카프로"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00638'); return false;" title="카프로"> 카프로</a> </td>
<td class="textOverflow" title="기초 화학물질 제조업">기초 화학물질 제조업</td>
<td class="textOverflow" title="카프로락탐,유안비료 제조">카프로락탐,유안비료 제조</td>
<td class="txc">1974-05-28</td>
<td class="txc">12월</td>
<td class="txc" title="박성명">박성명</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hcccapro.co.kr" target="_blank" title="http://www.hcccapro.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="롯데지주(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00499'); return false;" title="롯데지주"> 롯데지주</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주회사">지주회사</td>
<td class="txc">1974-02-16</td>
<td class="txc">12월</td>
<td class="txc" title="신동빈,이동우">신동빈..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.lotte.co.kr" target="_blank" title="http://www.lotte.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="대한방직(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00107'); return false;" title="대한방직"> 대한방직</a> </td>
<td class="textOverflow" title="직물직조 및 직물제품 제조업">직물직조 및 직물제품 제조업</td>
<td class="textOverflow" title="면사,화섬사,면직물 제조,판매,건설">면사,화섬사,면직물 제조,판매,건설</td>
<td class="txc">1973-12-28</td>
<td class="txc">12월</td>
<td class="txc" title="설 범, 김 인호">설 범..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.thtc.co.kr" target="_blank" title="http://www.thtc.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="서울식품공업(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00441'); return false;" title="서울식품공업"> 서울식품공업</a> </td>
<td class="textOverflow" title="기타 식품 제조업">기타 식품 제조업</td>
<td class="textOverflow" title="빵,스넥,마아가린,유지류,사료 제조,도매">빵,스넥,마아가린,유지류,사료 제조,도매</td>
<td class="txc">1973-12-28</td>
<td class="txc">12월</td>
<td class="txc" title="서성훈">서성훈</td>
<td class="txc">
<a class="btn ico homepage" href="http://seoul-food.co.kr" target="_blank" title="http://seoul-food.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">충청북도</td>
</tr>
<tr>
<td class="first" title="(주)아이에이치큐"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00356'); return false;" title="아이에이치큐"> 아이에이치큐</a> <img alt="관리종목" class="vmiddle legend" src="/images/common/icn_t_kwan.gif"/> </td>
<td class="textOverflow" title="영화, 비디오물, 방송프로그램 제작 및 배급업">영화, 비디오물, 방송프로그램 제작 및 배급업</td>
<td class="textOverflow" title="매니지먼트, 음반, 드라마 제작, 유료방송, 프로그램 공급, 광고대행">매니지먼트, 음반, 드라마 제작, 유료방송, 프로그램 공급, 광고대행</td>
<td class="txc">1973-12-18</td>
<td class="txc">12월</td>
<td class="txc" title="오준">오준</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.ihq.co.kr" target="_blank" title="http://www.ihq.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)LS네트웍스"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00068'); return false;" title="LS네트웍스"> LS네트웍스</a> </td>
<td class="textOverflow" title="상품 종합 도매업">상품 종합 도매업</td>
<td class="textOverflow" title="혁화,의류,등산용품 도매,제조/부동산 임대">혁화,의류,등산용품 도매,제조/부동산 임대</td>
<td class="txc">1973-11-15</td>
<td class="txc">12월</td>
<td class="txc" title="문성준">문성준</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.lsnetworks.co.kr" target="_blank" title="http://www.lsnetworks.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경상남도</td>
</tr>
<tr>
<td class="first" title="금호전기(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00121'); return false;" title="금호전기"> 금호전기</a> </td>
<td class="textOverflow" title="전구 및 조명장치 제조업">전구 및 조명장치 제조업</td>
<td class="textOverflow" title="형광등,백열전구,전구식현광등,실드빔(차량용전조) 제조,판매">형광등,백열전구,전구식현광등,실드빔(차량용전조) 제조,판매</td>
<td class="txc">1973-11-15</td>
<td class="txc">12월</td>
<td class="txc" title="이홍민">이홍민</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.khe.co.kr" target="_blank" title="http://www.khe.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="하이트진로홀딩스(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00014'); return false;" title="하이트진로홀딩스"> 하이트진로홀딩스</a> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주회사">지주회사</td>
<td class="txc">1973-09-19</td>
<td class="txc">12월</td>
<td class="txc" title="김인규">김인규</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hitejinroholdings.com" target="_blank" title="http://www.hitejinroholdings.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)노루홀딩스"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00032'); return false;" title="노루홀딩스"> 노루홀딩스</a> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주사업">지주사업</td>
<td class="txc">1973-08-10</td>
<td class="txc">12월</td>
<td class="txc" title="한영재,김용기">한영재..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.norooholdings.co.kr" target="_blank" title="http://www.norooholdings.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">경기도</td>
</tr>
<tr>
<td class="first" title="기아(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00027'); return false;" title="기아"> 기아</a> <img alt="V100" class="vmiddle legend" src="/images/common/icn_t_v100.gif"/> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> <img alt="KTOP30" class="vmiddle legend" src="/images/common/icn_t_ktop.gif"/> </td>
<td class="textOverflow" title="자동차용 엔진 및 자동차 제조업">자동차용 엔진 및 자동차 제조업</td>
<td class="textOverflow" title="승용차,중대형버스,트럭,민수특수차량,군수차량 제조,판매,정비">승용차,중대형버스,트럭,민수특수차량,군수차량 제조,판매,정비</td>
<td class="txc">1973-07-21</td>
<td class="txc">12월</td>
<td class="txc" title="송호성,최준영(각자 대표이사)">송호성..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.kia.co.kr" target="_blank" title="http://www.kia.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)효성"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00480'); return false;" title="효성"> 효성</a> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="스판덱스,합성원사,나일론,폴리에스터,타이어코드지,PET병,수지제품,중전기제품(변압기,차단기),사무용기계,컴퓨터 제조/건축공사">스판덱스,합성원사,나일론,폴리에스터,타이어코드지,PET병,수지제품,중전기제품(변압기,차단기),사무용기계,컴퓨터 제조/건축공사</td>
<td class="txc">1973-06-30</td>
<td class="txc">12월</td>
<td class="txc" title="조현준, 황윤언">조현준..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.hyosung.com" target="_blank" title="http://www.hyosung.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="CJ(주)"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00104'); return false;" title="CJ"> CJ</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="지주회사">지주회사</td>
<td class="txc">1973-06-29</td>
<td class="txc">12월</td>
<td class="txc" title="손경식, 김홍기">손경식..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.cj.net" target="_blank" title="http://www.cj.net"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)두산"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00015'); return false;" title="두산"> 두산</a> <img alt="KOSPI200" class="vmiddle legend" src="/images/common/icn_t_k200.gif"/> <img alt="KRX300" class="vmiddle legend" src="/images/common/icn_t_x300.gif"/> </td>
<td class="textOverflow" title="기타 금융업">기타 금융업</td>
<td class="textOverflow" title="동박적층판 등 제조 및 판매, 유압기기 등 제조 및 판매, 지게차 제조 및 판매, IT 시스템 개발/운영 서비스 등, 연료전지 등">동박적층판 등 제조 및 판매, 유압기기 등 제조 및 판매, 지게차 제조 및 판매, IT 시스템 개발/운영 서비스 등, 연료전지 등</td>
<td class="txc">1973-06-29</td>
<td class="txc">12월</td>
<td class="txc" title="박정원, 김민철, 유승우">박정원..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.doosancorp.co.kr" target="_blank" title="http://www.doosancorp.co.kr"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>
<td class="first" title="(주)휴스틸"><img alt="유가증권" class="vmiddle legend" src="/images/common/icn_t_yu.gif"/> <a href="#companysum" id="companysum" onclick="companysummary_open('00501'); return false;" title="휴스틸"> 휴스틸</a> </td>
<td class="textOverflow" title="1차 철강 제조업">1차 철강 제조업</td>
<td class="textOverflow" title="강관(배관용,구조용,유정용) 제조,도매">강관(배관용,구조용,유정용) 제조,도매</td>
<td class="txc">1973-06-29</td>
<td class="txc">12월</td>
<td class="txc" title="박훈, 윤형원(각자 대표이사)">박훈,..</td>
<td class="txc">
<a class="btn ico homepage" href="http://www.husteel.com" target="_blank" title="http://www.husteel.com"><span>홈페이지 보기</span></a>
</td>
<td class="txc">서울특별시</td>
</tr>
<tr>

In [9]:
pd.read_html(r.text)[0]

C:\Users\Admin\AppData\Local\Temp\ipykernel_6348\1880019241.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(r.text)[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,DH오토넥스,통신 및 방송 장비 제조업,"유,무선 통신장비",1975-06-09,12월,최준용,홈페이지 보기,전북특별자치도
1,BYC,봉제의복 제조업,"메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급",1975-06-02,12월,김 대..,홈페이지 보기,서울특별시
2,KG모빌리티,자동차용 엔진 및 자동차 제조업,"자동차,자동차부품,차륜,정비 제조/도소매",1975-05-29,12월,곽재선..,홈페이지 보기,경기도
3,SPC삼립,기타 식품 제조업,"빵,아이스크림,과자,케익,유산균음료,인스턴트식품,병조림,면류,식용유 제조,판매",1975-05-02,12월,황종현..,홈페이지 보기,경기도
4,흥국화재,보험업,손해보험,1974-12-05,12월,송윤상,홈페이지 보기,서울특별시
...,...,...,...,...,...,...,...,...
56,유한양행,의약품 제조업,"의약품(삐콤씨, 안티푸라민, 렉라자, 로수바미브, 코푸시럽 등), 생활용품(유한락스...",1962-11-01,12월,대표이..,홈페이지 보기,서울특별시
57,CJ대한통운,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,신영수..,홈페이지 보기,서울특별시
58,경방,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준,..",홈페이지 보기,서울특별시
59,유수홀딩스,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,홈페이지 보기,서울특별시
60,한진중공업홀딩스,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,조원국,홈페이지 보기,경기도