In [1]:
import os
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
import time
import datetime
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [143]:
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/135.0.0.0")
options.add_argument("lang=ko_KR")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )

## url 가져오기
url="https://play.google.com/store/apps/details?id=viva.republica.toss"
driver.get(url)

In [144]:
# 평점 및 리뷰 팝업창 열기
review_button =driver.find_element(By.CSS_SELECTOR,'button[aria-label="평점 및 리뷰 자세히 알아보기"]')
review_button.click()

In [19]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [145]:
# 팝업 창 정보 가져오기
wait = WebDriverWait(driver, 10)
review_page=wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,"div.fysCi.Vk3ZVd")))
#review_page

In [50]:
# 최신순으로 리뷰 정렬
# 정렬 버튼
order_button=driver.find_element(By.CSS_SELECTOR,'div[aria-label="관련성순"]')
order_button.click()

#최신순 선택
order_new=driver.find_element(By.CSS_SELECTOR,".z80M1.NmX0eb.KnEF3e[aria-label='최신']")
order_new.send_keys(Keys.ENTER)

In [146]:
max_retries=2
retries = 0
while retries < max_retries:
    try:
        # Find the "관련성순" button
        order_button = driver.find_element(By.CSS_SELECTOR, 'div[aria-label="관련성순"]')
        order_button.click()

        # Select the "최신" option
        order_new = driver.find_element(By.CSS_SELECTOR, ".z80M1.NmX0eb.KnEF3e[aria-label='최신']")
        order_new.send_keys(Keys.ENTER)
        break  # Exit the loop if the operation is successful
    except (NoSuchElementException, ElementNotInteractableException) as e:
        retries += 1
        if retries >= max_retries:
            raise Exception(f"Failed to sort reviews by newest after {max_retries} retries. Error: {e}")
        print(f"Failed to sort reviews by newest. Retrying ({retries}/{max_retries})...")

In [109]:
import re
#리뷰 리스트
review_list=driver.find_elements(By.CSS_SELECTOR,".RHo1pe")
for review in review_list:
    #작성자 닉네임
    print(review.find_element(By.CSS_SELECTOR,".X5PpBb").text)
    #별점
    aria_label=review.find_element(By.CSS_SELECTOR,'div[aria-label^="별표 5개 만점에 "]').get_attribute('aria-label')
    rating_pattern=r'별표 5개 만점에 (\d)개를 받았습니다\.'
    rating = re.search(rating_pattern, aria_label).group(1)
    print(rating)
    #작성 날짜
    print(review.find_element(By.CSS_SELECTOR,".bp9Aid").text)
    # 리뷰 내용
    print(review.find_element(By.CSS_SELECTOR,".h3YV2d").text)
    # 개발자 답변
    try:
        print(review.find_element(By.CSS_SELECTOR,".ras4vb").text)
    except Exception:
        print('답변 없음')
    # 공감 수
    try:
        useful_label=review.find_element(By.CSS_SELECTOR,".AJTPZc").text
        useful_pattern=r'사용자 (\d+)명이 이 리뷰가 유용하다고 평가함'
        useful = re.search(useful_pattern, useful_label).group(1)
        print(useful)
    except Exception:
        thumbs_up=None

정보영
1
2025년 4월 10일
자주쓰는계좌 업데이트 되었던데 이게 뭔가요.... 전처럼 사용자가 알아서 설정하게 원상복구 시켜주세요
안녕하세요. 정보영 님, 토스팀입니다. 서비스 변경으로 인해 불편을 드린 것 같아 마음이 무겁습니다. 말씀주신 부분은 현재 점진적으로 모든 고객님들 대상으로 변경이 될 예정으로 이전 홈 화면으로의 변경은 어려운 점 너그러운 마음으로 양해 부탁드립니다. 귀한 시간 내어 전달해주신만큼 담당부서로 전달 될 수 있도록 하겠으며, 더 나은 서비스를 제공 위해 노력하겠습니다. 보다 자세한 확인 및 안내를 위해 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 문의 부탁 드려도 될까요? 일부 안내의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.
내가왕이다
3
2025년 4월 10일
요 며칠 토스 친구가 안뜨네요. 저만 안뜨는게 아니고 주변에 몇 몇도 안뜬대요. 뜨는 사람들은 제 포인트를 먹는데 같이 블루투스 켜고 접속해도 저만 안뜰 많네요..
안녕하세요. 내가왕이다 님, 토스팀입니다. 1일 이내 상대를 만나 클릭한 기록이 있다면 다음날 00시까지 표시되지 않습니다. 위에 해당하지 않는다면 토스 앱 버전이 최신 버전인지 확인 하시어, ⓐ 기기 재부팅 후 블루투스 on/off 하여 재시도, ⓑ 기기 내의 블루투스 설정하는 화면에서 상대 기기가 정상적으로 검색 되는지, ⓒ 휴대폰 설정 - 애플리케이션 - 토스 - 위치권한이 활성화 되어 있는지, ⓓ 페어링 될 기기가 주변에 너무 많거나, 가로 막혀진 상황은 아닌지 상대방 기기에도 동일한 환경이어야 하므로 함께 확인해보실 수 있을까요? 그럼에도 동일하다면 24시간 운영되는 토스 고객센터로 문의 부탁드립니다.
유승민
1
2025년 4월 10일
카드 충전이 안되는데 무슨
안녕하세요. 유승민 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 점 양해 말씀 드립니다. 보다 자세한 확인 및 안내를 위해 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 문의 부탁 드려도 될까요? 일부 안내의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.
호두파이
4
2025년 4월 10일
다른건 다 좋은데 방금 두더지 잡기 이벤트 참여를 하려고 하니 비정상적인? 참여라고 나오는데 전 알림신청만 했는데 왜 할수 없는거죠 아무짓도 한게 없는데
안녕하세요, 고객님. 토스뱅크 고객센터 입니다. 두더지게임은 여러 고객님에게 혜택과 재미를 드리기 위해서 출시 했습니다. 공정한 게임 진행을 위하여 정상적인 참여에 안해서 혜택이 지급되는 과정이 추가 되었습니다. 현재는 고도화를 통하여 게임 참여 과정에서 불편함이 없도록 업데이트가 되었습니다. 정상적인 접근이 아니어서 소진된 기회는 원복이 불가 합니다. 링크 공유를 통해 추가 기회를 얻어 참여해 주시길 부탁 드립니다. 추가로 궁금하신 내용은 연중무휴, 24시간 운영되는 토스뱅크 고객센터 카카오톡(@tossbank)이나 전화(1661-7654)로 문의 주시면 빠르고 친절하게 도움 드리겠습니다.
_7타홍
1
2025년 4월 10일
이벤트를 만들어놓고 참여하게 유도했지만 아무것도 하지 않음에도 부정행위 감지로 참여조차 막아놓고 왜 그 이벤트를 보여준건가요? 불법프로그램을 깐것도 아니고, 토스 앱 구버전도 아니고, 매크로를 켜둔것도 아닌데 사람 놀리는건지
안녕하세요, 고객님. 토스뱅크 고객센터 입니다. 두더지게임은 여러 고객님에게 혜택과 재미를 드리기 위해서 출시 했습니다. 공정한 게임 진행을 위하여 정상적인 참여에 안해서 혜택이 지급되는 과정이 추가 되었습니다. 현재는 고도화를 통하여 게임 참여 과정에서 불편함이 없도록 업데이트가 되었습니다. 정상적인 접근이 아니어서 소진된 기회는 원복이 불가 합니다. 링크 공유를 통해 추가 기회를 얻어 참여해 주시길 부탁 드립니다. 추가로 궁금하신 내용은 연중무휴, 24시간 운영되는 토스뱅크 고객센터 카카오톡(@tossbank)이나 전화(1661-7654)로 문의 주시면 빠르고 친절하게 도움 드리겠습니다.
1
BH LEE
5
2025년 4월 10일
편해서 좋아요~
답변 없음
정찬민
4
2025년 4월 9일
요즘 8시되면 증권 급등 폭락 알림이 마구 뜨는데 막상 들어가서 보면 시세와 안 맞아요. 왜 그런가요. 매우 불편하네요
안녕하세요. 정찬민 님, 토스팀입니다. 우선 토스증권 서비스 이용에 불편을 드려 대단히 죄송합니다. 다만 남겨주신 내용만으로는 정확한 확인이 어려운 점 양해 말씀 드립니다. 보다 자세한 확인 및 안내를 위해 토스증권 고객센터 1599-7987 로 문의 부탁 드려도 될까요? 일부 안내의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.
심지현
1
2025년 4월 9일
그동안 잘 사용했는데 토스쇼핑 검색 기능이 그냥 쓰레기가 됐네요 저만 그런 건가요?? 뭐 옷 검색하면 같은 제품이 사이즈별로 옵션별로 쭈루룩 나뉘어져 있고요 단백질 쉐이크 검색하면 플라이밀만 15개 상품이 떠서 스크롤 내리는 데 한참 걸리네요 그 밑에 쉐이크베이비 16개 상품 그 밑에 또 플라이밀 2개 그 밑에 인테로 1개 그 밑에 하이뮨 8개... 이런 식이라 쇼핑을 할 수가 없네요 상품 정렬 기능도 없어졌고요
안녕하세요. 심지현 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나, 이용에 불편을 드린 것 같아 마음이 무겁습니다. 불편 느끼신 부분은 담당부서로 전달 드릴 예정이오며, 보다 만족스러운 서비스 제공할 수 있도록 노력하겠습니다. 다른 문의사항 있으실 경우 24시간 운영되는 카카오톡(@toss) 또는 토스 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
고기냉면
1
2025년 4월 9일
언어 설정 영어로 하면 뭐하냐. 어차피 안되는데
안녕하세요. 고기냉면 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 점 양해 말씀 드립니다. 보다 자세한 확인 및 안내를 위해 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 문의 부탁 드려도 될까요? 일부 안내의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.
포푸리
3
2025년 4월 9일
UI 7.0업뎃 후 잠금화면 만보기 파란 숫자의 가독성 떨어짐..눈 아파..
안녕하세요. 포푸리 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주셔서 감사합니다. 반영될 수 있다 확답 드리기는 어려우나, 고객님께서 말씀해주신 내용은 팀내에 공유하여 보다 편리한 토스 사용 경험을 하실 수 있도록 노력 하겠습니다. 다른 문의 사항이 있다면 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
JINU
1
2025년 4월 9일
홈화면 개악해놓은거.. 개발자들 개악인거 인정하시오. 개발자들도 이상한거 인정하죠? 무슨 기준으로 자주쓰는 계좌라고 판단하고 지맘대로 와리가리 배치하는거요? 사용자경험은 안중에도 없습니까? 최악 중 최악의 인터페이스 개악입니다. 그리고 답글담당자 만약에 이 댓글에 답글남길려면 "불편을 끼친 것 같아 죄송합니다" 라는 표현 쓰지마시오. 이 아래 답글에 다 이렇게써놨던데 지금 상황은 불편을 끼친 것 같은게 아니고 명확하게 불편을 끼친겁니다.
안녕하세요. JINU 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나, 불편을 끼쳐드려 죄송한 마음입니다. 불편 느끼신 부분은 담당부서로 전달 드릴 예정이오며, 보다 만족스러운 서비스 제공할 수 있도록 노력하겠습니다. 다른 문의사항 있으실 경우 24시간 운영되는 카카오톡(@toss) 또는 토스 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
2
# # (#)
2
2025년 4월 9일
토스에서 물건구매하고 품질에 문제가 있어 반품했는데 판매자가 거부해요. 그럼 구매자는 울며 겨자 먹기로 사야합니까??? 그럼 토스로 물건 구매를 못하지요. 온라인 쇼핑은 볼수도 만질 수도 없는데 반품이 보장 안되면 누가 구매를 합니다. 광고만 보고 살 순 없습니다ㅠㅠ. 반품이 안되면 토스 구매 거부운동할 겁니다ㅠㅠㅠ. 먼저 모든 언론사에 제보부터 할꺼구요.. 그 다음은 상상에 맡기겠습니다 **
안녕하세요. 박남규님, 토스팀입니다. 토스 홈 화면에서의 금액가리기를 말씀하시는게 맞으시다면, 아래의 경로로 진행 부탁드립니다. 훔 → 금액가리기 → 원하는 계좌 가리기 설정 설정이 안되시거나 다른 문의사항이 있으시다면, 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905로 편하실 때 언제든 문의 부탁 드립니다. 일부 응대의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다
24
송진모
1
2025년 4월 9일
왜 카드 받는 주소 수정이 안되나요?
안녕하세요. 송진모님, 토스팀입니다. 토스를 사용하시면서 사용에 불편을 드렸다면 죄송합니다. 유스카드를 신청하신 것 맞으실까요? 유스카드의 경우 신청당일만 취소가 가능하고, 다음날 부터는 주소를 변경하실 수는 없고, 일반우편으로 배송되기에, 배송에 영업일 기준 7~10일 소요될 수 있습니다. 다만, 문의주신 내용만으로는 확인이 어렵기 때문에 번거로우시겠지만 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
그게뭐임
1
2025년 4월 9일
송금 알림도 제대로 안떠, 만보기 복권 긁기 할때마다 광고 뜨고 쓸데없는 알림만 주구장창...ㅋㅋㅋㅋ 많은거 안바랍니다. 만보기 복권 광고만 없애주세요
안녕하세요. 그게뭐임님 토스팀입니다. 우선, 토스 이용에 불편함이 있으셨던 것 같아 마음이 무겁습니다. 이용하며 느끼신 소중한 의견 전달주셔서 감사합니다. 해당 내용은 담당부서 전달할 수 있도록 하겠습니다. 추가로 개선사항 전달주실 내용이 있으시다면 부득이 상세한 상담을 위해 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 언제든지 문의 부탁 드립니다. 일부 응대의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.
강태현
1
2025년 4월 9일
토스 이번주 미션의 게임 퍼즐오브z,워머신 두게임 모두 요구조건에 맞게 다했는데 포인트가 들어오지 않습니다. 제발 해결좀 해주세요 빨리
안녕하세요. 강태현 님, 토스팀입니다. 토스 앱 내에 이번주미션을 진행하셨는데 리워드를 못받으셨다면 아래의 경로로 문의 부탁드립니다. 토스 앱 → [혜택] 탭 → [이번 주 미션] → 아래 [미션했는데 포인트를 못 받았어요] → [문의하기]로 글을 남겨주실 수 있을까요? 문의 완료하시면 (주)엔비티 측에서 영업일 기준 3일 이내에 이메일로 답변 드리고 있습니다. 다른 문의사항이 있으신 경우 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 문의 부탁 드립니다. 감사합니다
송철선
1
2025년 4월 9일
로그인을 한 상테에서 다시 로그인을하라고하고,로그인이 너무 어렵다
안녕하세요. 송철선님, 토스팀입니다. 우선, 사용에 불편을 드려서 죄송합니다. 다만, 남겨주신 내용만으로는 정확한 확인이 어려운 점 양해 말씀 드립니다. 로그인이 불가하실 경우 보다 자세한 확인 및 안내를 위해 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 문의 부탁 드려도 될까요? 일부 안내의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.
고동준
1
2025년 4월 9일
일주일 방문미션 태그찾기 수십번 야그하면 뭐하나? 오늘도 끝까지 상품을 못찾았네요? 그상품 어디에 있는지 꼭 알려주시길 ㅋ 30분후에 다시 찾으라고? 그리고 그대로 찾아 답을 했는데 아니라네요?장난합니까?
안녕하세요. 고동준 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나, 이용에 불편을 드린 것 같아 마음이 무겁습니다. 불편 느끼신 부분은 담당부서로 전달 드릴 예정이오며, 보다 만족스러운 서비스 제공할 수 있도록 노력하겠습니다. 다른 문의사항 있으실 경우 24시간 운영되는 카카오톡(@toss) 또는 토스 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
27
이기섭
5
2025년 4월 9일
홈화면에 자주 확인한 계좌만 뜨게 바뀐게 너무 불편하네요. 예전에는 내가 자유롭게 커스텀해서 사용했는데 어느순간 바뀌었더라구요.. 자주 확인을 안하면 또 홈화면에서 사라지고 순서도 지들끼리 올라갔다 내려갔다 변하고 이러면 너무 불편한 것 아닙니까? 토스 정말 좋아하는데 이부분에서 살짝 정뚝털..ㅜㅡ
안녕하세요. 이기섭 님, 토스팀입니다. 먼저 토스를 이용해주셔서 감사합니다. 홈 화면은 다양한 방식으로 개편을 진행중에 있습니다, 다만 토스를 이용하시면서 불편하셨던 점이 있다면 토스의 개선을 위해 24시간 운영되는 토스 고객센터 전화 1599-4905 혹은 카카오톡(@toss)로 문의 부탁드립니다. 더욱 좋은 서비스를 제공할 수 있도록 고객님의 소중한 의견을 24시간 듣고 있습니다. 감사합니다.
3
HUNGYUN CHOO
1
2025년 4월 9일
토스 사용 할 때 마다 자꾸 인증 하라고 하는지 불편 해서 못쓰겠음 사용 할때마다 신분증 인증을 자꾸 하라고 그러고 1번 하는 걸로 족하지 않음? 제발 좀 인증 그만 하라고 해줘
안녕하세요. HUNGYUN CHOO 님, 토스팀입니다. 우선, 토스 이용에 불편을 드려 죄송합니다. 토스는 전자금융업자로 보안상 또는 법률에 의거 본인확인 절차를 거칠 수 있습니다. 다만, 남겨주신 내용만으로는 겪고 계신 불편사항의 자세한 내용 확인 및 해결이 어려운 점 양해 말씀 드립니다. 자세한 확인을 위하여 고객센터로 문의해주실 수 있을까요? 보다 정확한 상담을 위해 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 언제든지 문의 부탁 드립니다. 일부 응대의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다
DongHwan Kim
5
2025년 4월 8일
감사합니다. 너무 좋아요. 늘 고맙습니다. ^.~ 화이딩 부자 되세요. ^.^ 대박로...도... 호잇
답변 없음
박재화
1
2025년 4월 8일
토스만보기 좀 수정하세요 당첨도 안되는거 없애는게 나은듯 ;;
안녕하세요. 박재화 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나, 이용에 불편을 드린 것 같아 마음이 무겁습니다. 불편 느끼신 부분은 담당부서로 전달 드릴 예정이오며, 보다 만족스러운 서비스 제공할 수 있도록 노력하겠습니다. 다른 문의사항 있으실 경우 24시간 운영되는 카카오톡(@toss) 또는 토스 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
1
윤순중
4
2025년 4월 8일
토스를 즐겨하고 있는데 넘포인트가 조금주고 자꾸포인트가 줄어서 시간만 소비돼여 하기실어짐
안녕하세요. 윤순중님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나, 이용에 불편을 드린 것 같아 마음이 무겁습니다. 다만 혜택을 축소하기 위함이 아닌 더 다양한 혜택을 제공해드리고자 노력중이며 송금/결제/혜택 등을 무료로 제공해드리고 있는 만큼, 보다 많은 고객님들께 지속 가능한 서비스 제공을 위해 시행되는 내용인 점 너그럽게 양해 부탁 드립니다. 말씀 주신 소중한 의견 결코 흘려 듣지 않고 내부적으로 공유하여 향후 서비스 운영에 충분히 참고할 수 있도록 하겠습니다. 다른 문의사항이 있으시다면 24시간 운영되는 카카오톡(@toss) 또는 1599-4905로 문의 부탁드립니다. 감사합니다.
블루핑
1
2025년 4월 8일
해킹당한건가?? 숨겨놓은계좌들이 갑자기 쭉다보이길래 숨기기를다시햇는데도 계속 노출되있고 다시들어가면 숨기기 해제돼있고 또다시 숨겨놓으면 해제되있고 뭐죠? 들어와보니 업데이트뜨길래 업데이트안해서그런가싶어 업뎃해도 똑같네
안녕하세요. 블루핑 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 점 양해 말씀 드립니다. 보다 자세한 확인 및 안내를 위해 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 문의 부탁 드려도 될까요? 일부 안내의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.
1
문경수
1
2025년 4월 8일
가끔 이유없이 일부기능이 먹통됨
안녕하세요. 문경수 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나, 이용에 불편을 드린 것 같아 마음이 무겁습니다. 불편 느끼신 부분은 담당부서로 전달 드릴 예정이오며, 보다 만족스러운 서비스 제공할 수 있도록 노력하겠습니다. 다른 문의사항 있으실 경우 24시간 운영되는 카카오톡(@toss) 또는 토스 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
2
안창인
2
2025년 4월 8일

만보기 복권 긁고나면 적립이 안되거나 광고창에서 카운트가 멈추는 현상이 지속되고 있습니다. 업데이트도 해보고 새로깔아봐도 동일 증상 지속되고 있네요;;
안녕하세요. 안창인 님, 토스팀입니다. 토스 이용에 불편을 드려 죄송합니다. 다만 남겨주신 내용만으로는 정확한 확인이 어려운 점 양해 말씀 드립니다. 보다 자세한 확인 및 안내를 위해 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 문의 부탁 드려도 될까요? 일부 안내의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.
1
손주영
1
2025년 4월 8일
만보기 복권 실수로 광고 다 보고 뒤로가기 눌렀더니 그 뒤로 복권 긁고나면 흰 화면밖에 안보이고 돈을 못받아요..
안녕하세요. 손주영 님, 토스팀입니다. 토스 이용에 불편을 드려 죄송합니다. 다만 남겨주신 내용만으로는 정확한 확인이 어려운 점 양해 말씀 드립니다. 보다 자세한 확인 및 안내를 위해 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 문의 부탁 드려도 될까요? 일부 안내의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.
2
이강원
1
2025년 4월 8일
갤럭시 s25 울트라 차트볼때마다 앱크래시 겁나많이나네요 제발 수정좀
안녕하세요. 이강원 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄송하다는 말씀 드립니다. 고객님께서 말씀해주신 내용은 팀내에 공유하여 보다 편리한 토스증권 사용 경험을 하실 수 있도록 노력 하겠습니다. 다른 문의사항이 있으시다면 보다 자세한 확인 및 안내를 위해 토스증권 고객센터 1599-7987 로 문의 부탁 드려도 될까요? 일부 안내의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.
1
한기성
5
2025년 4월 8일
토스 카드 예쁜다!
답변 없음
Wjoo
1
2025년 4월 8일
오늘 토스로 대출받있는데 카뱅 대출에 비해 높은 대출만 나래비로 알려줬다는걸 대출 실행하고 봄.
안녕하세요, 고객님. 토스뱅크 고객센터입니다. 고객님 토스뱅크 이용중 불편을 드린 것 같아 죄송스럽습니다. 토스뱅크는 여러 대출 상품을 고객님의 상황에 맞춰 공급 해드리고 있습니다. 다만, 고객님께서 말씀해주신 내용만으로는 정확한 확인이 어렵습니다. 다소 불편하시겠지만, 연중무휴 24시간 운영되는 토스뱅크 고객센터 카카오톡(@tossbank)이나 전화(1661-7654)로 문의 주시면 빠르고 친절하게 도움 드리겠습니다. 고객님의 만족을 위해 언제나 최선을 다하겠습니다. 감사합니다.
김남두
5
2025년 4월 8일
3년째 토스 카뱅 쓰는데 토스정말 👍 입니다 광고도 짧고 혜택도 짱^^ 감사합니다
답변 없음
선숙영
4
2025년 4월 8일
개인적으로 굉장히 좋은 앱이라고 생각합니다. 가장 좋은 장점은 어린이 같은 미성현자도 돈의 중요성을 알수있어 좋고, 편리한기능만 정리되어있어 좋다고 생각합니다.
답변 없음
traveler stationary
2
2025년 4월 8일
고양이사료 도착했다는 알림 좀 안보낼수없나? 말같지도않는 냥냥거리는거 보기싫은데
안녕하세요. traveler stationary 님, 토스팀입니다.우선 의도치 않게 고객님께 불편을 드린 것 같아 죄송하다는 말씀드립니다. 고양이 키우고 간식 받기 서비스 관련 알림을 받지 않도록 설정하실 수 있는 방법 안내 도와드립니다. 【해제 방법】 토스 앱 → 오른쪽 아래 [전체] → 오른쪽 위 톱니바퀴 모양 [설정] → [알림] → [서비스별 알림] → [고양이 키우고 간식 받기] → 알림 해제 다른 문의가 있으시다면 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905로 편하실 때 언제든 문의 부탁 드립니다. 소중한 시간 내어 작성해주셨으나 즉시 도움 드리지 못해 죄송합니다. 감사합니다.
18
강수연
5
2025년 4월 8일
좋아요
답변 없음
Lurid
1
2025년 4월 8일
제발 홈화면 편집좀하게 해주세요. 제발 부탁해요 ㅡㅡ
안녕하세요. Lurid 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나, 이용에 불편을 드린 것 같아 마음이 무겁습니다. 불편 느끼신 부분은 담당부서로 전달 드릴 예정이오며, 보다 만족스러운 서비스 제공할 수 있도록 노력하겠습니다. 다른 문의사항 있으실 경우 24시간 운영되는 카카오톡(@toss) 또는 토스 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
9
힘찬하루
5
2025년 4월 8일
홈화면에서 계좌 순서 변경할 수 있도록 해 주세요~ 계좌 순서가 변경이 안돼서 불편합니다^^
안녕하세요. 힘찬하루 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주셔서 감사합니다. 반영될 수 있다 확답 드리기는 어려우나, 고객님께서 말씀해주신 내용은 팀내에 공유하여 보다 편리한 토스 사용 경험을 하실 수 있도록 노력 하겠습니다. 다른 문의 사항이 있다면 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
1
정JK
1
2025년 4월 8일
프로그램이 자꾸 튑니다~
안녕하세요. 정JK 님, 토스팀입니다. 우선 원활한 이용에 불편을 드려 죄송합니다. 토스 앱 사용이 원활하지 않으시다면 아래의 경로로 캐시 삭제 및 휴대폰 재부팅 진행 가능하실까요? 1. [Android 설정 > 애플리케이션 > 토스 > 저장공간 > 캐시 삭제] 2. [Android 설정 > 애플리케이션 > Android System WebView > 저장 공간 > 캐시 삭제] 위 안내드린 두가지 방법으로 진행 이후 휴대폰을 재부팅하여 정상 이용이 가능한지 확인해주시기 바라며, 지속 동일하게 이용이 어려우시다면 정확한 확인을 위해 24시간 운영되는 토스고객센터 1599-4905로 문의 부탁 드립니다. 감사합니다.
2
Hye Ju Hong
1
2025년 4월 8일
너무너무너무너무너무 느려요... 특히 고양이 키우기가 너무 버벅거립니다 제 폰이 3년된 폰이긴 하지만 다른 은행이나 쇼핑어플에선 느리다 생각해본적이 없는데 이상하게 토스만 그래요...ㅠ
안녕하세요. Hye Ju Hong 님, 토스팀입니다. 우선 원활한 이용에 불편을 드려 죄송합니다. 토스 앱 사용이 원활하지 않으시다면 아래의 경로로 캐시 삭제 진행 가능하실까요? 1. [Android 설정 > 애플리케이션 > 토스 > 저장공간 > 캐시 삭제] 2. [Android 설정 > 애플리케이션 > Android System WebView > 저장 공간 > 캐시 삭제] 위 안내드린 방법으로 진행 이후 휴대폰을 재부팅하여 정상 이용이 가능한지 확인해주시기 바라며, 지속 동일하게 이용이 어려우시다면 정확한 확인을 위해 24시간 운영되는 토스고객센터 1599-4905 로 문의 부탁 드립니다. 감사합니다.
3
록시땅 (릴)
1
2025년 4월 8일
토스가 자꾸 안열리고 꺼져요. 나흘 전까진 잘 썼는데 갑자기 이러니까 당혹스럽네요;;
안녕하세요. 록시땅 (릴) 님, 토스팀입니다. 우선 원활한 이용에 불편을 드려 죄송합니다. 토스 앱 사용이 원활하지 않으시다면 아래의 경로로 캐시 삭제 및 휴대폰 재부팅 진행 가능하실까요? 1. [Android 설정 > 애플리케이션 > 토스 > 저장공간 > 캐시 삭제] 2. [Android 설정 > 애플리케이션 > Android System WebView > 저장 공간 > 캐시 삭제] 위 안내드린 방법으로 진행 이후 휴대전화 단말기를 재부팅하여 정상 이용이 가능한지 확인해주시고 지속 동일하게 이용이 어려우시다면 정확한 확인을 위해 24시간 운영되는 토스고객센터 1599-4905 로 문의 부탁 드립니다. 감사합니다.
1
개밥
1
2025년 4월 7일
앱이 그냥 개무거움 다른 은행 앱들은 최적화 열심히 하는데 토스는 걍 손 놓고 광고만 싸는중 걍 다른 은행 앱 쓰세요
안녕하세요. 개밥 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나, 이용에 불편을 드린 것 같아 마음이 무겁습니다. 불편 느끼신 부분은 담당부서로 전달 드릴 예정이오며, 보다 만족스러운 서비스 제공할 수 있도록 노력하겠습니다. 다른 문의사항 있으실 경우 24시간 운영되는 카카오톡(@toss) 또는 토스 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
4
loco motion
3
2025년 4월 7일
광고 소리 없애고 보기만 하는건 안되는건가요? 음악들으면서 토스 앱 켜서 만보기든 고양이든 뭔가를 하려고 하면 자꾸 광고에서 재생되는 소리때매 음악 중지되고 짜증나네요. 그리고 젤 이해안가는거 도대체 만보기 1등 100만원, 2등 50만원, 10만원 이런거 진짜 주긴 하는건가요? 제 주변지인, 건너건너 인터넷블로그 싹다 뒤져봐도 실제 당첨 후기 올리능 사람 쥐똥만큼도 안보이고 아예 구라같고 의구심이 드는 부분이 있네요^^ 그냥 주기 싫으면 솔직하게 이런코너 없애시던가 하세요 몇년동안 단 한번도 20원이상 당첨돼본적도없고 고양이게임도 같은 그림 세개 나와본적이 단 한번도 없네요 거의 매일같이 꼬박꼬박 해도말이죠~ 좋은건 좋은데 제가 언급한 윗부분들에 대해서 답변좀 해주시져
안녕하세요. loco motion 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나, 이용에 불편을 드린 것 같아 마음이 무겁습니다. 토스 앱 내의 광고 소리의 경우 기기의 소리 설정으로 적용이 되기에 기기 설정을 음소거로 진행하신 후 이용을 부탁드려도될까요? 불편 느끼신 부분은 담당부서로 전달 드릴 예정이오며, 보다 만족스러운 서비스 제공할 수 있도록 노력하겠습니다. 다른 문의사항 있으실 경우 24시간 운영되는 카카오톡(@toss) 또는 토스 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
4

In [150]:
# 리뷰가 담긴 창을 찾아서 JavaScript로 8000px씩 아래로 스크롤
driver.execute_script("document.querySelector('.fysCi.Vk3ZVd').scrollBy(0, 8000)")

In [164]:

import re
#리뷰 리스트
review_list=driver.find_elements(By.CSS_SELECTOR,".RHo1pe")
for review in review_list:
    #작성자 닉네임
    nickname=review.find_element(By.CSS_SELECTOR,".X5PpBb").text
    #별점
    aria_label=review.find_element(By.CSS_SELECTOR,'div[aria-label^="별표 5개 만점에 "]').get_attribute('aria-label')
    rating_pattern=r'별표 5개 만점에 (\d)개를 받았습니다\.'
    rating = re.search(rating_pattern, aria_label).group(1)
    #작성 날짜
    date_label=review.find_element(By.CSS_SELECTOR,".bp9Aid").text
    date_pattern=r'(\d+)년 (\d+)월 (\d+)일'
    review_date=re.search(date_pattern, date_label)
    review_date=f"{int(review_date.group(1))}.{int(review_date.group(2)):02d}.{int(review_date.group(3)):02d}"
    # 리뷰 내용
    review_content=review.find_element(By.CSS_SELECTOR,".h3YV2d").text
    # 개발자 답변
    try:
        answer=review.find_element(By.CSS_SELECTOR,".ras4vb").text
    except Exception:
        answer=None
    # 공감 수
    try:
        useful_label=review.find_element(By.CSS_SELECTOR,".AJTPZc").text
        useful_pattern=r'사용자 (\d+)명이 이 리뷰가 유용하다고 평가함'
        useful = int(re.search(useful_pattern, useful_label).group(1))
    except Exception:
        useful=0
    temp=(nickname, rating, review_date, review_content, answer, useful)
    columns=('닉네임','별점','작성 날짜','리뷰','개발자 답변','공감 수')
    result=pd.DataFrame([temp],columns=columns)
    display(result)

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Yoseop Jeong,1,2025.04.10,메인화면에 노출되는 계좌 원래대로 다 나오게 돌려주세요 아니면 최소 사용자가 지정할...,"안녕하세요. Yoseop Jeong 님, 토스팀입니다. 서비스 변경으로 인해 불편을...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,바다김,3,2025.04.10,업뎃후 알림 바로가기안됨,"안녕하세요. 바다김 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 ...",4

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Itne Upne,1,2025.04.10,두더지 잡기 부정행위 했다는데 나는 아무짓도 안했음,"안녕하세요, 고객님. 토스뱅크 고객센터 입니다. 두더지게임은 여러 고객님에게 혜택과...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,박태환,1,2025.04.10,아니 접근성이 꺼져있다면서 나가게 하면서 기회도 다시안주는 토스 대단하다,"안녕하세요. 박태환 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,INY L,1,2025.04.10,너무 느려요. 로딩이 더딜때가 많아요. 다른앱들도 그러면 내핸드폰이 이상한가 할텐데...,"안녕하세요. INY L 님, 토스팀입니다. 우선 원활한 이용에 불편을 드려 죄송합니...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,김윤서,1,2025.04.10,자주 사용하는 계좌를 사용자가 변경할 수 있게 해주셔야되는거 아닌가요..? 너무 불...,"안녕하세요. 김윤서 님, 토스팀입니다. 서비스 변경으로 인해 불편을 드린 것 같아 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,물음표,1,2025.04.10,"갑자기 렉이 걸렸는지 앱이 들어가지지가 않네요,,","안녕하세요. 물음표 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,정보영,1,2025.04.10,자주쓰는계좌 업데이트 되었던데 이게 뭔가요.... 전처럼 사용자가 알아서 설정하게 ...,"안녕하세요. 정보영 님, 토스팀입니다. 서비스 변경으로 인해 불편을 드린 것 같아 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,내가왕이다,3,2025.04.10,요 며칠 토스 친구가 안뜨네요. 저만 안뜨는게 아니고 주변에 몇 몇도 안뜬대요. 뜨...,"안녕하세요. 내가왕이다 님, 토스팀입니다. 1일 이내 상대를 만나 클릭한 기록이 있...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,유승민,1,2025.04.10,카드 충전이 안되는데 무슨,"안녕하세요. 유승민 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,호두파이,4,2025.04.10,다른건 다 좋은데 방금 두더지 잡기 이벤트 참여를 하려고 하니 비정상적인? 참여라고...,"안녕하세요, 고객님. 토스뱅크 고객센터 입니다. 두더지게임은 여러 고객님에게 혜택과...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,_7타홍,1,2025.04.10,이벤트를 만들어놓고 참여하게 유도했지만 아무것도 하지 않음에도 부정행위 감지로 참여...,"안녕하세요, 고객님. 토스뱅크 고객센터 입니다. 두더지게임은 여러 고객님에게 혜택과...",1

      닉네임 별점       작성 날짜        리뷰 개발자 답변  공감 수
0  BH LEE  5  2025.04.10  편해서 좋아요~   None     0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,정찬민,4,2025.04.09,요즘 8시되면 증권 급등 폭락 알림이 마구 뜨는데 막상 들어가서 보면 시세와 안 맞...,"안녕하세요. 정찬민 님, 토스팀입니다. 우선 토스증권 서비스 이용에 불편을 드려 대...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,심지현,1,2025.04.09,그동안 잘 사용했는데 토스쇼핑 검색 기능이 그냥 쓰레기가 됐네요 저만 그런 건가요?...,"안녕하세요. 심지현 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,고기냉면,1,2025.04.09,언어 설정 영어로 하면 뭐하냐. 어차피 안되는데,"안녕하세요. 고기냉면 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,포푸리,3,2025.04.09,UI 7.0업뎃 후 잠금화면 만보기 파란 숫자의 가독성 떨어짐..눈 아파..,"안녕하세요. 포푸리 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,JINU,1,2025.04.09,홈화면 개악해놓은거.. 개발자들 개악인거 인정하시오. 개발자들도 이상한거 인정하죠?...,"안녕하세요. JINU 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였...",2

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,# # (#),2,2025.04.09,토스에서 물건구매하고 품질에 문제가 있어 반품했는데 판매자가 거부해요. 그럼 구매자...,"안녕하세요. 박남규님, 토스팀입니다. 토스 홈 화면에서의 금액가리기를 말씀하시는게 ...",24

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,송진모,1,2025.04.09,왜 카드 받는 주소 수정이 안되나요?,"안녕하세요. 송진모님, 토스팀입니다. 토스를 사용하시면서 사용에 불편을 드렸다면 죄...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,그게뭐임,1,2025.04.09,"송금 알림도 제대로 안떠, 만보기 복권 긁기 할때마다 광고 뜨고 쓸데없는 알림만 주...","안녕하세요. 그게뭐임님 토스팀입니다. 우선, 토스 이용에 불편함이 있으셨던 것 같아...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,강태현,1,2025.04.09,"토스 이번주 미션의 게임 퍼즐오브z,워머신 두게임 모두 요구조건에 맞게 다했는데 포...","안녕하세요. 강태현 님, 토스팀입니다. 토스 앱 내에 이번주미션을 진행하셨는데 리워...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,송철선,1,2025.04.09,"로그인을 한 상테에서 다시 로그인을하라고하고,로그인이 너무 어렵다","안녕하세요. 송철선님, 토스팀입니다. 우선, 사용에 불편을 드려서 죄송합니다. 다만...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,고동준,1,2025.04.09,일주일 방문미션 태그찾기 수십번 야그하면 뭐하나? 오늘도 끝까지 상품을 못찾았네요?...,"안녕하세요. 고동준 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으...",27

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,이기섭,5,2025.04.09,홈화면에 자주 확인한 계좌만 뜨게 바뀐게 너무 불편하네요. 예전에는 내가 자유롭게 ...,"안녕하세요. 이기섭 님, 토스팀입니다. 먼저 토스를 이용해주셔서 감사합니다. 홈 화...",3

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,HUNGYUN CHOO,1,2025.04.09,토스 사용 할 때 마다 자꾸 인증 하라고 하는지 불편 해서 못쓰겠음 사용 할때마다 ...,"안녕하세요. HUNGYUN CHOO 님, 토스팀입니다. 우선, 토스 이용에 불편을 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,DongHwan Kim,5,2025.04.08,감사합니다. 너무 좋아요. 늘 고맙습니다. ^.~ 화이딩 부자 되세요. ^.^ 대박...,None,0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,박재화,1,2025.04.08,토스만보기 좀 수정하세요 당첨도 안되는거 없애는게 나은듯 ;;,"안녕하세요. 박재화 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,윤순중,4,2025.04.08,토스를 즐겨하고 있는데 넘포인트가 조금주고 자꾸포인트가 줄어서 시간만 소비돼여 하기실어짐,"안녕하세요. 윤순중님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,블루핑,1,2025.04.08,해킹당한건가?? 숨겨놓은계좌들이 갑자기 쭉다보이길래 숨기기를다시햇는데도 계속 노출되...,"안녕하세요. 블루핑 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 ...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,문경수,1,2025.04.08,가끔 이유없이 일부기능이 먹통됨,"안녕하세요. 문경수 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으...",2

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,안창인,2,2025.04.08,만보기 복권 긁고나면 적립이 안되거나 광고창에서 카운트가 멈추는 현상이 지속되고 있...,"안녕하세요. 안창인 님, 토스팀입니다. 토스 이용에 불편을 드려 죄송합니다. 다만 ...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,손주영,1,2025.04.08,만보기 복권 실수로 광고 다 보고 뒤로가기 눌렀더니 그 뒤로 복권 긁고나면 흰 화면...,"안녕하세요. 손주영 님, 토스팀입니다. 토스 이용에 불편을 드려 죄송합니다. 다만 ...",2

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,이강원,1,2025.04.08,갤럭시 s25 울트라 차트볼때마다 앱크래시 겁나많이나네요 제발 수정좀,"안녕하세요. 이강원 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄송하다는...",1

   닉네임 별점       작성 날짜          리뷰 개발자 답변  공감 수
0  한기성  5  2025.04.08  토스 카드 예쁜다!   None     0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Wjoo,1,2025.04.08,오늘 토스로 대출받있는데 카뱅 대출에 비해 높은 대출만 나래비로 알려줬다는걸 대출 ...,"안녕하세요, 고객님. 토스뱅크 고객센터입니다. 고객님 토스뱅크 이용중 불편을 드린 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,김남두,5,2025.04.08,3년째 토스 카뱅 쓰는데 토스정말 👍 입니다 광고도 짧고 혜택도 짱^^ 감사합니다,None,0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,선숙영,4,2025.04.08,개인적으로 굉장히 좋은 앱이라고 생각합니다. 가장 좋은 장점은 어린이 같은 미성현자...,None,0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,traveler stationary,2,2025.04.08,고양이사료 도착했다는 알림 좀 안보낼수없나? 말같지도않는 냥냥거리는거 보기싫은데,"안녕하세요. traveler stationary 님, 토스팀입니다.우선 의도치 않게...",18

   닉네임 별점       작성 날짜   리뷰 개발자 답변  공감 수
0  강수연  5  2025.04.08  좋아요   None     0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Lurid,1,2025.04.08,제발 홈화면 편집좀하게 해주세요. 제발 부탁해요 ㅡㅡ,"안녕하세요. Lurid 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하...",9

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,힘찬하루,5,2025.04.08,홈화면에서 계좌 순서 변경할 수 있도록 해 주세요~ 계좌 순서가 변경이 안돼서 불편...,"안녕하세요. 힘찬하루 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 ...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,정JK,1,2025.04.08,프로그램이 자꾸 튑니다~,"안녕하세요. 정JK 님, 토스팀입니다. 우선 원활한 이용에 불편을 드려 죄송합니다....",2

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Hye Ju Hong,1,2025.04.08,너무너무너무너무너무 느려요... 특히 고양이 키우기가 너무 버벅거립니다 제 폰이 3...,"안녕하세요. Hye Ju Hong 님, 토스팀입니다. 우선 원활한 이용에 불편을 드...",3

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,록시땅 (릴),1,2025.04.08,토스가 자꾸 안열리고 꺼져요. 나흘 전까진 잘 썼는데 갑자기 이러니까 당혹스럽네요;;,"안녕하세요. 록시땅 (릴) 님, 토스팀입니다. 우선 원활한 이용에 불편을 드려 죄송...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,개밥,1,2025.04.07,앱이 그냥 개무거움 다른 은행 앱들은 최적화 열심히 하는데 토스는 걍 손 놓고 광고...,"안녕하세요. 개밥 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나...",4

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,loco motion,3,2025.04.07,광고 소리 없애고 보기만 하는건 안되는건가요? 음악들으면서 토스 앱 켜서 만보기든 ...,"안녕하세요. loco motion 님, 토스팀입니다. 만족스러운 서비스를 제공하기 ...",4

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,고진감래,1,2025.04.07,최악 중의 최악,"안녕하세요. 고진감래님 님, 토스팀입니다. 토스 서비스 이용에 불편을 드려 죄송합니...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,"GO SUNG, KIM",5,2025.04.07,항상 고마워요 모든것을 싸게 잘 살수있는 데 필요한 앱인 것 같아요 .,None,0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,박진우,1,2025.04.07,시스템이 왜 이렇게 느려요? 화면하나 넘어갈때도 일주일 이벤트도 다시 앱으로 돌아가...,"안녕하세요. 박진우 님, 토스팀입니다. 우선 원활한 이용에 불편을 드려 죄송합니다....",3

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,심예린,1,2025.04.07,광고 닫기 눌러도 안꺼짐 하 며칠째 이러는건지 최악이다,"안녕하세요. 심예린 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으...",3

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,배지현,1,2025.04.07,5개월 만보기. 100원도안되는데 사기그만 토스하는사람들 다것말이라고 누가당첨 적당...,"안녕하세요. 배지현 님, 토스팀입니다. 만보기 복권 당첨자는 매일 랜덤으로 새롭게 ...",7

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,이성진,1,2025.04.07,아니 토스 만보기 나이키광고 무한반복이네오 취소가 안됩니다..,"안녕하세요. 이성진 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으...",2

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,대한민국법좆까라그래,1,2025.04.07,광고보고 복권주고 당첨 후기 조작 확실하네 똑같은 후기가 두번 나오네 ㅋ 그따위로 ...,"안녕하세요. 고객님, 토스팀입니다. 만보기 복권 당첨자는 매일 랜덤으로 새롭게 집계...",10

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,허재원,5,2025.04.07,계좌알림이 갑자기준비중으로뜨는데 어떻게해야되나요,"안녕하세요. 허재원 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,임지훈,3,2025.04.07,토스증권 커뮤니티 너무 관리가 안되는거 같네요. 지속적인 조롱글을 신고해도 받아 들...,"안녕하세요. 임지훈 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄송하다는...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Joohyun Kim,1,2025.04.06,주식증권배당금얼마나들어와서뭔가안맞는것같네요.딱의심스럽습니다.얼마나들어와서뭔가빠졌는지...,"안녕하세요. Joohyun Kim 님, 토스팀입니다. 우선 토스증권 서비스 이용에 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,이학준,5,2025.04.06,토스님 덕분에 금융생활이 편해졌네요 토스톡은 추가 안하시나요 토스톡 나오면 중국산 ...,"안녕하세요. 이학준님, 토스팀입니다. 우선 귀한 시간내어 소중한 의견 전달해 주셔서...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,황장꾸,3,2025.04.06,안녕하세요 토스 고양이 키우기를 하고 있는데 장남감 받기가 원래 일정하게 1분 2분...,"안녕하세요. 황장꾸 님, 토스팀입니다. 먼저 서비스 이용에 불편을 드렸다면 대단히 ...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,류가네,1,2025.04.06,ㅎ 광고홍보 포인트 마음대로 지급이라고 상담해줌 ㅎ 웃기네요,"안녕하세요. 류가네 님, 토스팀입니다. 먼저 서비스 이용에 불편을 드렸다면 대단히 ...",0

   닉네임 별점       작성 날짜   리뷰 개발자 답변  공감 수
0  임영근  5  2025.04.06  빨라요   None     0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,강진희,1,2025.04.06,토스 깔아서 쓰는데 안에 돈 다 있는데 로그인하라 하면서 난리침 걍 깔아서 불평하지...,"안녕하세요. 강진희 님, 토스팀입니다. 사용에 불편을 드려 죄송합니다. 다만, 남겨...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,성우홍,1,2025.04.06,본인인증 한거 또하고 한거 또하고 한거 또하고 겁나 많이쓰네 진짜,"안녕하세요. 성우홍 님, 토스팀입니다. 토스는 금융앱으로 본인확인 절차를 거치신 후...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,정재원,1,2025.04.06,앱 실행하고 사용하는데 오류가 너무많아요,"안녕하세요. 정재원님, 토스팀입니다. 서비스 이용에 불편을 드려 죄송합니다. 다만,...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,appl aww,4,2025.04.05,뱅킹이랑 증권이랑 분리 좀 했으면.. 수시로 증권을 보는데 같이 있으니 불편하고 쓸...,"안녕하세요. appl aww님, 토스팀입니다. 우선 귀한 시간내어 소중한 의견 전달...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,김세빈,2,2025.04.05,업데이트 한 건진 모르겠지만 원래 안 그랬는데 이젠 앱 결제 하면 부모님 한테 사용...,"안녕하세요. 김세빈 님, 토스팀입니다. 토스페이로 결제 시 법정대리인에게 알림 문자...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,임유빈,3,2025.04.05,"토스유스카드 교통카드 잔액 환불,잔액 조회가 아예 안돼더라구요...","안녕하세요. 임유빈 님, 토스팀입니다. 우선 이용에 불편을 드려 죄송합니다. 재부팅...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,익명,1,2025.04.05,업데이트하고 앱이 그지가 됬네,"안녕하세요. 익명님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 점 ...",2

   닉네임 별점       작성 날짜 리뷰 개발자 답변  공감 수
0  이후서  5  2025.04.05  굿   None     0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,몬길아빠,5,2025.04.05,항상 잘쓰고있는데 요즘 게임광고하는건 좋은데 버그나는것좀 해결해줬으면 좋겠네요,"안녕하세요. 몬길아빠님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,김용무,1,2025.04.05,광고로 사업하나요 만보기도 역시 광고 때문에 하는것 같네요 10보를 걷던 만보를 걷...,"안녕하세요. 김용무님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나...",4

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,박도연,4,2025.04.05,입금출금 내역을 2개월전까지만 볼수 있는 건가요?,"안녕하세요. 박도연님, 토스팀입니다. 만 19세 이상이신 경우 마이데이터를 통해 연...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,현우,2,2025.04.05,딴건 다 좋은데 솔직히 만보기 복권 100만웡 50만원 당첨 다 구라죠? 어떻게 매...,"안녕하세요. 현우님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나,...",4

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,송송,1,2025.04.05,만보기 이벤트는 실망스러워요. 후기 말투 다 똑같고 사기 맞죠? 양심이 참... 정...,"안녕하세요. 송송님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나,...",16

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,김수현,4,2025.04.05,소비 복권 한번에 긁기 만들면 안되냐. 쥰내 귀찮네,"안녕하세요. 김수현님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였으나...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,롸롸,1,2025.04.05,비상금대출 받으려고 하는데 정보를 확인해주세요 라는 창만 뜨고 기다려도 아무것도 안...,"안녕하세요. 롸롸님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 점 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,박서현,1,2025.04.05,기프티콘 환불할라고 해도 채팅상담에 메뉴도 없고 진짜 짜증나요 어떻게 환불하라는 건가요,"안녕하세요. 박서현님, 토스팀입니다. 토스앱 - 전체 - 브랜드콘 - 내 브랜드콘 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Marlin O'jinger,1,2025.04.04,가면 갈수록 퇴보하는 어플리케이션의 대명사격. UX 고려 따윈 안 하고 별 해괴한 ...,"안녕하세요. Marlin O'jinger님, 토스팀입니다.만족스러운 서비스를 제공하...",2

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,이영헌,1,2025.04.04,실력이 안돼면 외주맡겨 제대로 하던지 태그던 전번이던 일치하는것만 올리든지 시간낭비...,"안녕하세요. 이영헌님, 토스팀입니다.만족스러운 서비스를 제공하기 위해 노력하였으나,...",6

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Tozun,1,2025.04.04,토스뱅크 주민등록증을 제대로 인식하지 못해서 송금을 막을 거면 왜 반대로 송금을 받...,"안녕하세요, 고객님. 토스뱅크 고객센터입니다. 고객님 토스뱅크 이용중 불편을 드린 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,김상미,1,2025.04.04,토스 업데이트 하기전에는 현질도 마음대로 되고 현금 뽑기 현금 토스에 넣기가 됬었는...,"안녕하세요. 김상미님, 토스팀입니다. 사용에 불편을 드려 죄송합니다. 다만, 남겨주...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,안전마진,5,2025.04.04,주식 거래소 통합모드로 사용중임에도 프리마켓이나 에프터마켓에선 조건주문시 입력한 가...,"안녕하세요. 안전마진 님, 토스팀입니다. 우선 토스증권 서비스 이용에 불편을 드려 ...",4

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,김익수,2,2025.04.04,자주 사용하는 계좌만 보이니 불편하네요. 토스 사용하는 이유가 여러개 계좌를 한번에...,"안녕하세요. 김익수 님, 토스팀입니다. 먼저 이용에 불편을 드려 죄송합니다. 홈 화...",2

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,성은하,4,2025.04.04,보상을 얻기위해 광고를 보는건 상관없는데 광고 좀 가려 받으면 안되나요?,"안녕하세요. 성은하님, 토스팀입니다. 사용에 불편을 드려 죄송합니다. 다만, 남겨주...",2

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Sunae Park,1,2025.04.04,토스증권 쓰지 마세요. 접속이 개구림,"안녕하세요. Sunae Park 님, 토스팀입니다. 우선 토스증권 서비스 이용에 불...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,성이름,1,2025.04.04,토스 공유하기 차단 안했는데 왜 상대방토스에선 내가 알림을 받을수없는 상태라고 나와...,"안녕하세요. 성이름님, 토스팀입니다. 상품 공유하고 포인트 받기 알림설정이 차단되어...",11

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,4444Z Z (Z4444Z),4,2025.04.04,토스증권에서 주식차트를 볼 때 차트를 누르고 드래그하면 진동이 울리는데 이 진동이 ...,"안녕하세요. 4444Z Z 님, 토스팀입니다. 먼저 토스증권 이용하시면서 느낀 소중...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,방pc,3,2025.04.04,만보기 그냥 원래대로 돌아가면 좋겠네요 지금 광고 때문에 하기가 싫어져요..,"안녕하세요. 방pc 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,haeyeong lee,4,2025.04.04,환율맞추기 성공률 표기가 있었으면 좋겠습니다.,"안녕하세요, 고객님. 토스뱅크 고객센터입니다. 고객님 토스뱅크를 이용해주셔서 감사합...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Minju Kim,1,2025.04.03,광고 닫는 버튼을 중국어인지 일본어인지로 해놓으면 어쩌라는?,"안녕하세요. Minju Kim 님, 토스팀입니다. 사용에 불편을 드려 죄송합니다. ...",2

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,박시현,1,2025.04.03,갑자기 생체인식에서 번호 인식으로 바껴버렸습니다 평소에 생체인식을 하다보니깐 번호를...,"안녕하세요. 박시현 님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,신지만,3,2025.04.03,갈수록 광고! 광고! 광고! 미쳐버리겠어요. 제발 소리라도 좀 선택할 수 있게 부탁...,"안녕하세요. 신지만 님, 토스팀입니다. 먼저 서비스 이용에 불편을 드렸다면 대단히 ...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,최진호,1,2025.04.03,토스 만보기가 휴대폰 상단에 안뜸 측정조차 안됨.,"안녕하세요. 최진호님, 토스팀입니다. 토스 이용에 불편을 겪으신 것 같아 죄송합니다...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,김병국,1,2025.04.03,어플이 접속이않돼 이따위로할거면운영하지마라,"안녕하세요. 김병국 님, 토스팀입니다. 먼저 이용에 불편을 드린 것 같아 마음이 무...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,이현화,3,2025.04.03,토스앱 다운로드 받으려면 넘 시간이 걸리는데 왜 그런지 모르겠네요..다른 앱은 빨리...,"안녕하세요. 이현화 님, 토스팀입니다. 먼저 토스 이용에 불편을 겪으신 것 같아 죄...",1

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,ByoungGeol Cho,1,2025.04.03,김밥 자르기 5천원까지 준다고 하더니 50원 넘어가니깐 0원만 나오네 사기 아님?,"안녕하세요. ByoungGeol Cho 님, 토스뱅크입니다. 남겨주신 내용만으로는 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,박상주,1,2025.04.03,첨엔 그러려니 했지만 갈수록 해도해도 광고가 너무 심합니다,"안녕하세요. 박상주 님, 토스팀입니다. 먼저 서비스 이용에 불편을 드렸다면 대단히 ...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,조주현,1,2025.04.03,환금액 8만얼마 나온다더니 갑자기 찾을 환금액 없데 니들이 먹냐?,"안녕하세요. 조주현 님, 토스팀입니다.남겨주신 내용만으로는 정확한 확인이 어려운 점...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,Andrew,3,2025.04.03,"메인 증권앱을 타 증권앱에서 토스앱으로 갈아타기 하였습니다만, 아래 내용이 개선되면...","안녕하세요. Andrew 님, 토스팀입니다. 먼저 토스증권 이용하시면서 느낀 소중한...",0

,닉네임,별점,작성 날짜,리뷰,개발자 답변,공감 수
0,최현준,1,2025.04.03,배당금 너무 늦게 주는거아님?,"안녕하세요. 최현준 님, 토스팀입니다. 우선 토스증권 서비스 이용에 불편을 드려 대...",0

In [163]:
#작성 날짜
review_date=review.find_element(By.CSS_SELECTOR,".bp9Aid").text

'2025.04.03'

In [ ]:
#리뷰일을 날짜형 데이터로 변경
review_date=review_date.replace('년','-').replace('월','-'),replace('일','-')
review_date=datetime.strptime(review_date,"%Y-%m-%d")
review_date

In [ ]:
#오늘로부터 1달 전 날짜 만들기
today=datetime.today()
twoyrago=today-timedelta(days=30)

In [ ]:
#리뷰들 중 가장 마지막 데이터의 날짜 추출해 날짜 데이터로 변환
review=driver.find_elements(By.CSS_SELECTOR,".RHo1pe")[-1]
end_Date=review.find_element(By.CSS_SELECTOR, "div.Jx4nYe > span.bp9Aid").text
end_date = end_date.replace("년 ", "-").replace("월 ", "-").replace("일", "")
end_date = datetime.strptime(end_date, "%Y-%m-%d")
end_date

In [ ]:
from tqdm import tqdm